-- Rollback for scripts/migrate9_event.sql (EVENT module columns).
-- Drops added indexes/columns. Data in dropped columns is lost.
-- SLUG backfill cannot be restored. Idempotent (safe to re-run). Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/migrate9_event_rollback.sql
SET XACT_ABORT ON;
BEGIN TRAN;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_TT_EVENT_ACTIVE' AND object_id = OBJECT_ID(N'dbo.T_TICKET_TYPE'))
  DROP INDEX IX_T_TT_EVENT_ACTIVE ON dbo.T_TICKET_TYPE;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_EVENT_MINE' AND object_id = OBJECT_ID(N'dbo.T_EVENT'))
  DROP INDEX IX_T_EVENT_MINE ON dbo.T_EVENT;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UQ_T_EVENT_SLUG' AND object_id = OBJECT_ID(N'dbo.T_EVENT'))
  DROP INDEX UQ_T_EVENT_SLUG ON dbo.T_EVENT;

IF COL_LENGTH(N'dbo.T_TICKET', N'PHONE') IS NOT NULL
  ALTER TABLE dbo.T_TICKET DROP COLUMN PHONE;
IF COL_LENGTH(N'dbo.T_TICKET', N'EMAIL') IS NOT NULL
  ALTER TABLE dbo.T_TICKET DROP COLUMN EMAIL;

IF COL_LENGTH(N'dbo.T_TICKET_TYPE', N'SORT_ORDER') IS NOT NULL
BEGIN
  ALTER TABLE dbo.T_TICKET_TYPE DROP CONSTRAINT DF_T_TT_SORT;
  ALTER TABLE dbo.T_TICKET_TYPE DROP COLUMN SORT_ORDER;
END
IF COL_LENGTH(N'dbo.T_TICKET_TYPE', N'IS_ACTIVE') IS NOT NULL
BEGIN
  ALTER TABLE dbo.T_TICKET_TYPE DROP CONSTRAINT DF_T_TT_ACTIVE;
  ALTER TABLE dbo.T_TICKET_TYPE DROP COLUMN IS_ACTIVE;
END
IF COL_LENGTH(N'dbo.T_TICKET_TYPE', N'MAX_PER_PERSON') IS NOT NULL
  ALTER TABLE dbo.T_TICKET_TYPE DROP COLUMN MAX_PER_PERSON;
IF COL_LENGTH(N'dbo.T_TICKET_TYPE', N'DESCRIPTION') IS NOT NULL
  ALTER TABLE dbo.T_TICKET_TYPE DROP COLUMN DESCRIPTION;

IF COL_LENGTH(N'dbo.T_EVENT', N'PUBLISHED_AT') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP COLUMN PUBLISHED_AT;
IF COL_LENGTH(N'dbo.T_EVENT', N'IS_DELETED') IS NOT NULL
BEGIN
  ALTER TABLE dbo.T_EVENT DROP CONSTRAINT DF_T_EVENT_DELETED;
  ALTER TABLE dbo.T_EVENT DROP COLUMN IS_DELETED;
END
IF COL_LENGTH(N'dbo.T_EVENT', N'CANCEL_REASON') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP COLUMN CANCEL_REASON;
IF COL_LENGTH(N'dbo.T_EVENT', N'TERMS') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP COLUMN TERMS;
IF COL_LENGTH(N'dbo.T_EVENT', N'SLUG') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP COLUMN SLUG;

COMMIT TRAN;
