-- Rollback Migration 14: MARKETING.
-- Removes MARKETING menus/module and new T_ tables / columns added by migrate14.
-- Safe to run even if migrate14 was partially applied (IF EXISTS guards).
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
GO

BEGIN TRAN;

DELETE FROM dbo.CPPERMISSION WHERE MENU_CODE IN (N'MENU_PROMO_CODES', N'MENU_AD_CAMPAIGNS', N'MENU_NEWS_MANAGEMENT');
DELETE FROM dbo.CPMENU WHERE CODE IN (N'MENU_PROMO_CODES', N'MENU_AD_CAMPAIGNS', N'MENU_NEWS_MANAGEMENT');
DELETE FROM dbo.CPMODULE WHERE CODE = N'MARKETING';

IF OBJECT_ID(N'dbo.T_PROMO_USAGE', N'U') IS NOT NULL DROP TABLE dbo.T_PROMO_USAGE;
IF OBJECT_ID(N'dbo.T_PROMO_SCOPE', N'U') IS NOT NULL DROP TABLE dbo.T_PROMO_SCOPE;
IF OBJECT_ID(N'dbo.T_AD_STAT_DAILY', N'U') IS NOT NULL DROP TABLE dbo.T_AD_STAT_DAILY;
IF OBJECT_ID(N'dbo.T_AD_POSITION', N'U') IS NOT NULL DROP TABLE dbo.T_AD_POSITION;

IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_NEWS_STATUS')
  ALTER TABLE dbo.T_NEWS DROP CONSTRAINT CK_T_NEWS_STATUS;
IF COL_LENGTH(N'dbo.T_NEWS', N'IS_DELETED') IS NOT NULL ALTER TABLE dbo.T_NEWS DROP COLUMN IS_DELETED;
IF COL_LENGTH(N'dbo.T_NEWS', N'SCHEDULED_AT') IS NOT NULL ALTER TABLE dbo.T_NEWS DROP COLUMN SCHEDULED_AT;
IF COL_LENGTH(N'dbo.T_NEWS', N'AUTHOR_CODE') IS NOT NULL ALTER TABLE dbo.T_NEWS DROP CONSTRAINT FK_T_NEWS_AUTHOR;
IF COL_LENGTH(N'dbo.T_NEWS', N'AUTHOR_CODE') IS NOT NULL ALTER TABLE dbo.T_NEWS DROP COLUMN AUTHOR_CODE;
-- Restore original DRAFT/PUBLISHED check
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_NEWS_STATUS')
  ALTER TABLE dbo.T_NEWS ADD CONSTRAINT CK_T_NEWS_STATUS CHECK (STATUS IN (N'DRAFT', N'PUBLISHED'));

IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_APPROVAL')
  ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT CK_T_AD_APPROVAL;
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_PAY')
  ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT CK_T_AD_PAY;
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_STATUS')
  ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT CK_T_AD_STATUS;
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'REJECT_NOTE') IS NOT NULL ALTER TABLE dbo.T_AD_CAMPAIGN DROP COLUMN REJECT_NOTE;
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'APPROVAL_STATUS') IS NOT NULL ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT DF_T_ADC_APPROVAL;
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'APPROVAL_STATUS') IS NOT NULL ALTER TABLE dbo.T_AD_CAMPAIGN DROP COLUMN APPROVAL_STATUS;
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'PAYMENT_STATUS') IS NOT NULL ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT DF_T_ADC_PAY;
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'PAYMENT_STATUS') IS NOT NULL ALTER TABLE dbo.T_AD_CAMPAIGN DROP COLUMN PAYMENT_STATUS;
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'COST') IS NOT NULL ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT DF_T_ADC_COST;
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'COST') IS NOT NULL ALTER TABLE dbo.T_AD_CAMPAIGN DROP COLUMN COST;
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'ORGANIZER_CODE') IS NOT NULL ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT FK_T_ADC_ORG;
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'ORGANIZER_CODE') IS NOT NULL ALTER TABLE dbo.T_AD_CAMPAIGN DROP COLUMN ORGANIZER_CODE;
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_STATUS')
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD CONSTRAINT CK_T_AD_STATUS CHECK (STATUS IN (N'ACTIVE', N'PAUSED', N'ENDED'));
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_POS')
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD CONSTRAINT CK_T_AD_POS CHECK (POSITION IN (N'HOME_BANNER', N'EVENT_LIST', N'SIDEBAR'));

IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_PROMO_SCOPE')
  ALTER TABLE dbo.T_PROMO DROP CONSTRAINT CK_T_PROMO_SCOPE;
IF COL_LENGTH(N'dbo.T_PROMO', N'MAX_PER_USER') IS NOT NULL ALTER TABLE dbo.T_PROMO DROP COLUMN MAX_PER_USER;
IF COL_LENGTH(N'dbo.T_PROMO', N'SCOPE_TYPE') IS NOT NULL ALTER TABLE dbo.T_PROMO DROP CONSTRAINT DF_T_PROMO_SCOPE;
IF COL_LENGTH(N'dbo.T_PROMO', N'SCOPE_TYPE') IS NOT NULL ALTER TABLE dbo.T_PROMO DROP COLUMN SCOPE_TYPE;
IF COL_LENGTH(N'dbo.T_PROMO', N'ORGANIZER_CODE') IS NOT NULL ALTER TABLE dbo.T_PROMO DROP CONSTRAINT FK_T_PROMO_ORG;
IF COL_LENGTH(N'dbo.T_PROMO', N'ORGANIZER_CODE') IS NOT NULL ALTER TABLE dbo.T_PROMO DROP COLUMN ORGANIZER_CODE;

COMMIT TRAN;
