-- Migration 12: TICKETING tables + columns.
--
--   Verified against live ticket-db: T_ORDER_ITEM, T_STOCK_RESERVATION,
--   T_SCAN_LOG and T_EVENT_OFFICER do not exist (all created here).
--   T_ORDER, T_TICKET and T_REFUND exist (migrate5) and are extended;
--   T_EVENT/T_TICKET_TYPE exist (migrate5/6/9) and are reused as-is.
--     T_ORDER_ITEM: order line price snapshot (unit price at purchase).
--     T_STOCK_RESERVATION: temporary quota hold (default 15 minutes).
--     T_SCAN_LOG: every scan attempt with result (audit trail).
--     T_EVENT_OFFICER: officer-to-event assignment (scan scope).
--     T_ORDER += RESERVED_UNTIL, STATUS gains EXPIRED.
--     T_TICKET += QR_TOKEN (signed, non-sequential).
--     T_REFUND += TICKET_CODE (nullable, future per-ticket), REJECT_NOTE,
--                 PAYOUT_STATUS (NONE/PENDING_FINANCE/PAID; FINANCE owns payout).
--   Patterns copied from migrate5/6/9 (DF_/FK_/UQ_/CK_/IX_, GETDATE(),
--   NO_ACTION master refs, CASCADE dependents, DECIMAL(18,2)).
--
-- Idempotent (safe to re-run). Rollback: scripts/migrate12_ticketing_rollback.sql
-- Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/migrate12_ticketing.sql
-- Or: task migrate
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
GO

BEGIN TRAN;

-- 1. T_ORDER_ITEM (harga snapshot per baris order) ------------------------------------
IF OBJECT_ID(N'dbo.T_ORDER_ITEM', N'U') IS NULL
CREATE TABLE dbo.T_ORDER_ITEM (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  ORDER_CODE NVARCHAR(20) NOT NULL,
  TICKET_TYPE_CODE NVARCHAR(20) NOT NULL,
  TYPE_NAME NVARCHAR(100) NOT NULL,
  UNIT_PRICE DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_OI_PRICE DEFAULT 0,
  QTY INT NOT NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_OI_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_OI_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_ORDER_ITEM PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_OI_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_OI_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES dbo.T_ORDER (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_T_OI_TYPE FOREIGN KEY (TICKET_TYPE_CODE) REFERENCES dbo.T_TICKET_TYPE (CODE)
);

-- 2. T_STOCK_RESERVATION (tahan kuota sementara sampai dibayar/kedaluwarsa) -------------
IF OBJECT_ID(N'dbo.T_STOCK_RESERVATION', N'U') IS NULL
CREATE TABLE dbo.T_STOCK_RESERVATION (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  ORDER_CODE NVARCHAR(20) NOT NULL,
  TICKET_TYPE_CODE NVARCHAR(20) NOT NULL,
  QTY INT NOT NULL,
  EXPIRES_AT DATETIME NOT NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_SR_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_STOCK_RESERVATION PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_SR_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT UQ_T_SR_ORDER_TYPE UNIQUE NONCLUSTERED (ORDER_CODE, TICKET_TYPE_CODE),
  CONSTRAINT FK_T_SR_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES dbo.T_ORDER (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_T_SR_TYPE FOREIGN KEY (TICKET_TYPE_CODE) REFERENCES dbo.T_TICKET_TYPE (CODE)
);

-- 3. T_EVENT_OFFICER (penugasan petugas per event = scope scan) ------------------------------
IF OBJECT_ID(N'dbo.T_EVENT_OFFICER', N'U') IS NULL
CREATE TABLE dbo.T_EVENT_OFFICER (
  EVENT_CODE NVARCHAR(20) NOT NULL,
  OFFICER_CODE NVARCHAR(20) NOT NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_EO_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_EVENT_OFFICER PRIMARY KEY CLUSTERED (EVENT_CODE, OFFICER_CODE),
  CONSTRAINT FK_T_EO_EVENT FOREIGN KEY (EVENT_CODE) REFERENCES dbo.T_EVENT (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_T_EO_OFFICER FOREIGN KEY (OFFICER_CODE) REFERENCES dbo.CPUSER (CODE) ON DELETE CASCADE
);

-- 4. T_SCAN_LOG (semua percobaan scan + hasilnya) ------------------------------------------------
IF OBJECT_ID(N'dbo.T_SCAN_LOG', N'U') IS NULL
CREATE TABLE dbo.T_SCAN_LOG (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  EVENT_CODE NVARCHAR(20) NOT NULL,
  TICKET_CODE NVARCHAR(20) NULL,
  OFFICER_CODE NVARCHAR(20) NOT NULL,
  RESULT NVARCHAR(20) NOT NULL,
  DETAIL NVARCHAR(500) NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_SL_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_SCAN_LOG PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_SL_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_SL_EVENT FOREIGN KEY (EVENT_CODE) REFERENCES dbo.T_EVENT (CODE),
  CONSTRAINT FK_T_SL_OFFICER FOREIGN KEY (OFFICER_CODE) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT CK_T_SL_RESULT CHECK (RESULT IN (N'VALID', N'USED', N'INVALID', N'WRONG_EVENT',
    N'UNPAID', N'REFUNDED', N'EXPIRED', N'OUTSIDE_SCHEDULE'))
);
GO

-- 5. T_ORDER: hold expiry + EXPIRED status (batch sendiri: ADD lalu referensi) --------
IF COL_LENGTH(N'dbo.T_ORDER', N'RESERVED_UNTIL') IS NULL
  ALTER TABLE dbo.T_ORDER ADD RESERVED_UNTIL DATETIME NULL;
GO
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_ORDER_STATUS')
  ALTER TABLE dbo.T_ORDER DROP CONSTRAINT CK_T_ORDER_STATUS;
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_ORDER_STATUS')
  ALTER TABLE dbo.T_ORDER ADD CONSTRAINT CK_T_ORDER_STATUS
    CHECK (STATUS IN (N'PENDING', N'PAID', N'CANCELLED', N'REFUNDED', N'EXPIRED'));
GO

-- 6. T_TICKET: signed QR token -------------------------------------------------------------------
IF COL_LENGTH(N'dbo.T_TICKET', N'QR_TOKEN') IS NULL
  ALTER TABLE dbo.T_TICKET ADD QR_TOKEN NVARCHAR(512) NULL;
GO

-- 7. T_REFUND: per-ticket ref + reject note + finance payout marker -------------------------
IF COL_LENGTH(N'dbo.T_REFUND', N'TICKET_CODE') IS NULL
  ALTER TABLE dbo.T_REFUND ADD TICKET_CODE NVARCHAR(20) NULL
    CONSTRAINT FK_T_RF_TICKET REFERENCES dbo.T_TICKET (CODE);
IF COL_LENGTH(N'dbo.T_REFUND', N'REJECT_NOTE') IS NULL
  ALTER TABLE dbo.T_REFUND ADD REJECT_NOTE NVARCHAR(500) NULL;
IF COL_LENGTH(N'dbo.T_REFUND', N'PAYOUT_STATUS') IS NULL
  ALTER TABLE dbo.T_REFUND ADD PAYOUT_STATUS NVARCHAR(20) NOT NULL
    CONSTRAINT DF_T_RF_PAYOUT DEFAULT N'NONE';
GO
-- One pending request per order (no double filing; same rule covers tickets
-- because requests are filed per order).
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UQ_T_RF_ORDER_PENDING' AND object_id = OBJECT_ID(N'dbo.T_REFUND'))
  CREATE UNIQUE NONCLUSTERED INDEX UQ_T_RF_ORDER_PENDING ON dbo.T_REFUND (ORDER_CODE) WHERE STATUS = N'PENDING';
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_RF_PAYOUT')
  ALTER TABLE dbo.T_REFUND ADD CONSTRAINT CK_T_RF_PAYOUT
    CHECK (PAYOUT_STATUS IN (N'NONE', N'PENDING_FINANCE', N'PAID'));
GO

-- 8. Index kolom filter ticketing ----------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_ORDER_BUYER' AND object_id = OBJECT_ID(N'dbo.T_ORDER'))
  CREATE NONCLUSTERED INDEX IX_T_ORDER_BUYER ON dbo.T_ORDER (BUYER_CODE, STATUS, ORDER_DATE DESC);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_SR_EXPIRY' AND object_id = OBJECT_ID(N'dbo.T_STOCK_RESERVATION'))
  CREATE NONCLUSTERED INDEX IX_T_SR_EXPIRY ON dbo.T_STOCK_RESERVATION (TICKET_TYPE_CODE, EXPIRES_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_SL_EVENT' AND object_id = OBJECT_ID(N'dbo.T_SCAN_LOG'))
  CREATE NONCLUSTERED INDEX IX_T_SL_EVENT ON dbo.T_SCAN_LOG (EVENT_CODE, CREATED_AT DESC);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_SL_OFFICER' AND object_id = OBJECT_ID(N'dbo.T_SCAN_LOG'))
  CREATE NONCLUSTERED INDEX IX_T_SL_OFFICER ON dbo.T_SCAN_LOG (OFFICER_CODE, CREATED_AT DESC);
GO

COMMIT TRAN;
