-- Rollback for scripts/migrate12_ticketing.sql (TICKETING tables + columns).
-- Drops new T_ tables, removes added columns, restores T_ORDER status check.
-- Data in dropped objects is lost. Idempotent (safe to re-run). Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/migrate12_ticketing_rollback.sql
SET XACT_ABORT ON;
GO

BEGIN TRAN;

DROP TABLE IF EXISTS dbo.T_SCAN_LOG;
DROP TABLE IF EXISTS dbo.T_EVENT_OFFICER;
DROP TABLE IF EXISTS dbo.T_STOCK_RESERVATION;
DROP TABLE IF EXISTS dbo.T_ORDER_ITEM;

IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_RF_PAYOUT')
  ALTER TABLE dbo.T_REFUND DROP CONSTRAINT CK_T_RF_PAYOUT;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UQ_T_RF_ORDER_PENDING' AND object_id = OBJECT_ID(N'dbo.T_REFUND'))
  DROP INDEX UQ_T_RF_ORDER_PENDING ON dbo.T_REFUND;
IF COL_LENGTH(N'dbo.T_REFUND', N'PAYOUT_STATUS') IS NOT NULL
BEGIN
  ALTER TABLE dbo.T_REFUND DROP CONSTRAINT DF_T_RF_PAYOUT;
  ALTER TABLE dbo.T_REFUND DROP COLUMN PAYOUT_STATUS;
END
IF COL_LENGTH(N'dbo.T_REFUND', N'REJECT_NOTE') IS NOT NULL
  ALTER TABLE dbo.T_REFUND DROP COLUMN REJECT_NOTE;
IF COL_LENGTH(N'dbo.T_REFUND', N'TICKET_CODE') IS NOT NULL
  ALTER TABLE dbo.T_REFUND DROP CONSTRAINT FK_T_RF_TICKET;
IF COL_LENGTH(N'dbo.T_REFUND', N'TICKET_CODE') IS NOT NULL
  ALTER TABLE dbo.T_REFUND DROP COLUMN TICKET_CODE;

IF COL_LENGTH(N'dbo.T_TICKET', N'QR_TOKEN') IS NOT NULL
  ALTER TABLE dbo.T_TICKET DROP COLUMN QR_TOKEN;

IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_ORDER_STATUS')
  ALTER TABLE dbo.T_ORDER DROP CONSTRAINT CK_T_ORDER_STATUS;
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_ORDER_STATUS')
  ALTER TABLE dbo.T_ORDER ADD CONSTRAINT CK_T_ORDER_STATUS
    CHECK (STATUS IN (N'PENDING', N'PAID', N'CANCELLED', N'REFUNDED'));
IF COL_LENGTH(N'dbo.T_ORDER', N'RESERVED_UNTIL') IS NOT NULL
  ALTER TABLE dbo.T_ORDER DROP COLUMN RESERVED_UNTIL;

COMMIT TRAN;
