-- Migrasi 2: RBAC + Audit Log + System Log + Notifikasi + sesi admin.
--   CPPERMISSION      master permission (CODE, GROUP)
--   CPROLEPERMISSION  mapping ROLE_CODE -> PERMISSION_CODE
--   CPAUDITLOG        jejak aksi user (siapa, apa, kapan, dari IP mana)
--   CPSYSLOG          log error/sistem aplikasi (pengganti baca file log)
--   CPNOTIFTEMPLATE   template notifikasi (email/push/in-app, dukung {{var}})
--   CPNOTIFLOG        riwayat pengiriman notifikasi
-- Sesi memakai CPREFRESHTOKEN yang sudah ada (read/revoke via API).
--
-- Aman diulang (idempotent). Jalankan:
--   sqlcmd -S localhost,1433 -U <user> -P <pass> -d Go -C -i scripts/migrate2_rbac.sql
-- Atau: task migrate (menjalankan migrate.sql lalu file ini berurutan)
SET XACT_ABORT ON;
BEGIN TRAN;

-- 1. CPPERMISSION ------------------------------------------------------------
IF OBJECT_ID(N'dbo.CPPERMISSION', N'U') IS NULL
CREATE TABLE dbo.CPPERMISSION (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(40) NOT NULL,
  NAME NVARCHAR(100) NOT NULL,
  PERMGROUP NVARCHAR(40) NOT NULL,
  DESCRIPTION NVARCHAR(255) NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_CPPERM_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_CPPERMISSION PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_CPPERM_CODE UNIQUE NONCLUSTERED (CODE)
);

-- 2. CPROLEPERMISSION ----------------------------------------------------------
IF OBJECT_ID(N'dbo.CPROLEPERMISSION', N'U') IS NULL
CREATE TABLE dbo.CPROLEPERMISSION (
  ROLE_CODE NVARCHAR(20) NOT NULL,
  PERMISSION_CODE NVARCHAR(40) NOT NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_CRP_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_CPROLEPERMISSION PRIMARY KEY CLUSTERED (ROLE_CODE, PERMISSION_CODE),
  CONSTRAINT FK_CRP_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES dbo.CPROLE (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_CRP_PERM FOREIGN KEY (PERMISSION_CODE) REFERENCES dbo.CPPERMISSION (CODE) ON DELETE CASCADE
);

-- Bersihkan permission lama per-fitur; RBAC sekarang satu permission per menu.
DELETE FROM dbo.CPROLEPERMISSION
WHERE PERMISSION_CODE IN (
  N'USER_READ', N'USER_CREATE', N'USER_UPDATE', N'USER_DELETE', N'USER_ROLE_ASSIGN',
  N'ROLE_READ', N'ROLE_MANAGE', N'PERMISSION_ASSIGN',
  N'SESSION_READ', N'SESSION_REVOKE', N'SESSION_MANAGE',
  N'AUDIT_READ', N'SECURITY_READ', N'SYSLOG_READ', N'SYSLOG_MANAGE',
  N'NOTIF_READ', N'NOTIF_MANAGE', N'NOTIF_SEND'
);
DELETE FROM dbo.CPPERMISSION
WHERE CODE IN (
  N'USER_READ', N'USER_CREATE', N'USER_UPDATE', N'USER_DELETE', N'USER_ROLE_ASSIGN',
  N'ROLE_READ', N'ROLE_MANAGE', N'PERMISSION_ASSIGN',
  N'SESSION_READ', N'SESSION_REVOKE', N'SESSION_MANAGE',
  N'AUDIT_READ', N'SECURITY_READ', N'SYSLOG_READ', N'SYSLOG_MANAGE',
  N'NOTIF_READ', N'NOTIF_MANAGE', N'NOTIF_SEND'
);

-- Seed permission (CODE, NAME, GROUP, DESCRIPTION) — satu permission per menu.
-- Jika role punya permission ini, menu-nya tampil di sidebar.
DECLARE @perms TABLE (CODE NVARCHAR(40), NAME NVARCHAR(100), PERMGROUP NVARCHAR(40), DESCRIPTION NVARCHAR(255));
INSERT INTO @perms VALUES
  (N'MENU_DASHBOARD',    N'Akses menu Dashboard',       N'MENU', N'Seluruh fungsi dashboard untuk role ini'),
  (N'MENU_USERS',        N'Akses menu User Account',   N'MENU', N'Seluruh fungsi pengelolaan pengguna'),
  (N'MENU_ROLES',        N'Akses menu Role & Permission', N'MENU', N'Seluruh fungsi pengelolaan role'),
  (N'MENU_SESSIONS',     N'Akses menu Sesi',           N'MENU', N'Seluruh fungsi pengelolaan sesi'),
  (N'MENU_AUDIT',        N'Akses menu Audit Log',      N'MENU', N'Seluruh fungsi audit log'),
  (N'MENU_SECURITY',     N'Akses menu Security Center', N'MENU', N'Seluruh fungsi security center'),
  (N'MENU_SYSLOG',       N'Akses menu System Log',     N'MENU', N'Seluruh fungsi system log'),
  (N'MENU_NOTIFICATIONS',N'Akses menu Notifikasi',     N'MENU', N'Seluruh fungsi notifikasi');

INSERT INTO dbo.CPPERMISSION (CODE, NAME, PERMGROUP, DESCRIPTION)
SELECT CODE, NAME, PERMGROUP, DESCRIPTION FROM @perms p
WHERE NOT EXISTS (SELECT 1 FROM dbo.CPPERMISSION x WHERE x.CODE = p.CODE);

UPDATE p
SET p.NAME = v.NAME, p.PERMGROUP = v.PERMGROUP, p.DESCRIPTION = v.DESCRIPTION
FROM dbo.CPPERMISSION p
INNER JOIN @perms v ON v.CODE = p.CODE;

-- ADMIN = semua permission (tampil semua menu)
INSERT INTO dbo.CPROLEPERMISSION (ROLE_CODE, PERMISSION_CODE)
SELECT N'ADMIN', CODE FROM dbo.CPPERMISSION
WHERE NOT EXISTS (
  SELECT 1 FROM dbo.CPROLEPERMISSION x WHERE x.ROLE_CODE = N'ADMIN' AND x.PERMISSION_CODE = CPPERMISSION.CODE
);

-- USER = hanya dashboard (tampil user/dashboard saja)
INSERT INTO dbo.CPROLEPERMISSION (ROLE_CODE, PERMISSION_CODE)
SELECT N'USER', CODE FROM (VALUES (N'MENU_DASHBOARD')) v(CODE)
WHERE NOT EXISTS (
  SELECT 1 FROM dbo.CPROLEPERMISSION x WHERE x.ROLE_CODE = N'USER' AND x.PERMISSION_CODE = v.CODE
);

-- 3. CPAUDITLOG ------------------------------------------------------------------
IF OBJECT_ID(N'dbo.CPAUDITLOG', N'U') IS NULL
CREATE TABLE dbo.CPAUDITLOG (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  ACTOR_CODE NVARCHAR(20) NULL,          -- CODE CPUSER pelaku (NULL = sistem/login-gagal)
  ACTION NVARCHAR(60) NOT NULL,          -- LOGIN, REGISTER, UPDATE_USER, ...
  ENTITY NVARCHAR(40) NOT NULL,          -- USER, ROLE, SESSION, NOTIFICATION, ...
  ENTITY_CODE NVARCHAR(60) NULL,         -- kode objek yang dikenai aksi
  DETAIL NVARCHAR(1000) NULL,
  IP_ADDRESS NVARCHAR(60) NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_CPAUDIT_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_CPAUDITLOG PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_CPAUDIT_CODE UNIQUE NONCLUSTERED (CODE)
);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CPAUDIT_ACTION' AND object_id = OBJECT_ID(N'dbo.CPAUDITLOG'))
  CREATE NONCLUSTERED INDEX IX_CPAUDIT_ACTION ON dbo.CPAUDITLOG (ACTION, CREATED_AT DESC);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CPAUDIT_ACTOR' AND object_id = OBJECT_ID(N'dbo.CPAUDITLOG'))
  CREATE NONCLUSTERED INDEX IX_CPAUDIT_ACTOR ON dbo.CPAUDITLOG (ACTOR_CODE, CREATED_AT DESC);

-- 4. CPSYSLOG ---------------------------------------------------------------------
IF OBJECT_ID(N'dbo.CPSYSLOG', N'U') IS NULL
CREATE TABLE dbo.CPSYSLOG (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  LEVEL NVARCHAR(10) NOT NULL,           -- ERROR, WARN, INFO
  SOURCE NVARCHAR(100) NOT NULL,         -- handler/service asal error
  MESSAGE NVARCHAR(1000) NOT NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_CPSYS_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_CPSYSLOG PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_CPSYS_CODE UNIQUE NONCLUSTERED (CODE)
);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CPSYS_LEVEL' AND object_id = OBJECT_ID(N'dbo.CPSYSLOG'))
  CREATE NONCLUSTERED INDEX IX_CPSYS_LEVEL ON dbo.CPSYSLOG (LEVEL, CREATED_AT DESC);

-- 5. CPNOTIFTEMPLATE ----------------------------------------------------------------
IF OBJECT_ID(N'dbo.CPNOTIFTEMPLATE', N'U') IS NULL
CREATE TABLE dbo.CPNOTIFTEMPLATE (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  NAME NVARCHAR(100) NOT NULL,
  CHANNEL NVARCHAR(10) NOT NULL,         -- EMAIL, PUSH, INAPP
  SUBJECT NVARCHAR(200) NULL,
  BODY NVARCHAR(4000) NOT NULL,          -- dukung variabel {{nama}}, {{kode}}, ...
  IS_ACTIVE BIT NOT NULL CONSTRAINT DF_CPNT_ACTIVE DEFAULT 1,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_CPNT_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_CPNT_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_CPNOTIFTEMPLATE PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_CPNT_CODE UNIQUE NONCLUSTERED (CODE)
);

-- Seed 3 template bawaan
IF NOT EXISTS (SELECT 1 FROM dbo.CPNOTIFTEMPLATE WHERE CODE = N'NTPL-WELCOME')
  INSERT INTO dbo.CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
  VALUES (N'NTPL-WELCOME', N'Selamat datang', N'EMAIL', N'Selamat datang di Go Core, {{nama}}!',
    N'Halo {{nama}},\n\nAkun Anda ({{kode}}) berhasil dibuat dengan role {{role}}.\nSilakan login untuk mulai menggunakan aplikasi.\n\nSalam,\nTim Go Core');
IF NOT EXISTS (SELECT 1 FROM dbo.CPNOTIFTEMPLATE WHERE CODE = N'NTPL-RESET')
  INSERT INTO dbo.CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
  VALUES (N'NTPL-RESET', N'Reset password', N'EMAIL', N'Permintaan reset password akun {{kode}}',
    N'Halo {{nama}},\n\nKami menerima permintaan reset password untuk akun {{kode}}.\nAbaikan pesan ini bila Anda tidak memintanya.\n\nSalam,\nTim Go Core');
IF NOT EXISTS (SELECT 1 FROM dbo.CPNOTIFTEMPLATE WHERE CODE = N'NTPL-ALERT')
  INSERT INTO dbo.CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
  VALUES (N'NTPL-ALERT', N'Peringatan keamanan', N'INAPP', N'Peringatan keamanan',
    N'Aktivitas penting terdeteksi pada akun {{kode}}: {{detail}}');

-- 6. CPNOTIFLOG -----------------------------------------------------------------------
IF OBJECT_ID(N'dbo.CPNOTIFLOG', N'U') IS NULL
CREATE TABLE dbo.CPNOTIFLOG (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  TEMPLATE_CODE NVARCHAR(20) NULL,       -- NULL = kirim manual tanpa template
  CHANNEL NVARCHAR(10) NOT NULL,
  RECIPIENT NVARCHAR(255) NOT NULL,
  SUBJECT NVARCHAR(200) NULL,
  BODY NVARCHAR(4000) NOT NULL,
  STATUS NVARCHAR(10) NOT NULL,          -- SENT, FAILED
  ERROR NVARCHAR(500) NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_CPNL_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_CPNOTIFLOG PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_CPNL_CODE UNIQUE NONCLUSTERED (CODE)
);

COMMIT TRAN;
