-- Migration 6: DISCOVERY tables (prefix T_) + discovery columns on T_*.
--
--   Verified against live ticket-db (only CP* + migrate5 T_* exist):
--   - T_EVENT lacks category/address/coords/poster; STATUS has no ENDED.
--   - T_TICKET_TYPE lacks sale period.
--   - T_PROMO lacks description/max-discount/min-purchase/coverage.
--   - News + ad campaigns have no table at all (T_AD_DAILY is per-event
--     organizer stats - different function, so it is reused, not replaced).
--
--   New: T_EVENT_CATEGORY, T_NEWS_CATEGORY, T_NEWS, T_NEWS_VIEW,
--        T_AD_CAMPAIGN, T_AD_EVENT.
--   Alter: T_EVENT (+6 cols, STATUS gains ENDED), T_TICKET_TYPE (+2 cols),
--          T_PROMO (+4 cols). CP_* untouched.
--   Patterns copied from migrate5 (DF_/FK_/UQ_/CK_/IX_ naming, GETDATE(),
--   NO_ACTION master refs, CASCADE dependents, DECIMAL(18,2) money).
--
-- Idempotent (safe to re-run). Rollback: scripts/migrate6_discovery_rollback.sql
-- Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/migrate6_discovery.sql
-- Or: task migrate
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
BEGIN TRAN;

-- 1. T_EVENT_CATEGORY (master kategori event, extendable) -----------------------
IF OBJECT_ID(N'dbo.T_EVENT_CATEGORY', N'U') IS NULL
CREATE TABLE dbo.T_EVENT_CATEGORY (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  NAME NVARCHAR(100) NOT NULL,
  SORT_ORDER INT NOT NULL CONSTRAINT DF_T_ECAT_SORT DEFAULT 99,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ECAT_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ECAT_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_EVENT_CATEGORY PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_ECAT_CODE UNIQUE NONCLUSTERED (CODE)
);

-- 2. T_NEWS_CATEGORY (master kategori berita) ------------------------------------
IF OBJECT_ID(N'dbo.T_NEWS_CATEGORY', N'U') IS NULL
CREATE TABLE dbo.T_NEWS_CATEGORY (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  NAME NVARCHAR(100) NOT NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_NCAT_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_NCAT_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_NEWS_CATEGORY PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_NCAT_CODE UNIQUE NONCLUSTERED (CODE)
);

-- 3. T_NEWS (berita; relasi opsional ke kategori event + event terkait) -----------
IF OBJECT_ID(N'dbo.T_NEWS', N'U') IS NULL
CREATE TABLE dbo.T_NEWS (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  TITLE NVARCHAR(200) NOT NULL,
  SLUG NVARCHAR(200) NOT NULL,
  SUMMARY NVARCHAR(500) NULL,
  BODY NVARCHAR(MAX) NOT NULL,
  IMAGE_URL NVARCHAR(500) NULL,
  NEWS_CATEGORY_CODE NVARCHAR(20) NOT NULL,
  EVENT_CATEGORY_CODE NVARCHAR(20) NULL,
  EVENT_CODE NVARCHAR(20) NULL,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_NEWS_STATUS DEFAULT N'DRAFT',
  PUBLISHED_AT DATETIME NULL,
  VIEW_COUNT INT NOT NULL CONSTRAINT DF_T_NEWS_VIEWS DEFAULT 0,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_NEWS_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_NEWS_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_NEWS PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_NEWS_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT UQ_T_NEWS_SLUG UNIQUE NONCLUSTERED (SLUG),
  CONSTRAINT FK_T_NEWS_CAT FOREIGN KEY (NEWS_CATEGORY_CODE) REFERENCES dbo.T_NEWS_CATEGORY (CODE),
  CONSTRAINT FK_T_NEWS_ECAT FOREIGN KEY (EVENT_CATEGORY_CODE) REFERENCES dbo.T_EVENT_CATEGORY (CODE),
  CONSTRAINT FK_T_NEWS_EVENT FOREIGN KEY (EVENT_CODE) REFERENCES dbo.T_EVENT (CODE),
  CONSTRAINT CK_T_NEWS_STATUS CHECK (STATUS IN (N'DRAFT', N'PUBLISHED'))
);

-- 4. T_NEWS_VIEW (dedup hitungan baca: 1 viewer per 30 menit) -----------------------
IF OBJECT_ID(N'dbo.T_NEWS_VIEW', N'U') IS NULL
CREATE TABLE dbo.T_NEWS_VIEW (
  ID INT IDENTITY(1,1) NOT NULL,
  NEWS_CODE NVARCHAR(20) NOT NULL,
  VIEWER_HASH NVARCHAR(64) NOT NULL,
  VIEWED_AT DATETIME NOT NULL CONSTRAINT DF_T_NV_AT DEFAULT GETDATE(),
  CONSTRAINT PK_T_NEWS_VIEW PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_T_NV_NEWS FOREIGN KEY (NEWS_CODE) REFERENCES dbo.T_NEWS (CODE) ON DELETE CASCADE
);

-- 5. T_AD_CAMPAIGN (iklan kampanye tayang di discovery) ------------------------------
IF OBJECT_ID(N'dbo.T_AD_CAMPAIGN', N'U') IS NULL
CREATE TABLE dbo.T_AD_CAMPAIGN (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  TITLE NVARCHAR(200) NOT NULL,
  IMAGE_URL NVARCHAR(500) NULL,
  TARGET_URL NVARCHAR(500) NULL,
  POSITION NVARCHAR(20) NOT NULL CONSTRAINT DF_T_ADC_POS DEFAULT N'HOME_BANNER',
  START_AT DATETIME NOT NULL,
  END_AT DATETIME NOT NULL,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_ADC_STATUS DEFAULT N'ACTIVE',
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ADC_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ADC_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_AD_CAMPAIGN PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_AD_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT CK_T_AD_POS CHECK (POSITION IN (N'HOME_BANNER', N'EVENT_LIST', N'SIDEBAR')),
  CONSTRAINT CK_T_AD_STATUS CHECK (STATUS IN (N'ACTIVE', N'PAUSED', N'ENDED'))
);

-- 6. T_AD_EVENT (log impression/klik; dedup 1 jam per IP+campaign+kind) -----------------
IF OBJECT_ID(N'dbo.T_AD_EVENT', N'U') IS NULL
CREATE TABLE dbo.T_AD_EVENT (
  ID INT IDENTITY(1,1) NOT NULL,
  CAMPAIGN_CODE NVARCHAR(20) NOT NULL,
  KIND NVARCHAR(10) NOT NULL,
  IP_HASH NVARCHAR(64) NOT NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_AE_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_AD_EVENT PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_T_AE_CAMP FOREIGN KEY (CAMPAIGN_CODE) REFERENCES dbo.T_AD_CAMPAIGN (CODE) ON DELETE CASCADE,
  CONSTRAINT CK_T_AE_KIND CHECK (KIND IN (N'IMPRESSION', N'CLICK'))
);

-- 7. T_EVENT: discovery columns ---------------------------------------------------------
IF COL_LENGTH(N'dbo.T_EVENT', N'EVENT_CATEGORY_CODE') IS NULL
  ALTER TABLE dbo.T_EVENT ADD EVENT_CATEGORY_CODE NVARCHAR(20) NULL
    CONSTRAINT FK_T_EVENT_CAT REFERENCES dbo.T_EVENT_CATEGORY (CODE);
IF COL_LENGTH(N'dbo.T_EVENT', N'ADDRESS') IS NULL
  ALTER TABLE dbo.T_EVENT ADD ADDRESS NVARCHAR(300) NULL;
IF COL_LENGTH(N'dbo.T_EVENT', N'LATITUDE') IS NULL
  ALTER TABLE dbo.T_EVENT ADD LATITUDE DECIMAL(10,7) NULL;
IF COL_LENGTH(N'dbo.T_EVENT', N'LONGITUDE') IS NULL
  ALTER TABLE dbo.T_EVENT ADD LONGITUDE DECIMAL(10,7) NULL;
IF COL_LENGTH(N'dbo.T_EVENT', N'POSTER_URL') IS NULL
  ALTER TABLE dbo.T_EVENT ADD POSTER_URL NVARCHAR(500) NULL;
-- STATUS gains ENDED (spec) alongside existing COMPLETED.
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_EVENT_STATUS')
  ALTER TABLE dbo.T_EVENT DROP CONSTRAINT CK_T_EVENT_STATUS;
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_EVENT_STATUS')
  ALTER TABLE dbo.T_EVENT ADD CONSTRAINT CK_T_EVENT_STATUS
    CHECK (STATUS IN (N'DRAFT', N'PUBLISHED', N'COMPLETED', N'ENDED', N'CANCELLED'));

-- 8. T_TICKET_TYPE: sale period --------------------------------------------------------------
IF COL_LENGTH(N'dbo.T_TICKET_TYPE', N'SALE_START_AT') IS NULL
  ALTER TABLE dbo.T_TICKET_TYPE ADD SALE_START_AT DATETIME NULL;
IF COL_LENGTH(N'dbo.T_TICKET_TYPE', N'SALE_END_AT') IS NULL
  ALTER TABLE dbo.T_TICKET_TYPE ADD SALE_END_AT DATETIME NULL;

-- 9. T_PROMO: discovery columns -----------------------------------------------------------------
IF COL_LENGTH(N'dbo.T_PROMO', N'DESCRIPTION') IS NULL
  ALTER TABLE dbo.T_PROMO ADD DESCRIPTION NVARCHAR(500) NULL;
IF COL_LENGTH(N'dbo.T_PROMO', N'MAX_DISCOUNT_AMOUNT') IS NULL
  ALTER TABLE dbo.T_PROMO ADD MAX_DISCOUNT_AMOUNT DECIMAL(18,2) NOT NULL
    CONSTRAINT DF_T_PROMO_MAXDISC DEFAULT 0;
IF COL_LENGTH(N'dbo.T_PROMO', N'MIN_PURCHASE') IS NULL
  ALTER TABLE dbo.T_PROMO ADD MIN_PURCHASE DECIMAL(18,2) NOT NULL
    CONSTRAINT DF_T_PROMO_MINPUR DEFAULT 0;
IF COL_LENGTH(N'dbo.T_PROMO', N'COVERAGE_CATEGORY_CODE') IS NULL
  ALTER TABLE dbo.T_PROMO ADD COVERAGE_CATEGORY_CODE NVARCHAR(20) NULL
    CONSTRAINT FK_T_PROMO_COVCAT REFERENCES dbo.T_EVENT_CATEGORY (CODE);

-- 10. Index kolom yang sering difilter ------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_EVENT_PUBLIC' AND object_id = OBJECT_ID(N'dbo.T_EVENT'))
  CREATE NONCLUSTERED INDEX IX_T_EVENT_PUBLIC ON dbo.T_EVENT (STATUS, START_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_EVENT_CITY' AND object_id = OBJECT_ID(N'dbo.T_EVENT'))
  CREATE NONCLUSTERED INDEX IX_T_EVENT_CITY ON dbo.T_EVENT (CITY_CODE, STATUS, START_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_EVENT_CAT' AND object_id = OBJECT_ID(N'dbo.T_EVENT'))
  CREATE NONCLUSTERED INDEX IX_T_EVENT_CAT ON dbo.T_EVENT (EVENT_CATEGORY_CODE, STATUS, START_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_NEWS_PUB' AND object_id = OBJECT_ID(N'dbo.T_NEWS'))
  CREATE NONCLUSTERED INDEX IX_T_NEWS_PUB ON dbo.T_NEWS (STATUS, PUBLISHED_AT DESC);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_NEWS_CAT' AND object_id = OBJECT_ID(N'dbo.T_NEWS'))
  CREATE NONCLUSTERED INDEX IX_T_NEWS_CAT ON dbo.T_NEWS (NEWS_CATEGORY_CODE, STATUS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_NV_DEDUP' AND object_id = OBJECT_ID(N'dbo.T_NEWS_VIEW'))
  CREATE NONCLUSTERED INDEX IX_T_NV_DEDUP ON dbo.T_NEWS_VIEW (NEWS_CODE, VIEWER_HASH, VIEWED_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_AD_LIVE' AND object_id = OBJECT_ID(N'dbo.T_AD_CAMPAIGN'))
  CREATE NONCLUSTERED INDEX IX_T_AD_LIVE ON dbo.T_AD_CAMPAIGN (STATUS, START_AT, END_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_AE_DEDUP' AND object_id = OBJECT_ID(N'dbo.T_AD_EVENT'))
  CREATE NONCLUSTERED INDEX IX_T_AE_DEDUP ON dbo.T_AD_EVENT (CAMPAIGN_CODE, KIND, IP_HASH, CREATED_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_TT_EVENT' AND object_id = OBJECT_ID(N'dbo.T_TICKET_TYPE'))
  CREATE NONCLUSTERED INDEX IX_T_TT_EVENT ON dbo.T_TICKET_TYPE (EVENT_CODE);

COMMIT TRAN;
