-- Migration 5: dashboard tables (prefix T_) + DASHBOARD module/menus.
--
--   Business tables (all NEW - live DB has zero of these; verified against
--   INFORMATION_SCHEMA on ticket-db: only 10 CP* tables exist):
--     T_CITY, T_EVENT, T_TICKET_TYPE, T_PROMO, T_ORDER, T_TICKET, T_REFUND,
--     T_AD_DAILY, T_PAYOUT, T_PRODUCT, T_MERCH_ORDER, T_COMPLAINT, T_REVIEW,
--     T_ORGANIZER_BALANCE, T_SELLER_BALANCE
--
--   Patterns copied exactly from CP* tables:
--     ID INT IDENTITY PK + public CODE NVARCHAR(20) UNIQUE, relations via CODE,
--     FK named FK_<child>_<ref>, NO_ACTION for master refs (like FK_CPUSER_ROLE),
--     CASCADE for dependents (like FK_CPRT_USER), DF_<table>_<col> GETDATE()
--     defaults, CHECK for status domains (like CK_CPMENU_KIND).
--   Differences from CP* (deliberate, reported): money DECIMAL(18,2) (no money
--   column exists yet), no created_by/updated_by or soft-delete (CP* has none).
--
--   Module/menus (per user order 2026-09-30): registered with ZERO grants to
--   ANY role (not even ADMIN). Sidebar stays empty until an admin assigns via
--   the Role & Permission matrix. This deviates from the "don't touch CP_"
--   rule on explicit user instruction.
--
-- Idempotent (safe to re-run). Rollback: scripts/migrate5_dashboard_rollback.sql
-- Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/migrate5_dashboard.sql
-- Or: task migrate
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
BEGIN TRAN;

-- 1. T_CITY (master kota) ------------------------------------------------------
IF OBJECT_ID(N'dbo.T_CITY', N'U') IS NULL
CREATE TABLE dbo.T_CITY (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  NAME NVARCHAR(100) NOT NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_CITY_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_CITY_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_CITY PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_CITY_CODE UNIQUE NONCLUSTERED (CODE)
);

-- 2. T_EVENT (event milik organizer) -------------------------------------------
IF OBJECT_ID(N'dbo.T_EVENT', N'U') IS NULL
CREATE TABLE dbo.T_EVENT (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  ORGANIZER_CODE NVARCHAR(20) NOT NULL,
  CITY_CODE NVARCHAR(20) NULL,
  TITLE NVARCHAR(200) NOT NULL,
  DESCRIPTION NVARCHAR(1000) NULL,
  VENUE NVARCHAR(200) NULL,
  START_AT DATETIME NOT NULL,
  END_AT DATETIME NULL,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_EVENT_STATUS DEFAULT N'PUBLISHED',
  PLATFORM_FEE_PERCENT DECIMAL(5,2) NOT NULL CONSTRAINT DF_T_EVENT_FEE DEFAULT 10.00,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_EVENT_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_EVENT_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_EVENT PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_EVENT_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_EVENT_ORGANIZER FOREIGN KEY (ORGANIZER_CODE) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT FK_T_EVENT_CITY FOREIGN KEY (CITY_CODE) REFERENCES dbo.T_CITY (CODE),
  CONSTRAINT CK_T_EVENT_STATUS CHECK (STATUS IN (N'DRAFT', N'PUBLISHED', N'COMPLETED', N'CANCELLED'))
);

-- 3. T_TICKET_TYPE (tipe tiket + harga + kuota per event) -----------------------
IF OBJECT_ID(N'dbo.T_TICKET_TYPE', N'U') IS NULL
CREATE TABLE dbo.T_TICKET_TYPE (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  EVENT_CODE NVARCHAR(20) NOT NULL,
  NAME NVARCHAR(100) NOT NULL,
  PRICE DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_TT_PRICE DEFAULT 0,
  QUOTA INT NOT NULL CONSTRAINT DF_T_TT_QUOTA DEFAULT 0,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_TT_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_TT_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_TICKET_TYPE PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_TICKET_TYPE_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_TT_EVENT FOREIGN KEY (EVENT_CODE) REFERENCES dbo.T_EVENT (CODE) ON DELETE CASCADE
);

-- 4. T_PROMO (kode promo, per event atau global bila EVENT_CODE NULL) -----------
IF OBJECT_ID(N'dbo.T_PROMO', N'U') IS NULL
CREATE TABLE dbo.T_PROMO (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  EVENT_CODE NVARCHAR(20) NULL,
  PROMO_CODE NVARCHAR(40) NOT NULL,
  DISCOUNT_PERCENT DECIMAL(5,2) NOT NULL CONSTRAINT DF_T_PROMO_PCT DEFAULT 0,
  DISCOUNT_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_PROMO_AMT DEFAULT 0,
  MAX_USES INT NULL,
  USED_COUNT INT NOT NULL CONSTRAINT DF_T_PROMO_USED DEFAULT 0,
  VALID_FROM DATETIME NOT NULL,
  VALID_TO DATETIME NOT NULL,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_PROMO_STATUS DEFAULT N'ACTIVE',
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_PROMO_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_PROMO_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_PROMO PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_PROMO_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT UQ_T_PROMO_PCODE UNIQUE NONCLUSTERED (PROMO_CODE),
  CONSTRAINT FK_T_PROMO_EVENT FOREIGN KEY (EVENT_CODE) REFERENCES dbo.T_EVENT (CODE) ON DELETE CASCADE,
  CONSTRAINT CK_T_PROMO_STATUS CHECK (STATUS IN (N'ACTIVE', N'EXPIRED', N'DISABLED'))
);

-- 5. T_ORDER (order tiket) ------------------------------------------------------
IF OBJECT_ID(N'dbo.T_ORDER', N'U') IS NULL
CREATE TABLE dbo.T_ORDER (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  EVENT_CODE NVARCHAR(20) NOT NULL,
  BUYER_CODE NVARCHAR(20) NOT NULL,
  TICKET_TYPE_CODE NVARCHAR(20) NOT NULL,
  QTY INT NOT NULL,
  GROSS_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_ORDER_GROSS DEFAULT 0,
  DISCOUNT_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_ORDER_DISC DEFAULT 0,
  PLATFORM_FEE DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_ORDER_FEE DEFAULT 0,
  NET_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_ORDER_NET DEFAULT 0,
  PROMO_CODE NVARCHAR(40) NULL,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_ORDER_STATUS DEFAULT N'PAID',
  ORDER_DATE DATETIME NOT NULL CONSTRAINT DF_T_ORDER_DATE DEFAULT GETDATE(),
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ORDER_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ORDER_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_ORDER PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_ORDER_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_ORDER_EVENT FOREIGN KEY (EVENT_CODE) REFERENCES dbo.T_EVENT (CODE),
  CONSTRAINT FK_T_ORDER_BUYER FOREIGN KEY (BUYER_CODE) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT FK_T_ORDER_TTYPE FOREIGN KEY (TICKET_TYPE_CODE) REFERENCES dbo.T_TICKET_TYPE (CODE),
  CONSTRAINT CK_T_ORDER_STATUS CHECK (STATUS IN (N'PENDING', N'PAID', N'CANCELLED', N'REFUNDED'))
);

-- 6. T_TICKET (tiket individual + QR + check-in) --------------------------------
IF OBJECT_ID(N'dbo.T_TICKET', N'U') IS NULL
CREATE TABLE dbo.T_TICKET (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  ORDER_CODE NVARCHAR(20) NOT NULL,
  QR_CODE NVARCHAR(64) NOT NULL,
  HOLDER_NAME NVARCHAR(100) NULL,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_TICKET_STATUS DEFAULT N'ACTIVE',
  CHECKED_IN_AT DATETIME NULL,
  CHECKED_IN_BY NVARCHAR(20) NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_TICKET_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_TICKET_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_TICKET PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_TICKET_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT UQ_T_TICKET_QR UNIQUE NONCLUSTERED (QR_CODE),
  CONSTRAINT FK_T_TICKET_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES dbo.T_ORDER (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_T_TICKET_OFFICER FOREIGN KEY (CHECKED_IN_BY) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT CK_T_TICKET_STATUS CHECK (STATUS IN (N'ACTIVE', N'USED', N'REFUNDED'))
);

-- 7. T_REFUND (pengajuan refund + keputusan) -------------------------------------
IF OBJECT_ID(N'dbo.T_REFUND', N'U') IS NULL
CREATE TABLE dbo.T_REFUND (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  ORDER_CODE NVARCHAR(20) NOT NULL,
  AMOUNT DECIMAL(18,2) NOT NULL,
  REASON NVARCHAR(500) NULL,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_REFUND_STATUS DEFAULT N'PENDING',
  REQUESTED_BY NVARCHAR(20) NOT NULL,
  DECIDED_BY NVARCHAR(20) NULL,
  DECIDED_AT DATETIME NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_REFUND_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_REFUND_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_REFUND PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_REFUND_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_REFUND_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES dbo.T_ORDER (CODE),
  CONSTRAINT FK_T_REFUND_REQUESTER FOREIGN KEY (REQUESTED_BY) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT FK_T_REFUND_DECIDER FOREIGN KEY (DECIDED_BY) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT CK_T_REFUND_STATUS CHECK (STATUS IN (N'PENDING', N'APPROVED', N'REJECTED'))
);

-- 8. T_AD_DAILY (statistik iklan harian per event) --------------------------------
IF OBJECT_ID(N'dbo.T_AD_DAILY', N'U') IS NULL
CREATE TABLE dbo.T_AD_DAILY (
  ID INT IDENTITY(1,1) NOT NULL,
  EVENT_CODE NVARCHAR(20) NOT NULL,
  STAT_DATE DATE NOT NULL,
  IMPRESSIONS INT NOT NULL CONSTRAINT DF_T_AD_IMP DEFAULT 0,
  CLICKS INT NOT NULL CONSTRAINT DF_T_AD_CLK DEFAULT 0,
  COST DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_AD_COST DEFAULT 0,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_AD_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_AD_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_AD_DAILY PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_AD_EVENT_DATE UNIQUE NONCLUSTERED (EVENT_CODE, STAT_DATE),
  CONSTRAINT FK_T_AD_EVENT FOREIGN KEY (EVENT_CODE) REFERENCES dbo.T_EVENT (CODE) ON DELETE CASCADE
);

-- 9. T_PAYOUT (pengajuan/riwayat pencairan, owner = baris CPUSER) -----------------
IF OBJECT_ID(N'dbo.T_PAYOUT', N'U') IS NULL
CREATE TABLE dbo.T_PAYOUT (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  OWNER_CODE NVARCHAR(20) NOT NULL,
  AMOUNT DECIMAL(18,2) NOT NULL,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_PAYOUT_STATUS DEFAULT N'READY',
  REQUESTED_AT DATETIME NULL,
  PAID_AT DATETIME NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_PAYOUT_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_PAYOUT_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_PAYOUT PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_PAYOUT_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_PAYOUT_OWNER FOREIGN KEY (OWNER_CODE) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT CK_T_PAYOUT_STATUS CHECK (STATUS IN (N'READY', N'REQUESTED', N'PAID'))
);

-- 10. T_PRODUCT (produk seller) ----------------------------------------------------
IF OBJECT_ID(N'dbo.T_PRODUCT', N'U') IS NULL
CREATE TABLE dbo.T_PRODUCT (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  SELLER_CODE NVARCHAR(20) NOT NULL,
  CATEGORY NVARCHAR(100) NOT NULL,
  NAME NVARCHAR(200) NOT NULL,
  PRICE DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_PROD_PRICE DEFAULT 0,
  STOCK INT NOT NULL CONSTRAINT DF_T_PROD_STOCK DEFAULT 0,
  LOW_STOCK_THRESHOLD INT NOT NULL CONSTRAINT DF_T_PROD_THRESH DEFAULT 5,
  RATING DECIMAL(3,2) NOT NULL CONSTRAINT DF_T_PROD_RATING DEFAULT 0,
  REVIEW_COUNT INT NOT NULL CONSTRAINT DF_T_PROD_RCNT DEFAULT 0,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_PROD_STATUS DEFAULT N'ACTIVE',
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_PROD_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_PROD_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_PRODUCT PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_PRODUCT_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_PROD_SELLER FOREIGN KEY (SELLER_CODE) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT CK_T_PROD_STATUS CHECK (STATUS IN (N'ACTIVE', N'INACTIVE', N'REJECTED'))
);

-- 11. T_MERCH_ORDER (pesanan merchandise) -------------------------------------------
IF OBJECT_ID(N'dbo.T_MERCH_ORDER', N'U') IS NULL
CREATE TABLE dbo.T_MERCH_ORDER (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  PRODUCT_CODE NVARCHAR(20) NOT NULL,
  BUYER_CODE NVARCHAR(20) NOT NULL,
  SELLER_CODE NVARCHAR(20) NOT NULL,
  QTY INT NOT NULL,
  TOTAL_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_MO_TOTAL DEFAULT 0,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_MO_STATUS DEFAULT N'NEW',
  ORDER_DATE DATETIME NOT NULL CONSTRAINT DF_T_MO_DATE DEFAULT GETDATE(),
  SHIP_DEADLINE DATETIME NULL,
  SHIPPED_AT DATETIME NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_MO_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_MO_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_MERCH_ORDER PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_MERCH_ORDER_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_MO_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES dbo.T_PRODUCT (CODE),
  CONSTRAINT FK_T_MO_BUYER FOREIGN KEY (BUYER_CODE) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT FK_T_MO_SELLER FOREIGN KEY (SELLER_CODE) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT CK_T_MO_STATUS CHECK (STATUS IN (N'NEW', N'PROCESSING', N'SHIPPED', N'COMPLETED', N'CANCELLED', N'RETURNED'))
);

-- 12. T_COMPLAINT (keluhan atas pesanan merchandise) ----------------------------------
IF OBJECT_ID(N'dbo.T_COMPLAINT', N'U') IS NULL
CREATE TABLE dbo.T_COMPLAINT (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  ORDER_CODE NVARCHAR(20) NOT NULL,
  BUYER_CODE NVARCHAR(20) NOT NULL,
  MESSAGE NVARCHAR(1000) NOT NULL,
  STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_T_CMPL_STATUS DEFAULT N'OPEN',
  RESOLVED_AT DATETIME NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_CMPL_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_CMPL_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_COMPLAINT PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_COMPLAINT_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_CMPL_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES dbo.T_MERCH_ORDER (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_T_CMPL_BUYER FOREIGN KEY (BUYER_CODE) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT CK_T_CMPL_STATUS CHECK (STATUS IN (N'OPEN', N'RESOLVED'))
);

-- 13. T_REVIEW (ulasan rating atas pesanan merchandise) --------------------------------
IF OBJECT_ID(N'dbo.T_REVIEW', N'U') IS NULL
CREATE TABLE dbo.T_REVIEW (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  ORDER_CODE NVARCHAR(20) NOT NULL,
  PRODUCT_CODE NVARCHAR(20) NOT NULL,
  BUYER_CODE NVARCHAR(20) NOT NULL,
  RATING INT NOT NULL,
  COMMENT NVARCHAR(500) NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_REV_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_REV_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_REVIEW PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_REVIEW_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_REV_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES dbo.T_MERCH_ORDER (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_T_REV_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES dbo.T_PRODUCT (CODE),
  CONSTRAINT FK_T_REV_BUYER FOREIGN KEY (BUYER_CODE) REFERENCES dbo.CPUSER (CODE),
  CONSTRAINT CK_T_REV_RATING CHECK (RATING BETWEEN 1 AND 5)
);

-- 14. T_ORGANIZER_BALANCE (saldo organizer, 1 baris per organizer) ----------------------
IF OBJECT_ID(N'dbo.T_ORGANIZER_BALANCE', N'U') IS NULL
CREATE TABLE dbo.T_ORGANIZER_BALANCE (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  ORGANIZER_CODE NVARCHAR(20) NOT NULL,
  ESCROW_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_OB_ESCROW DEFAULT 0,
  AVAILABLE_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_OB_AVAIL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_OB_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_OB_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_ORGANIZER_BALANCE PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_OB_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT UQ_T_OB_OWNER UNIQUE NONCLUSTERED (ORGANIZER_CODE),
  CONSTRAINT FK_T_OB_OWNER FOREIGN KEY (ORGANIZER_CODE) REFERENCES dbo.CPUSER (CODE)
);

-- 15. T_SELLER_BALANCE (saldo seller, 1 baris per seller) ---------------------------------
IF OBJECT_ID(N'dbo.T_SELLER_BALANCE', N'U') IS NULL
CREATE TABLE dbo.T_SELLER_BALANCE (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  SELLER_CODE NVARCHAR(20) NOT NULL,
  ESCROW_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_SB_ESCROW DEFAULT 0,
  AVAILABLE_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_SB_AVAIL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_SB_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_SB_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_SELLER_BALANCE PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_SB_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT UQ_T_SB_OWNER UNIQUE NONCLUSTERED (SELLER_CODE),
  CONSTRAINT FK_T_SB_OWNER FOREIGN KEY (SELLER_CODE) REFERENCES dbo.CPUSER (CODE)
);

-- 16. Index agregasi dashboard -----------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_EVENT_ORG_START' AND object_id = OBJECT_ID(N'dbo.T_EVENT'))
  CREATE NONCLUSTERED INDEX IX_T_EVENT_ORG_START ON dbo.T_EVENT (ORGANIZER_CODE, START_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_ORDER_EVENT_DATE' AND object_id = OBJECT_ID(N'dbo.T_ORDER'))
  CREATE NONCLUSTERED INDEX IX_T_ORDER_EVENT_DATE ON dbo.T_ORDER (EVENT_CODE, ORDER_DATE);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_ORDER_STATUS' AND object_id = OBJECT_ID(N'dbo.T_ORDER'))
  CREATE NONCLUSTERED INDEX IX_T_ORDER_STATUS ON dbo.T_ORDER (STATUS, ORDER_DATE);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_TICKET_ORDER' AND object_id = OBJECT_ID(N'dbo.T_TICKET'))
  CREATE NONCLUSTERED INDEX IX_T_TICKET_ORDER ON dbo.T_TICKET (ORDER_CODE, STATUS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_REFUND_STATUS' AND object_id = OBJECT_ID(N'dbo.T_REFUND'))
  CREATE NONCLUSTERED INDEX IX_T_REFUND_STATUS ON dbo.T_REFUND (STATUS, CREATED_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_MO_SELLER_DATE' AND object_id = OBJECT_ID(N'dbo.T_MERCH_ORDER'))
  CREATE NONCLUSTERED INDEX IX_T_MO_SELLER_DATE ON dbo.T_MERCH_ORDER (SELLER_CODE, ORDER_DATE);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_MO_STATUS' AND object_id = OBJECT_ID(N'dbo.T_MERCH_ORDER'))
  CREATE NONCLUSTERED INDEX IX_T_MO_STATUS ON dbo.T_MERCH_ORDER (SELLER_CODE, STATUS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_PROD_SELLER' AND object_id = OBJECT_ID(N'dbo.T_PRODUCT'))
  CREATE NONCLUSTERED INDEX IX_T_PROD_SELLER ON dbo.T_PRODUCT (SELLER_CODE, STATUS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_CMPL_STATUS' AND object_id = OBJECT_ID(N'dbo.T_COMPLAINT'))
  CREATE NONCLUSTERED INDEX IX_T_CMPL_STATUS ON dbo.T_COMPLAINT (STATUS, CREATED_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_AD_EVENT_DATE' AND object_id = OBJECT_ID(N'dbo.T_AD_DAILY'))
  CREATE NONCLUSTERED INDEX IX_T_AD_EVENT_DATE ON dbo.T_AD_DAILY (EVENT_CODE, STAT_DATE);

-- 17. Modul DASHBOARD + 2 menu (ZERO grant ke role mana pun) --------------------------------
INSERT INTO dbo.CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT N'DASHBOARD', N'Dashboard', 2
WHERE NOT EXISTS (SELECT 1 FROM dbo.CPMODULE WHERE CODE = N'DASHBOARD');

IF COL_LENGTH(N'dbo.CPMENU', N'MCONTROL') IS NULL
  EXEC(N'INSERT INTO dbo.CPMENU (CODE, MODULE, LABEL, MENU_KIND, SORT_ORDER, PARENT_CODE)
  SELECT v.CODE, v.MODULE, v.LABEL, v.KIND, v.SORT, v.PARENT FROM (VALUES
    (N''MENU_ORGANIZER'', N''DASHBOARD'', N''Organizer Dashboard'', N''CHILD'', 1, NULL),
    (N''MENU_SELLER'', N''DASHBOARD'', N''Seller Dashboard'', N''CHILD'', 2, NULL)
  ) v(CODE, MODULE, LABEL, KIND, SORT, PARENT)
  WHERE NOT EXISTS (SELECT 1 FROM dbo.CPMENU x WHERE x.CODE = v.CODE);');
ELSE
  EXEC(N'INSERT INTO dbo.CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
  SELECT v.CODE, v.MODULE, v.LABEL, v.MCONTROL, v.KIND, v.SORT, v.PARENT FROM (VALUES
    (N''MENU_ORGANIZER'', N''DASHBOARD'', N''Organizer Dashboard'', N''organizer_dashboard'', N''CHILD'', 1, NULL),
    (N''MENU_SELLER'', N''DASHBOARD'', N''Seller Dashboard'', N''seller_dashboard'', N''CHILD'', 2, NULL)
  ) v(CODE, MODULE, LABEL, MCONTROL, KIND, SORT, PARENT)
  WHERE NOT EXISTS (SELECT 1 FROM dbo.CPMENU x WHERE x.CODE = v.CODE);');

-- Jaga-jaga: bila seed lama "ADMIN = semua CHILD" berjalan ulang setelah file
-- ini, cabut lagi grant DASHBOARD dari semua role (tetap nol akses).
DELETE FROM dbo.CPPERMISSION
WHERE MENU_CODE IN (N'MENU_ORGANIZER', N'MENU_SELLER');

COMMIT TRAN;
