-- Rollback for scripts/migrate6_discovery.sql (discovery tables + columns).
-- Drops new T_ tables, removes added columns, restores the original
-- T_EVENT status check. Idempotent (safe to re-run). Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/migrate6_discovery_rollback.sql
SET XACT_ABORT ON;
BEGIN TRAN;

DROP TABLE IF EXISTS dbo.T_AD_EVENT;
DROP TABLE IF EXISTS dbo.T_AD_CAMPAIGN;
DROP TABLE IF EXISTS dbo.T_NEWS_VIEW;
DROP TABLE IF EXISTS dbo.T_NEWS;
DROP TABLE IF EXISTS dbo.T_NEWS_CATEGORY;

IF COL_LENGTH(N'dbo.T_PROMO', N'COVERAGE_CATEGORY_CODE') IS NOT NULL
  ALTER TABLE dbo.T_PROMO DROP CONSTRAINT FK_T_PROMO_COVCAT;
IF COL_LENGTH(N'dbo.T_PROMO', N'COVERAGE_CATEGORY_CODE') IS NOT NULL
  ALTER TABLE dbo.T_PROMO DROP COLUMN COVERAGE_CATEGORY_CODE;
IF COL_LENGTH(N'dbo.T_PROMO', N'MIN_PURCHASE') IS NOT NULL
BEGIN
  ALTER TABLE dbo.T_PROMO DROP CONSTRAINT DF_T_PROMO_MINPUR;
  ALTER TABLE dbo.T_PROMO DROP COLUMN MIN_PURCHASE;
END
IF COL_LENGTH(N'dbo.T_PROMO', N'MAX_DISCOUNT_AMOUNT') IS NOT NULL
BEGIN
  ALTER TABLE dbo.T_PROMO DROP CONSTRAINT DF_T_PROMO_MAXDISC;
  ALTER TABLE dbo.T_PROMO DROP COLUMN MAX_DISCOUNT_AMOUNT;
END
IF COL_LENGTH(N'dbo.T_PROMO', N'DESCRIPTION') IS NOT NULL
  ALTER TABLE dbo.T_PROMO DROP COLUMN DESCRIPTION;

IF COL_LENGTH(N'dbo.T_TICKET_TYPE', N'SALE_END_AT') IS NOT NULL
  ALTER TABLE dbo.T_TICKET_TYPE DROP COLUMN SALE_END_AT;
IF COL_LENGTH(N'dbo.T_TICKET_TYPE', N'SALE_START_AT') IS NOT NULL
  ALTER TABLE dbo.T_TICKET_TYPE DROP COLUMN SALE_START_AT;

IF COL_LENGTH(N'dbo.T_EVENT', N'POSTER_URL') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP COLUMN POSTER_URL;
IF COL_LENGTH(N'dbo.T_EVENT', N'LONGITUDE') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP COLUMN LONGITUDE;
IF COL_LENGTH(N'dbo.T_EVENT', N'LATITUDE') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP COLUMN LATITUDE;
IF COL_LENGTH(N'dbo.T_EVENT', N'ADDRESS') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP COLUMN ADDRESS;
IF COL_LENGTH(N'dbo.T_EVENT', N'EVENT_CATEGORY_CODE') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP CONSTRAINT FK_T_EVENT_CAT;
IF COL_LENGTH(N'dbo.T_EVENT', N'EVENT_CATEGORY_CODE') IS NOT NULL
  ALTER TABLE dbo.T_EVENT DROP COLUMN EVENT_CATEGORY_CODE;
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_EVENT_STATUS')
  ALTER TABLE dbo.T_EVENT DROP CONSTRAINT CK_T_EVENT_STATUS;
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_EVENT_STATUS')
  ALTER TABLE dbo.T_EVENT ADD CONSTRAINT CK_T_EVENT_STATUS
    CHECK (STATUS IN (N'DRAFT', N'PUBLISHED', N'COMPLETED', N'CANCELLED'));

DROP TABLE IF EXISTS dbo.T_EVENT_CATEGORY;

COMMIT TRAN;
