-- Migration 14: MARKETING module (PROMO / ADS / NEWS extensions).
--
--   Reuses existing T_* tables, adds new ones, never touches CP_* structure
--   except inserting module/menu rows. Patterns copied from migrate5/6/9/12.
--
--   Promo:
--     T_PROMO      += ORGANIZER_CODE, SCOPE_TYPE, MAX_PER_USER
--     New: T_PROMO_SCOPE (coverage per category/event), T_PROMO_USAGE (per order/user)
--   Ads:
--     T_AD_CAMPAIGN += ORGANIZER_CODE, COST, PAYMENT_STATUS, APPROVAL_STATUS, REJECT_NOTE
--     New: T_AD_POSITION (rate per day), T_AD_STAT_DAILY (impressions/clicks per day)
--   News:
--     T_NEWS       += AUTHOR_CODE, SCHEDULED_AT, IS_DELETED (soft delete/archive)
--     STATUS gains ARCHIVED (DRAFT/PUBLISHED/ARCHIVED)
--
--   Module/menus (ZERO grants, same precedent as migrate5/7/10/13):
--     MODULE MARKETING + 3 CHILD menus (mcontrol = frontend/src/app/<mcontrol>/).
--
-- Idempotent (safe to re-run). Rollback: scripts/migrate14_marketing_rollback.sql
-- Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/migrate14_marketing.sql
-- Or: task migrate
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
GO

BEGIN TRAN;

-- 1. T_PROMO: organizer scope + per-user limit + scope type ------------------------
IF COL_LENGTH(N'dbo.T_PROMO', N'ORGANIZER_CODE') IS NULL
  ALTER TABLE dbo.T_PROMO ADD ORGANIZER_CODE NVARCHAR(20) NULL
    CONSTRAINT FK_T_PROMO_ORG REFERENCES dbo.CPUSER (CODE);
GO
IF COL_LENGTH(N'dbo.T_PROMO', N'SCOPE_TYPE') IS NULL
  ALTER TABLE dbo.T_PROMO ADD SCOPE_TYPE NVARCHAR(20) NOT NULL
    CONSTRAINT DF_T_PROMO_SCOPE DEFAULT N'ALL';
GO
IF COL_LENGTH(N'dbo.T_PROMO', N'MAX_PER_USER') IS NULL
  ALTER TABLE dbo.T_PROMO ADD MAX_PER_USER INT NULL;
GO
-- Normalize scope values (legacy rows: infer from EVENT_CODE / COVERAGE_CATEGORY_CODE).
UPDATE dbo.T_PROMO SET SCOPE_TYPE = N'ALL' WHERE SCOPE_TYPE NOT IN (N'ALL', N'CATEGORY', N'EVENT');
GO
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_PROMO_SCOPE')
  ALTER TABLE dbo.T_PROMO DROP CONSTRAINT CK_T_PROMO_SCOPE;
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_PROMO_SCOPE')
  ALTER TABLE dbo.T_PROMO ADD CONSTRAINT CK_T_PROMO_SCOPE
    CHECK (SCOPE_TYPE IN (N'ALL', N'CATEGORY', N'EVENT'));
GO
-- Backfill organizer for existing promos (demo promos belong to organizer).
UPDATE dbo.T_PROMO SET ORGANIZER_CODE = N'USR-ORGANIZER' WHERE ORGANIZER_CODE IS NULL AND CODE LIKE N'PRM-%';
UPDATE dbo.T_PROMO SET ORGANIZER_CODE = N'USR-ORGANIZER' WHERE ORGANIZER_CODE IS NULL AND PROMO_CODE IN (N'HEMAT20', N'EARLY10', N'SOON5', N'DISC10', N'KPOP20', N'SEOUL50', N'NATAL25', N'LAMA15', N'HABIS5');
GO

-- 2. T_PROMO_SCOPE (coverage list when SCOPE_TYPE = CATEGORY or EVENT) ----------
IF OBJECT_ID(N'dbo.T_PROMO_SCOPE', N'U') IS NULL
CREATE TABLE dbo.T_PROMO_SCOPE (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  PROMO_CODE NVARCHAR(20) NOT NULL,
  SCOPE_TYPE NVARCHAR(20) NOT NULL,
  CATEGORY_CODE NVARCHAR(20) NULL,
  EVENT_CODE NVARCHAR(20) NULL,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_PSC_CREATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_PROMO_SCOPE PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_PSC_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_PSC_PROMO FOREIGN KEY (PROMO_CODE) REFERENCES dbo.T_PROMO (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_T_PSC_CAT FOREIGN KEY (CATEGORY_CODE) REFERENCES dbo.T_EVENT_CATEGORY (CODE),
  CONSTRAINT FK_T_PSC_EVENT FOREIGN KEY (EVENT_CODE) REFERENCES dbo.T_EVENT (CODE),
  CONSTRAINT CK_T_PSC_TYPE CHECK (SCOPE_TYPE IN (N'CATEGORY', N'EVENT'))
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_PSC_PROMO' AND object_id = OBJECT_ID(N'dbo.T_PROMO_SCOPE'))
  CREATE NONCLUSTERED INDEX IX_T_PSC_PROMO ON dbo.T_PROMO_SCOPE (PROMO_CODE);
GO

-- 3. T_PROMO_USAGE (per order + per user audit) ----------------------------------
IF OBJECT_ID(N'dbo.T_PROMO_USAGE', N'U') IS NULL
CREATE TABLE dbo.T_PROMO_USAGE (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  PROMO_CODE NVARCHAR(20) NOT NULL,
  ORDER_CODE NVARCHAR(20) NOT NULL,
  USER_CODE NVARCHAR(20) NOT NULL,
  DISCOUNT_AMOUNT DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_PU_AMT DEFAULT 0,
  USED_AT DATETIME NOT NULL CONSTRAINT DF_T_PU_USED DEFAULT GETDATE(),
  CONSTRAINT PK_T_PROMO_USAGE PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_PU_CODE UNIQUE NONCLUSTERED (CODE),
  CONSTRAINT FK_T_PU_PROMO FOREIGN KEY (PROMO_CODE) REFERENCES dbo.T_PROMO (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_T_PU_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES dbo.T_ORDER (CODE) ON DELETE CASCADE,
  CONSTRAINT FK_T_PU_USER FOREIGN KEY (USER_CODE) REFERENCES dbo.CPUSER (CODE)
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_PU_PROMO' AND object_id = OBJECT_ID(N'dbo.T_PROMO_USAGE'))
  CREATE NONCLUSTERED INDEX IX_T_PU_PROMO ON dbo.T_PROMO_USAGE (PROMO_CODE);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_PU_USER' AND object_id = OBJECT_ID(N'dbo.T_PROMO_USAGE'))
  CREATE NONCLUSTERED INDEX IX_T_PU_USER ON dbo.T_PROMO_USAGE (USER_CODE, PROMO_CODE);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_PU_ORDER' AND object_id = OBJECT_ID(N'dbo.T_PROMO_USAGE'))
  CREATE NONCLUSTERED INDEX IX_T_PU_ORDER ON dbo.T_PROMO_USAGE (ORDER_CODE);
GO

-- 4. T_AD_POSITION (rate per day per position) -----------------------------------
IF OBJECT_ID(N'dbo.T_AD_POSITION', N'U') IS NULL
CREATE TABLE dbo.T_AD_POSITION (
  ID INT IDENTITY(1,1) NOT NULL,
  CODE NVARCHAR(20) NOT NULL,
  NAME NVARCHAR(100) NOT NULL,
  PRICE_PER_DAY DECIMAL(18,2) NOT NULL CONSTRAINT DF_T_ADP_PRICE DEFAULT 0,
  SORT_ORDER INT NOT NULL CONSTRAINT DF_T_ADP_SORT DEFAULT 99,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ADP_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ADP_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_AD_POSITION PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_ADP_CODE UNIQUE NONCLUSTERED (CODE)
);
GO
-- Seed default positions (idempotent)
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_POSITION WHERE CODE = N'HOME_BANNER')
  INSERT INTO dbo.T_AD_POSITION (CODE, NAME, PRICE_PER_DAY, SORT_ORDER) VALUES (N'HOME_BANNER', N'Banner Home', 150000, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_POSITION WHERE CODE = N'EVENT_LIST')
  INSERT INTO dbo.T_AD_POSITION (CODE, NAME, PRICE_PER_DAY, SORT_ORDER) VALUES (N'EVENT_LIST', N'Event List', 80000, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_POSITION WHERE CODE = N'SIDEBAR')
  INSERT INTO dbo.T_AD_POSITION (CODE, NAME, PRICE_PER_DAY, SORT_ORDER) VALUES (N'SIDEBAR', N'Sidebar', 100000, 3);
GO

-- 5. T_AD_CAMPAIGN: owner + payment/approval + cost -------------------------------
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'ORGANIZER_CODE') IS NULL
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD ORGANIZER_CODE NVARCHAR(20) NULL
    CONSTRAINT FK_T_ADC_ORG REFERENCES dbo.CPUSER (CODE);
GO
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'COST') IS NULL
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD COST DECIMAL(18,2) NOT NULL
    CONSTRAINT DF_T_ADC_COST DEFAULT 0;
GO
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'PAYMENT_STATUS') IS NULL
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD PAYMENT_STATUS NVARCHAR(20) NOT NULL
    CONSTRAINT DF_T_ADC_PAY DEFAULT N'UNPAID';
GO
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'APPROVAL_STATUS') IS NULL
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD APPROVAL_STATUS NVARCHAR(20) NOT NULL
    CONSTRAINT DF_T_ADC_APPROVAL DEFAULT N'PENDING';
GO
IF COL_LENGTH(N'dbo.T_AD_CAMPAIGN', N'REJECT_NOTE') IS NULL
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD REJECT_NOTE NVARCHAR(500) NULL;
GO
-- Backfill organizer for existing campaigns
UPDATE dbo.T_AD_CAMPAIGN SET ORGANIZER_CODE = N'USR-ORGANIZER' WHERE ORGANIZER_CODE IS NULL;
GO
-- Expand status domain: DRAFT, PENDING_PAYMENT, PENDING_APPROVAL, LIVE, ENDED, REJECTED, PAUSED
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_STATUS')
  ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT CK_T_AD_STATUS;
GO
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_PAY')
  ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT CK_T_AD_PAY;
GO
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_APPROVAL')
  ALTER TABLE dbo.T_AD_CAMPAIGN DROP CONSTRAINT CK_T_AD_APPROVAL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_STATUS')
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD CONSTRAINT CK_T_AD_STATUS
    CHECK (STATUS IN (N'DRAFT', N'PENDING_PAYMENT', N'PENDING_APPROVAL', N'LIVE', N'ACTIVE', N'PAUSED', N'ENDED', N'REJECTED'));
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_PAY')
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD CONSTRAINT CK_T_AD_PAY
    CHECK (PAYMENT_STATUS IN (N'UNPAID', N'PENDING', N'PAID'));
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_AD_APPROVAL')
  ALTER TABLE dbo.T_AD_CAMPAIGN ADD CONSTRAINT CK_T_AD_APPROVAL
    CHECK (APPROVAL_STATUS IN (N'PENDING', N'APPROVED', N'REJECTED'));
GO
-- Normalize legacy statuses: ACTIVE -> LIVE for live flight campaigns
UPDATE dbo.T_AD_CAMPAIGN SET STATUS = N'LIVE' WHERE STATUS = N'ACTIVE' AND START_AT <= GETDATE() AND END_AT >= GETDATE();
UPDATE dbo.T_AD_CAMPAIGN SET STATUS = N'ENDED' WHERE STATUS = N'ACTIVE' AND END_AT < GETDATE();
GO

-- 6. T_AD_STAT_DAILY (per campaign per day aggregates) ----------------------------
IF OBJECT_ID(N'dbo.T_AD_STAT_DAILY', N'U') IS NULL
CREATE TABLE dbo.T_AD_STAT_DAILY (
  ID INT IDENTITY(1,1) NOT NULL,
  CAMPAIGN_CODE NVARCHAR(20) NOT NULL,
  STAT_DATE DATE NOT NULL,
  IMPRESSIONS INT NOT NULL CONSTRAINT DF_T_ASD_IMP DEFAULT 0,
  CLICKS INT NOT NULL CONSTRAINT DF_T_ASD_CLK DEFAULT 0,
  CREATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ASD_CREATED DEFAULT GETDATE(),
  UPDATED_AT DATETIME NOT NULL CONSTRAINT DF_T_ASD_UPDATED DEFAULT GETDATE(),
  CONSTRAINT PK_T_AD_STAT_DAILY PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT UQ_T_ASD_CAMP_DATE UNIQUE NONCLUSTERED (CAMPAIGN_CODE, STAT_DATE),
  CONSTRAINT FK_T_ASD_CAMP FOREIGN KEY (CAMPAIGN_CODE) REFERENCES dbo.T_AD_CAMPAIGN (CODE) ON DELETE CASCADE
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_ASD_CAMP' AND object_id = OBJECT_ID(N'dbo.T_AD_STAT_DAILY'))
  CREATE NONCLUSTERED INDEX IX_T_ASD_CAMP ON dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE);
GO

-- 7. T_NEWS: author + schedule + soft-delete + ARCHIVED ---------------------------
IF COL_LENGTH(N'dbo.T_NEWS', N'AUTHOR_CODE') IS NULL
  ALTER TABLE dbo.T_NEWS ADD AUTHOR_CODE NVARCHAR(20) NULL
    CONSTRAINT FK_T_NEWS_AUTHOR REFERENCES dbo.CPUSER (CODE);
GO
IF COL_LENGTH(N'dbo.T_NEWS', N'SCHEDULED_AT') IS NULL
  ALTER TABLE dbo.T_NEWS ADD SCHEDULED_AT DATETIME NULL;
GO
IF COL_LENGTH(N'dbo.T_NEWS', N'IS_DELETED') IS NULL
  ALTER TABLE dbo.T_NEWS ADD IS_DELETED BIT NOT NULL
    CONSTRAINT DF_T_NEWS_DELETED DEFAULT 0;
GO
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_NEWS_STATUS')
  ALTER TABLE dbo.T_NEWS DROP CONSTRAINT CK_T_NEWS_STATUS;
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = N'CK_T_NEWS_STATUS')
  ALTER TABLE dbo.T_NEWS ADD CONSTRAINT CK_T_NEWS_STATUS
    CHECK (STATUS IN (N'DRAFT', N'PUBLISHED', N'ARCHIVED'));
GO
UPDATE dbo.T_NEWS SET AUTHOR_CODE = N'USR-ORGANIZER' WHERE AUTHOR_CODE IS NULL;
GO

-- 8. Index promo organizer + campaign organizer + news publish ---------------------
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_PROMO_ORG' AND object_id = OBJECT_ID(N'dbo.T_PROMO'))
  CREATE NONCLUSTERED INDEX IX_T_PROMO_ORG ON dbo.T_PROMO (ORGANIZER_CODE, STATUS, VALID_TO);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_ADC_ORG' AND object_id = OBJECT_ID(N'dbo.T_AD_CAMPAIGN'))
  CREATE NONCLUSTERED INDEX IX_T_ADC_ORG ON dbo.T_AD_CAMPAIGN (ORGANIZER_CODE, STATUS, START_AT);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_NEWS_AUTHOR' AND object_id = OBJECT_ID(N'dbo.T_NEWS'))
  CREATE NONCLUSTERED INDEX IX_T_NEWS_AUTHOR ON dbo.T_NEWS (AUTHOR_CODE, STATUS, PUBLISHED_AT DESC);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_T_NEWS_SCHED' AND object_id = OBJECT_ID(N'dbo.T_NEWS'))
  CREATE NONCLUSTERED INDEX IX_T_NEWS_SCHED ON dbo.T_NEWS (STATUS, SCHEDULED_AT);
GO

-- 9. Module MARKETING + 3 menus (ZERO grants) ------------------------------------
INSERT INTO dbo.CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT N'MARKETING', N'Marketing', 6
WHERE NOT EXISTS (SELECT 1 FROM dbo.CPMODULE WHERE CODE = N'MARKETING');
GO

IF COL_LENGTH(N'dbo.CPMENU', N'MCONTROL') IS NULL
  EXEC(N'INSERT INTO dbo.CPMENU (CODE, MODULE, LABEL, MENU_KIND, SORT_ORDER, PARENT_CODE)
  SELECT v.CODE, v.MODULE, v.LABEL, v.KIND, v.SORT, v.PARENT FROM (VALUES
    (N''MENU_PROMO_CODES'', N''MARKETING'', N''Promo Codes'', N''CHILD'', 1, NULL),
    (N''MENU_AD_CAMPAIGNS'', N''MARKETING'', N''Ad Campaigns'', N''CHILD'', 2, NULL),
    (N''MENU_NEWS_MANAGEMENT'', N''MARKETING'', N''News Management'', N''CHILD'', 3, NULL)
  ) v(CODE, MODULE, LABEL, KIND, SORT, PARENT)
  WHERE NOT EXISTS (SELECT 1 FROM dbo.CPMENU x WHERE x.CODE = v.CODE);');
ELSE
  EXEC(N'INSERT INTO dbo.CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
  SELECT v.CODE, v.MODULE, v.LABEL, v.MCONTROL, v.KIND, v.SORT, v.PARENT FROM (VALUES
    (N''MENU_PROMO_CODES'', N''MARKETING'', N''Promo Codes'', N''promo_codes'', N''CHILD'', 1, NULL),
    (N''MENU_AD_CAMPAIGNS'', N''MARKETING'', N''Ad Campaigns'', N''ad_campaigns'', N''CHILD'', 2, NULL),
    (N''MENU_NEWS_MANAGEMENT'', N''MARKETING'', N''News Management'', N''news_management'', N''CHILD'', 3, NULL)
  ) v(CODE, MODULE, LABEL, MCONTROL, KIND, SORT, PARENT)
  WHERE NOT EXISTS (SELECT 1 FROM dbo.CPMENU x WHERE x.CODE = v.CODE);');
GO

DELETE FROM dbo.CPPERMISSION
WHERE MENU_CODE IN (N'MENU_PROMO_CODES', N'MENU_AD_CAMPAIGNS', N'MENU_NEWS_MANAGEMENT');
GO

COMMIT TRAN;
