-- Skema SQLite (fresh install). Relasi via CODE, tabel huruf besar prefix CP.
-- Jalankan sekali (butuh sqlite3 CLI):
--   sqlite3 ./data/go-core.db < scripts/schema.sqlite.sql
-- Env: DB_CONNECTION=sqlite + DB_DATABASE=./data/go-core.db
-- Catatan: aktifkan foreign_keys bila akses manual:
--   PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS CPROLE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CPROLE (CODE, NAME)
SELECT 'ADMIN', 'Administrator'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'ADMIN');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'USER', 'Pengguna'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'USER');

CREATE TABLE IF NOT EXISTS CPUSER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  USERNAME TEXT NOT NULL UNIQUE,
  EMAIL TEXT NOT NULL UNIQUE,
  PASSWORD TEXT NOT NULL,
  ROLE_CODE TEXT NOT NULL DEFAULT 'USER' REFERENCES CPROLE (CODE),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CPREFRESHTOKEN (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE) ON DELETE CASCADE,
  TOKEN TEXT NOT NULL UNIQUE,
  EXPIRES_AT DATETIME NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- (CPPERMISSION sebagai tabel grant dibuat setelah CPMENU di bawah,
-- karena FK-nya menunjuk ke sana. Tidak ada tabel definisi terpisah:
-- definisi menu tinggal di CPMENU.)

-- CPMATRIX: master modul. CPMENU.MCONTROL ber-FK ke sini (modul dibuat dulu).
CREATE TABLE IF NOT EXISTS CPMATRIX (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  LABEL TEXT NOT NULL,
  SORT_ORDER INTEGER NOT NULL DEFAULT 99,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CPMATRIX (CODE, LABEL, SORT_ORDER)
SELECT 'SYSTEM', 'System', 1
WHERE NOT EXISTS (SELECT 1 FROM CPMATRIX WHERE CODE = 'SYSTEM');
INSERT INTO CPMATRIX (CODE, LABEL, SORT_ORDER)
SELECT 'REPORT', 'Report', 2
WHERE NOT EXISTS (SELECT 1 FROM CPMATRIX WHERE CODE = 'REPORT');

-- CPMENU: registry menu. MCONTROL = nama folder modul (UPPERCASE),
-- wajib sama persis dengan folder frontend menus/<MCONTROL>/... .
CREATE TABLE IF NOT EXISTS CPMENU (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  MCONTROL TEXT NOT NULL REFERENCES CPMATRIX (CODE),
  LABEL TEXT NOT NULL,
  SORT_ORDER INTEGER NOT NULL DEFAULT 99,
  PARENT_CODE TEXT REFERENCES CPMENU (CODE),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (MCONTROL, CODE)
);
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_USERS', 'SYSTEM', 'User Account', 1
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_USERS');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_MODUL', 'SYSTEM', 'Modul & Menu', 2
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_MODUL');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_ROLES', 'SYSTEM', 'Role & Permission', 3
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_ROLES');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_SESSIONS', 'SYSTEM', 'Sesi & Auth', 4
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SESSIONS');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_AUDIT', 'SYSTEM', 'Audit Log', 5
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_AUDIT');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_SECURITY', 'SYSTEM', 'Security Center', 6
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SECURITY');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_SYSLOG', 'SYSTEM', 'System Log', 7
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SYSLOG');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_NOTIFICATIONS', 'SYSTEM', 'Notifikasi', 8
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_NOTIFICATIONS');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_LAPORAN', 'REPORT', 'Laporan', 1
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_LAPORAN');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_ARUS_KAS', 'REPORT', 'Arus Kas', 2, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_ARUS_KAS');

-- CPPERMISSION: satu-satunya tabel relasi grant (ROLE_CODE -> MENU_CODE).
-- Definisi menu tinggal di CPMENU; tidak ada tabel definisi terpisah.
CREATE TABLE IF NOT EXISTS CPPERMISSION (
  ROLE_CODE TEXT NOT NULL REFERENCES CPROLE (CODE) ON DELETE CASCADE,
  MENU_CODE TEXT NOT NULL REFERENCES CPMENU (CODE) ON DELETE CASCADE,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ROLE_CODE, MENU_CODE)
);
-- ADMIN mendapat semua menu kecuali contoh tes tampilan (tanpa akses).
-- USER nol mapping (manual via UI).
INSERT INTO CPPERMISSION (ROLE_CODE, MENU_CODE)
SELECT 'ADMIN', CODE FROM CPMENU
WHERE CODE NOT IN ('MENU_LAPORAN', 'MENU_ARUS_KAS')
AND NOT EXISTS (
  SELECT 1 FROM CPPERMISSION x WHERE x.ROLE_CODE = 'ADMIN' AND x.MENU_CODE = CPMENU.CODE
);

-- Matriks role x modul x menu dibaca via JOIN (CPROLE x CPMENU LEFT JOIN
-- CPPERMISSION); tulis grant tetap ke CPPERMISSION (tidak ada sinkron ganda).
-- Catatan: dulu CPMATRIX adalah VIEW. Sekarang CPMATRIX = tabel master modul
-- (lihat di atas), jadi tidak ada view yang perlu di-drop.

CREATE TABLE IF NOT EXISTS CPAUDITLOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ACTOR_CODE TEXT,
  ACTION TEXT NOT NULL,
  ENTITY TEXT NOT NULL,
  ENTITY_CODE TEXT,
  DETAIL TEXT,
  IP_ADDRESS TEXT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTION ON CPAUDITLOG (ACTION, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTOR ON CPAUDITLOG (ACTOR_CODE, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPSYSLOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  LEVEL TEXT NOT NULL,
  SOURCE TEXT NOT NULL,
  MESSAGE TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_CPSYS_LEVEL ON CPSYSLOG (LEVEL, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPNOTIFTEMPLATE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CHANNEL TEXT NOT NULL,
  SUBJECT TEXT,
  BODY TEXT NOT NULL,
  IS_ACTIVE INTEGER NOT NULL DEFAULT 1,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
SELECT 'NTPL-WELCOME', 'Selamat datang', 'EMAIL', 'Selamat datang di Go Core, {{nama}}!',
'Halo {{nama}},

Akun Anda ({{kode}}) berhasil dibuat dengan role {{role}}.
Silakan login untuk mulai menggunakan aplikasi.

Salam,
Tim Go Core'
WHERE NOT EXISTS (SELECT 1 FROM CPNOTIFTEMPLATE WHERE CODE = 'NTPL-WELCOME');
INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
SELECT 'NTPL-RESET', 'Reset password', 'EMAIL', 'Permintaan reset password akun {{kode}}',
'Halo {{nama}},

Kami menerima permintaan reset password untuk akun {{kode}}.
Abaikan pesan ini bila Anda tidak memintanya.

Salam,
Tim Go Core'
WHERE NOT EXISTS (SELECT 1 FROM CPNOTIFTEMPLATE WHERE CODE = 'NTPL-RESET');
INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
SELECT 'NTPL-ALERT', 'Peringatan keamanan', 'INAPP', 'Peringatan keamanan',
'Aktivitas penting terdeteksi pada akun {{kode}}: {{detail}}'
WHERE NOT EXISTS (SELECT 1 FROM CPNOTIFTEMPLATE WHERE CODE = 'NTPL-ALERT');

CREATE TABLE IF NOT EXISTS CPNOTIFLOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  TEMPLATE_CODE TEXT,
  CHANNEL TEXT NOT NULL,
  RECIPIENT TEXT NOT NULL,
  SUBJECT TEXT,
  BODY TEXT NOT NULL,
  STATUS TEXT NOT NULL,
  ERROR TEXT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed 2 akun awal (sama seperti scripts/seed-admin.sql untuk SQL Server):
-- admin/admin (ADMIN) + user/user (USER). WAJIB ganti password setelah login
-- pertama, dan jangan dipakai di production apa adanya.
-- Hash di bawah = bcrypt; sama persis dengan seed SQL Server.
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-000004', 'admin', 'admin@example.com',
  '$2a$10$vq5MqkuG4/mD/twgYMBsxeOwbrmL3xE88rIpOEzMYt./TmL8xKAqO', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'admin');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-USER0001', 'user', 'user@example.com',
  '$2a$10$MpKcDZmTSotcNefe53ODl.3frNUr0E/fuU/cpAKPglu85tG0Niyr6', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'user');
