-- Skema SQLite (fresh install). Relasi via CODE, tabel huruf besar prefix CP.
-- Jalankan sekali (butuh sqlite3 CLI):
--   sqlite3 ./data/go-core.db < scripts/schema.sqlite.sql
-- Env: DB_CONNECTION=sqlite + DB_DATABASE=./data/go-core.db
-- Catatan: aktifkan foreign_keys bila akses manual:
--   PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS CPROLE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CPROLE (CODE, NAME)
SELECT 'ADMIN', 'Administrator'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'ADMIN');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'USER', 'Pengguna'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'USER');

CREATE TABLE IF NOT EXISTS CPUSER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  USERNAME TEXT NOT NULL UNIQUE,
  EMAIL TEXT NOT NULL UNIQUE,
  PASSWORD TEXT NOT NULL,
  ROLE_CODE TEXT NOT NULL DEFAULT 'USER' REFERENCES CPROLE (CODE),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CPREFRESHTOKEN (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE) ON DELETE CASCADE,
  TOKEN TEXT NOT NULL UNIQUE,
  EXPIRES_AT DATETIME NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CPPERMISSION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  PERMGROUP TEXT NOT NULL,
  DESCRIPTION TEXT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CPPERMISSION (CODE, NAME, PERMGROUP, DESCRIPTION) VALUES
  ('MENU_USERS', 'Akses menu User Account', 'SYSTEM', 'Seluruh fungsi pengelolaan pengguna'),
  ('MENU_ROLES', 'Akses menu Role & Permission', 'SYSTEM', 'Seluruh fungsi pengelolaan role'),
  ('MENU_SESSIONS', 'Akses menu Sesi', 'SYSTEM', 'Seluruh fungsi pengelolaan sesi'),
  ('MENU_AUDIT', 'Akses menu Audit Log', 'SYSTEM', 'Seluruh fungsi audit log'),
  ('MENU_SECURITY', 'Akses menu Security Center', 'SYSTEM', 'Seluruh fungsi security center'),
  ('MENU_SYSLOG', 'Akses menu System Log', 'SYSTEM', 'Seluruh fungsi system log'),
  ('MENU_NOTIFICATIONS', 'Akses menu Notifikasi', 'SYSTEM', 'Seluruh fungsi notifikasi')
ON CONFLICT(CODE) DO UPDATE SET NAME=excluded.NAME, PERMGROUP=excluded.PERMGROUP, DESCRIPTION=excluded.DESCRIPTION;
-- MENU_DASHBOARD sengaja tidak ada: modul account dihapus, USER nol menu.

CREATE TABLE IF NOT EXISTS CPROLEPERMISSION (
  ROLE_CODE TEXT NOT NULL REFERENCES CPROLE (CODE) ON DELETE CASCADE,
  PERMISSION_CODE TEXT NOT NULL REFERENCES CPPERMISSION (CODE) ON DELETE CASCADE,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ROLE_CODE, PERMISSION_CODE)
);
INSERT INTO CPROLEPERMISSION (ROLE_CODE, PERMISSION_CODE)
SELECT 'ADMIN', CODE FROM CPPERMISSION
WHERE NOT EXISTS (
  SELECT 1 FROM CPROLEPERMISSION x WHERE x.ROLE_CODE = 'ADMIN' AND x.PERMISSION_CODE = CPPERMISSION.CODE
);
-- USER tidak diberi menu apa pun (nol mapping); akses diberikan manual oleh admin.

-- CPMENU: registry menu. MCONTROL = nama folder modul (UPPERCASE),
-- wajib sama persis dengan folder frontend menus/<MCONTROL>/... .
CREATE TABLE IF NOT EXISTS CPMENU (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  MCONTROL TEXT NOT NULL,
  LABEL TEXT NOT NULL,
  SORT_ORDER INTEGER NOT NULL DEFAULT 99,
  PARENT_CODE TEXT REFERENCES CPMENU (CODE),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (MCONTROL, CODE)
);
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_USERS', 'SYSTEM', 'User Account', 1
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_USERS');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_ROLES', 'SYSTEM', 'Role & Permission', 2
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_ROLES');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_SESSIONS', 'SYSTEM', 'Sesi & Auth', 3
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SESSIONS');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_AUDIT', 'SYSTEM', 'Audit Log', 4
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_AUDIT');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_SECURITY', 'SYSTEM', 'Security Center', 5
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SECURITY');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_SYSLOG', 'SYSTEM', 'System Log', 6
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SYSLOG');
INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER)
SELECT 'MENU_NOTIFICATIONS', 'SYSTEM', 'Notifikasi', 7
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_NOTIFICATIONS');

-- CPMATRIX: view matriks role x modul x menu (satu-satunya bacaan matriks).
-- Tulis tetap lewat CPROLEPERMISSION (tidak ada sinkron ganda).
DROP VIEW IF EXISTS CPMATRIX;
CREATE VIEW CPMATRIX AS
SELECT r.CODE AS ROLE_CODE, r.NAME AS ROLE_NAME,
       m.MCONTROL AS MODULE, m.CODE AS MENU_CODE, m.LABEL AS MENU_LABEL,
       m.SORT_ORDER, m.PARENT_CODE,
       CASE WHEN pm.ROLE_CODE IS NULL THEN 0 ELSE 1 END AS HAS_ACCESS
FROM CPROLE r
CROSS JOIN CPMENU m
LEFT JOIN CPROLEPERMISSION pm
  ON pm.ROLE_CODE = r.CODE AND pm.PERMISSION_CODE = m.CODE;

CREATE TABLE IF NOT EXISTS CPAUDITLOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ACTOR_CODE TEXT,
  ACTION TEXT NOT NULL,
  ENTITY TEXT NOT NULL,
  ENTITY_CODE TEXT,
  DETAIL TEXT,
  IP_ADDRESS TEXT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTION ON CPAUDITLOG (ACTION, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTOR ON CPAUDITLOG (ACTOR_CODE, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPSYSLOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  LEVEL TEXT NOT NULL,
  SOURCE TEXT NOT NULL,
  MESSAGE TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_CPSYS_LEVEL ON CPSYSLOG (LEVEL, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPNOTIFTEMPLATE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CHANNEL TEXT NOT NULL,
  SUBJECT TEXT,
  BODY TEXT NOT NULL,
  IS_ACTIVE INTEGER NOT NULL DEFAULT 1,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
SELECT 'NTPL-WELCOME', 'Selamat datang', 'EMAIL', 'Selamat datang di Go Core, {{nama}}!',
'Halo {{nama}},

Akun Anda ({{kode}}) berhasil dibuat dengan role {{role}}.
Silakan login untuk mulai menggunakan aplikasi.

Salam,
Tim Go Core'
WHERE NOT EXISTS (SELECT 1 FROM CPNOTIFTEMPLATE WHERE CODE = 'NTPL-WELCOME');
INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
SELECT 'NTPL-RESET', 'Reset password', 'EMAIL', 'Permintaan reset password akun {{kode}}',
'Halo {{nama}},

Kami menerima permintaan reset password untuk akun {{kode}}.
Abaikan pesan ini bila Anda tidak memintanya.

Salam,
Tim Go Core'
WHERE NOT EXISTS (SELECT 1 FROM CPNOTIFTEMPLATE WHERE CODE = 'NTPL-RESET');
INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
SELECT 'NTPL-ALERT', 'Peringatan keamanan', 'INAPP', 'Peringatan keamanan',
'Aktivitas penting terdeteksi pada akun {{kode}}: {{detail}}'
WHERE NOT EXISTS (SELECT 1 FROM CPNOTIFTEMPLATE WHERE CODE = 'NTPL-ALERT');

CREATE TABLE IF NOT EXISTS CPNOTIFLOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  TEMPLATE_CODE TEXT,
  CHANNEL TEXT NOT NULL,
  RECIPIENT TEXT NOT NULL,
  SUBJECT TEXT,
  BODY TEXT NOT NULL,
  STATUS TEXT NOT NULL,
  ERROR TEXT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
