-- Skema PostgreSQL (fresh install). Relasi via CODE, tabel huruf besar prefix CP.
-- Jalankan sekali: psql -h localhost -U <user> -d <db> -f scripts/schema.postgres.sql
-- Env: DB_CONNECTION=postgres (+ DB_HOST/DB_PORT/DB_DATABASE/DB_USERNAME/DB_PASSWORD)

CREATE TABLE IF NOT EXISTS CPROLE (
  ID SERIAL PRIMARY KEY,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);
INSERT INTO CPROLE (CODE, NAME)
SELECT 'ADMIN', 'Administrator'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'ADMIN');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'USER', 'Pengguna'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'USER');
-- Ticket-app roles (English only, zero menu grants by design).
INSERT INTO CPROLE (CODE, NAME)
SELECT 'AUDIENCE', 'Audience'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'AUDIENCE');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'ORGANIZER', 'Event Organizer'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'ORGANIZER');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'SELLER', 'Seller'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'SELLER');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'OFFICER', 'Check-in Officer'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'OFFICER');

CREATE TABLE IF NOT EXISTS CPUSER (
  ID SERIAL PRIMARY KEY,
  CODE TEXT NOT NULL UNIQUE,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE_CODE TEXT NOT NULL DEFAULT 'USER' REFERENCES CPROLE (CODE),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS CPREFRESHTOKEN (
  ID SERIAL PRIMARY KEY,
  USER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE) ON DELETE CASCADE,
  TOKEN VARCHAR(512) NOT NULL UNIQUE,
  EXPIRES_AT TIMESTAMP NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

-- (CPPERMISSION sebagai tabel grant dibuat setelah CPMENU di bawah,
-- karena FK-nya menunjuk ke sana.)

-- CPMODULE: master modul. Satu baris = satu section sidebar + satu folder
-- di frontend/src/app/<MODULE>/. CPMENU.MODULE ber-FK ke sini (modul
-- dibuat dulu, baru menunya).
CREATE TABLE IF NOT EXISTS CPMODULE (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(40) NOT NULL UNIQUE,
  LABEL VARCHAR(100) NOT NULL,
  SORT_ORDER INT NOT NULL DEFAULT 99,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'SYSTEM', 'System', 1
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'SYSTEM');

-- CPMENU: registry menu. MODULE = kode modul (FK ke CPMODULE.CODE),
-- menentukan section sidebar level-1 (MODULE tampil sebagai section header).
-- MCONTROL = nama folder frontend (snake_case, mis. user_account): halaman
-- menu tinggal di frontend/src/app/<mcontrol>/index.jsx — datar, tanpa
-- folder modul perantara. NULL = menu PARENT (header buka-tutup di sidebar,
-- tanpa halaman/folder). Judul tampil = LABEL.
-- MENU_KIND: 'PARENT' = header buka-tutup (MCONTROL wajib NULL, tidak boleh
-- punya PARENT_CODE), 'CHILD' = item biasa (MCONTROL wajib unik, boleh punya
-- PARENT_CODE yang menunjuk menu PARENT se-modul, tanpa siklus).
CREATE TABLE IF NOT EXISTS CPMENU (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(40) NOT NULL UNIQUE,
  MODULE VARCHAR(40) NOT NULL REFERENCES CPMODULE (CODE),
  LABEL VARCHAR(100) NOT NULL,
  MCONTROL VARCHAR(40) UNIQUE,
  MENU_KIND VARCHAR(10) NOT NULL DEFAULT 'CHILD' CHECK (MENU_KIND IN ('PARENT', 'CHILD')),
  SORT_ORDER INT NOT NULL DEFAULT 99,
  PARENT_CODE VARCHAR(40) REFERENCES CPMENU (CODE),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (MODULE, CODE),
  CHECK ((MENU_KIND = 'PARENT' AND MCONTROL IS NULL) OR (MENU_KIND = 'CHILD' AND MCONTROL IS NOT NULL))
);

-- Seed menu bawaan (urut sesuai sidebar).
-- MCONTROL snake_case = nama folder frontend/src/app/<mcontrol>/.
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE) VALUES
  ('MENU_USERS',         'SYSTEM', 'User Account',       'users',           'CHILD',  1, NULL),
  ('MENU_MODUL',         'SYSTEM', 'Modul & Menu',       'modul_menu',      'CHILD',  2, NULL),
  ('MENU_ROLES',         'SYSTEM', 'Role & Permission',  'role_permission', 'CHILD',  3, NULL),
  ('MENU_SESSIONS',      'SYSTEM', 'Sesi & Auth',        'sesi_auth',       'CHILD',  4, NULL),
  ('MENU_AUDIT',         'SYSTEM', 'Audit Log',          'audit_log',       'CHILD',  5, NULL),
  ('MENU_SECURITY',      'SYSTEM', 'Security Center',    'security_center', 'CHILD',  6, NULL),
  ('MENU_SYSLOG',        'SYSTEM', 'System Log',         'system_log',      'CHILD',  7, NULL),
  ('MENU_NOTIFICATIONS', 'SYSTEM', 'Notifikasi',         'notifikasi',      'CHILD',  8, NULL)
ON CONFLICT (CODE) DO NOTHING;
-- Bersihkan sisa menu REPORT yang sudah dihapus (database lama).
DELETE FROM CPMENU WHERE CODE IN ('MENU_ARUS_KAS', 'MENU_LAPORAN', 'MENU_KEUANGAN');
DELETE FROM CPMODULE WHERE CODE = 'REPORT';

-- CPPERMISSION: satu-satunya tabel relasi grant (ROLE_CODE -> MENU_CODE).
-- Definisi menu tinggal di CPMENU; tidak ada tabel definisi terpisah.
CREATE TABLE IF NOT EXISTS CPPERMISSION (
  ROLE_CODE TEXT NOT NULL REFERENCES CPROLE (CODE) ON DELETE CASCADE,
  MENU_CODE VARCHAR(40) NOT NULL REFERENCES CPMENU (CODE) ON DELETE CASCADE,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (ROLE_CODE, MENU_CODE)
);

-- ADMIN mendapat semua menu CHILD.
-- Menu PARENT tidak pernah di-grant: header buka-tutup tanpa halaman sendiri,
-- aksesnya menyusul otomatis dari menu CHILD di bawahnya.
-- USER nol mapping (manual via UI).
INSERT INTO CPPERMISSION (ROLE_CODE, MENU_CODE)
SELECT 'ADMIN', CODE FROM CPMENU
WHERE MENU_KIND = 'CHILD'
ON CONFLICT DO NOTHING;
-- Bersihkan grant PARENT sisa database lama (matriks kini hanya mencentang CHILD).
DELETE FROM CPPERMISSION
WHERE MENU_CODE IN (SELECT CODE FROM CPMENU WHERE MENU_KIND = 'PARENT');
-- Bersihkan sisa grant REPORT yang sudah dihapus (database lama).
DELETE FROM CPPERMISSION WHERE MENU_CODE IN ('MENU_LAPORAN', 'MENU_ARUS_KAS', 'MENU_KEUANGAN');

-- Matriks role x modul x menu dibaca via JOIN (CPROLE x CPMENU LEFT JOIN
-- CPPERMISSION); tulis grant tetap ke CPPERMISSION (tidak ada sinkron ganda).

CREATE TABLE IF NOT EXISTS CPAUDITLOG (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ACTOR_CODE VARCHAR(20),
  ACTION VARCHAR(60) NOT NULL,
  ENTITY VARCHAR(40) NOT NULL,
  ENTITY_CODE VARCHAR(60),
  DETAIL VARCHAR(1000),
  IP_ADDRESS VARCHAR(60),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTION ON CPAUDITLOG (ACTION, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTOR ON CPAUDITLOG (ACTOR_CODE, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPSYSLOG (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  LEVEL VARCHAR(10) NOT NULL,
  SOURCE VARCHAR(100) NOT NULL,
  MESSAGE VARCHAR(1000) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS IX_CPSYS_LEVEL ON CPSYSLOG (LEVEL, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPNOTIFTEMPLATE (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  NAME VARCHAR(100) NOT NULL,
  CHANNEL VARCHAR(10) NOT NULL,
  SUBJECT VARCHAR(200),
  BODY VARCHAR(4000) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY) VALUES
  ('NTPL-WELCOME', 'Selamat datang', 'EMAIL', 'Selamat datang di Go Core, {{nama}}!',
   'Halo {{nama}},

Akun Anda ({{kode}}) berhasil dibuat dengan role {{role}}.
Silakan login untuk mulai menggunakan aplikasi.

Salam,
Tim Go Core'),
  ('NTPL-RESET', 'Reset password', 'EMAIL', 'Permintaan reset password akun {{kode}}',
   'Halo {{nama}},

Kami menerima permintaan reset password untuk akun {{kode}}.
Abaikan pesan ini bila Anda tidak memintanya.

Salam,
Tim Go Core'),
  ('NTPL-ALERT', 'Peringatan keamanan', 'INAPP', 'Peringatan keamanan',
   'Aktivitas penting terdeteksi pada akun {{kode}}: {{detail}}')
ON CONFLICT (CODE) DO NOTHING;

CREATE TABLE IF NOT EXISTS CPNOTIFLOG (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  TEMPLATE_CODE VARCHAR(20),
  CHANNEL VARCHAR(10) NOT NULL,
  RECIPIENT VARCHAR(255) NOT NULL,
  SUBJECT VARCHAR(200),
  BODY VARCHAR(4000) NOT NULL,
  STATUS VARCHAR(10) NOT NULL,
  ERROR VARCHAR(500),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Seed starter accounts (password = username + "123", bcrypt).
-- admin/admin123 (ADMIN) + audience/audience123 (AUDIENCE) +
-- organizer/organizer123 (ORGANIZER) + seller/seller123 (SELLER) +
-- officer/officer123 (OFFICER), plus legacy user/user (USER).
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-ADMIN', 'admin', 'admin@ticket.app',
  '$2a$10$pPedrlyKaNDNl.uZMHK.F.jSkchAcyDcz2kgU1qOQKmLXO/KECB3.', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'admin');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-AUDIENCE', 'audience', 'audience@ticket.app',
  '$2a$10$IZUzHE4snobTnbmKwb.lQ.APsOKdWvYpfermkIwtcMxiPMUUruTnW', 'AUDIENCE'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'audience');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-ORGANIZER', 'organizer', 'organizer@ticket.app',
  '$2a$10$HFQR9/SSJPcvsDX4HXMXKuvnYz9DV/JTelLL4bc/Decxehdj1d3b6', 'ORGANIZER'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'organizer');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-SELLER', 'seller', 'seller@ticket.app',
  '$2a$10$sZLQKWkONHQ4muRlWVZeqeO8gYIpvBepQuEPy6DHDxA1WpoWMDpre', 'SELLER'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'seller');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-OFFICER', 'officer', 'officer@ticket.app',
  '$2a$10$nHVgbB3.h39bb4k4yJbBmuzN6Ddmsqhi9t0LXuOOHAtMXTPyWLFde', 'OFFICER'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'officer');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-USER0001', 'user', 'user@example.com',
  '$2a$10$MpKcDZmTSotcNefe53ODl.3frNUr0E/fuU/cpAKPglu85tG0Niyr6', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'user');

-- Dashboard tables (prefix T_, mirror of scripts/migrate5_dashboard.sql).
-- Placed AFTER the ADMIN grant above so dashboard menus get ZERO grants.
CREATE TABLE IF NOT EXISTS T_CITY (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  NAME VARCHAR(100) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_EVENT (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ORGANIZER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  CITY_CODE VARCHAR(20) REFERENCES T_CITY (CODE),
  TITLE VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(1000),
  VENUE VARCHAR(200),
  START_AT TIMESTAMP NOT NULL,
  END_AT TIMESTAMP,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED' CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'COMPLETED', 'CANCELLED')),
  PLATFORM_FEE_PERCENT DECIMAL(5,2) NOT NULL DEFAULT 10.00,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_TICKET_TYPE (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  EVENT_CODE VARCHAR(20) NOT NULL REFERENCES T_EVENT (CODE) ON DELETE CASCADE,
  NAME VARCHAR(100) NOT NULL,
  PRICE DECIMAL(18,2) NOT NULL DEFAULT 0,
  QUOTA INT NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_PROMO (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  EVENT_CODE VARCHAR(20) REFERENCES T_EVENT (CODE) ON DELETE CASCADE,
  PROMO_CODE VARCHAR(40) NOT NULL UNIQUE,
  DISCOUNT_PERCENT DECIMAL(5,2) NOT NULL DEFAULT 0,
  DISCOUNT_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  MAX_USES INT,
  USED_COUNT INT NOT NULL DEFAULT 0,
  VALID_FROM TIMESTAMP NOT NULL,
  VALID_TO TIMESTAMP NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'EXPIRED', 'DISABLED')),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_ORDER (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  EVENT_CODE VARCHAR(20) NOT NULL REFERENCES T_EVENT (CODE),
  BUYER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  TICKET_TYPE_CODE VARCHAR(20) NOT NULL REFERENCES T_TICKET_TYPE (CODE),
  QTY INT NOT NULL,
  GROSS_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  DISCOUNT_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  PLATFORM_FEE DECIMAL(18,2) NOT NULL DEFAULT 0,
  NET_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  PROMO_CODE VARCHAR(40),
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PAID' CHECK (STATUS IN ('PENDING', 'PAID', 'CANCELLED', 'REFUNDED')),
  ORDER_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_TICKET (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ORDER_CODE VARCHAR(20) NOT NULL REFERENCES T_ORDER (CODE) ON DELETE CASCADE,
  QR_CODE VARCHAR(64) NOT NULL UNIQUE,
  HOLDER_NAME VARCHAR(100),
  STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'USED', 'REFUNDED')),
  CHECKED_IN_AT TIMESTAMP,
  CHECKED_IN_BY VARCHAR(20) REFERENCES CPUSER (CODE),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_REFUND (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ORDER_CODE VARCHAR(20) NOT NULL REFERENCES T_ORDER (CODE),
  AMOUNT DECIMAL(18,2) NOT NULL,
  REASON VARCHAR(500),
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
  REQUESTED_BY VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  DECIDED_BY VARCHAR(20) REFERENCES CPUSER (CODE),
  DECIDED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_AD_DAILY (
  ID SERIAL PRIMARY KEY,
  EVENT_CODE VARCHAR(20) NOT NULL REFERENCES T_EVENT (CODE) ON DELETE CASCADE,
  STAT_DATE DATE NOT NULL,
  IMPRESSIONS INT NOT NULL DEFAULT 0,
  CLICKS INT NOT NULL DEFAULT 0,
  COST DECIMAL(18,2) NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (EVENT_CODE, STAT_DATE)
);

CREATE TABLE IF NOT EXISTS T_PAYOUT (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  OWNER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  AMOUNT DECIMAL(18,2) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'READY' CHECK (STATUS IN ('READY', 'REQUESTED', 'PAID')),
  REQUESTED_AT TIMESTAMP,
  PAID_AT TIMESTAMP,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_PRODUCT (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  SELLER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  CATEGORY VARCHAR(100) NOT NULL,
  NAME VARCHAR(200) NOT NULL,
  PRICE DECIMAL(18,2) NOT NULL DEFAULT 0,
  STOCK INT NOT NULL DEFAULT 0,
  LOW_STOCK_THRESHOLD INT NOT NULL DEFAULT 5,
  RATING DECIMAL(3,2) NOT NULL DEFAULT 0,
  REVIEW_COUNT INT NOT NULL DEFAULT 0,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'REJECTED')),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_MERCH_ORDER (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  PRODUCT_CODE VARCHAR(20) NOT NULL REFERENCES T_PRODUCT (CODE),
  BUYER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  SELLER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  QTY INT NOT NULL,
  TOTAL_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'NEW' CHECK (STATUS IN ('NEW', 'PROCESSING', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'RETURNED')),
  ORDER_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
  SHIP_DEADLINE TIMESTAMP,
  SHIPPED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_COMPLAINT (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ORDER_CODE VARCHAR(20) NOT NULL REFERENCES T_MERCH_ORDER (CODE) ON DELETE CASCADE,
  BUYER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  MESSAGE VARCHAR(1000) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (STATUS IN ('OPEN', 'RESOLVED')),
  RESOLVED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_REVIEW (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ORDER_CODE VARCHAR(20) NOT NULL REFERENCES T_MERCH_ORDER (CODE) ON DELETE CASCADE,
  PRODUCT_CODE VARCHAR(20) NOT NULL REFERENCES T_PRODUCT (CODE),
  BUYER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  RATING INT NOT NULL CHECK (RATING BETWEEN 1 AND 5),
  COMMENT VARCHAR(500),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_ORGANIZER_BALANCE (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ORGANIZER_CODE VARCHAR(20) NOT NULL UNIQUE REFERENCES CPUSER (CODE),
  ESCROW_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  AVAILABLE_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_SELLER_BALANCE (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  SELLER_CODE VARCHAR(20) NOT NULL UNIQUE REFERENCES CPUSER (CODE),
  ESCROW_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  AVAILABLE_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS IX_T_EVENT_ORG_START ON T_EVENT (ORGANIZER_CODE, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_ORDER_EVENT_DATE ON T_ORDER (EVENT_CODE, ORDER_DATE);
CREATE INDEX IF NOT EXISTS IX_T_ORDER_STATUS ON T_ORDER (STATUS, ORDER_DATE);
CREATE INDEX IF NOT EXISTS IX_T_TICKET_ORDER ON T_TICKET (ORDER_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_T_REFUND_STATUS ON T_REFUND (STATUS, CREATED_AT);
CREATE INDEX IF NOT EXISTS IX_T_MO_SELLER_DATE ON T_MERCH_ORDER (SELLER_CODE, ORDER_DATE);
CREATE INDEX IF NOT EXISTS IX_T_MO_STATUS ON T_MERCH_ORDER (SELLER_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_T_PROD_SELLER ON T_PRODUCT (SELLER_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_T_CMPL_STATUS ON T_COMPLAINT (STATUS, CREATED_AT);
CREATE INDEX IF NOT EXISTS IX_T_AD_EVENT_DATE ON T_AD_DAILY (EVENT_CODE, STAT_DATE);

-- DISCOVERY module + menus (mirror of scripts/migrate7_discovery_menus.sql).
-- Placed AFTER the ADMIN grant above so these menus get ZERO grants.
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'DISCOVERY', 'Discovery', 3
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'DISCOVERY');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_HOME', 'DISCOVERY', 'Home', 'home', 'CHILD', 1, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_HOME');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_NEWS', 'DISCOVERY', 'News', 'news', 'CHILD', 2, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_NEWS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_EVENTS', 'DISCOVERY', 'Events', 'events', 'CHILD', 3, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_EVENTS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_PROMOTIONS', 'DISCOVERY', 'Promotions', 'promotions', 'CHILD', 5, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_PROMOTIONS');

-- EVENT module + menus (mirror of scripts/migrate10_event_menus.sql).
-- Placed AFTER the ADMIN grant above so these menus get ZERO grants.
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'EVENT', 'Event', 4
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'EVENT');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_MY_EVENTS', 'EVENT', 'My Events', 'my_events', 'CHILD', 1, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_MY_EVENTS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_TICKET_TYPES', 'EVENT', 'Ticket Types', 'ticket_types', 'CHILD', 3, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_TICKET_TYPES');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_ATTENDEES', 'EVENT', 'Attendees', 'attendees', 'CHILD', 4, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_ATTENDEES');

-- TICKETING module + menus (mirror of scripts/migrate13_ticketing_menus.sql).
-- Placed AFTER the ADMIN grant above so these menus get ZERO grants.
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'TICKETING', 'Ticketing', 5
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'TICKETING');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_CHECKOUT', 'TICKETING', 'Checkout', 'checkout', 'CHILD', 1, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_CHECKOUT');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_MY_TICKETS', 'TICKETING', 'My Tickets', 'my_tickets', 'CHILD', 2, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_MY_TICKETS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_REFUNDS', 'TICKETING', 'Refunds', 'refunds', 'CHILD', 3, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_REFUNDS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_SCAN_TICKET', 'TICKETING', 'Scan Ticket', 'scan_ticket', 'CHILD', 4, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SCAN_TICKET');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_SCAN_HISTORY', 'TICKETING', 'Scan History', 'scan_history', 'CHILD', 5, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SCAN_HISTORY');

-- DASHBOARD module + menus (ZERO grants to any role, by design).
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'DASHBOARD', 'Dashboard', 2
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'DASHBOARD');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_ORGANIZER', 'DASHBOARD', 'Organizer Dashboard', 'organizer_dashboard', 'CHILD', 1, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_ORGANIZER');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_SELLER', 'DASHBOARD', 'Seller Dashboard', 'seller_dashboard', 'CHILD', 2, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SELLER');

-- Discovery tables (prefix T_, mirror of scripts/migrate6_discovery.sql).
CREATE TABLE IF NOT EXISTS T_EVENT_CATEGORY (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  NAME VARCHAR(100) NOT NULL,
  SORT_ORDER INT NOT NULL DEFAULT 99,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_NEWS_CATEGORY (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  NAME VARCHAR(100) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_NEWS (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  TITLE VARCHAR(200) NOT NULL,
  SLUG VARCHAR(200) NOT NULL UNIQUE,
  SUMMARY VARCHAR(500),
  BODY TEXT NOT NULL,
  IMAGE_URL VARCHAR(500),
  NEWS_CATEGORY_CODE VARCHAR(20) NOT NULL REFERENCES T_NEWS_CATEGORY (CODE),
  EVENT_CATEGORY_CODE VARCHAR(20) REFERENCES T_EVENT_CATEGORY (CODE),
  EVENT_CODE VARCHAR(20) REFERENCES T_EVENT (CODE),
  STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (STATUS IN ('DRAFT', 'PUBLISHED')),
  PUBLISHED_AT TIMESTAMP,
  VIEW_COUNT INT NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_NEWS_VIEW (
  ID SERIAL PRIMARY KEY,
  NEWS_CODE VARCHAR(20) NOT NULL REFERENCES T_NEWS (CODE) ON DELETE CASCADE,
  VIEWER_HASH VARCHAR(64) NOT NULL,
  VIEWED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_AD_CAMPAIGN (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  TITLE VARCHAR(200) NOT NULL,
  IMAGE_URL VARCHAR(500),
  TARGET_URL VARCHAR(500),
  POSITION VARCHAR(20) NOT NULL DEFAULT 'HOME_BANNER' CHECK (POSITION IN ('HOME_BANNER', 'EVENT_LIST', 'SIDEBAR')),
  START_AT TIMESTAMP NOT NULL,
  END_AT TIMESTAMP NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'PAUSED', 'ENDED')),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_AD_EVENT (
  ID SERIAL PRIMARY KEY,
  CAMPAIGN_CODE VARCHAR(20) NOT NULL REFERENCES T_AD_CAMPAIGN (CODE) ON DELETE CASCADE,
  KIND VARCHAR(10) NOT NULL CHECK (KIND IN ('IMPRESSION', 'CLICK')),
  IP_HASH VARCHAR(64) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Discovery columns on existing T_ tables (no-op when already present).
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS EVENT_CATEGORY_CODE VARCHAR(20) REFERENCES T_EVENT_CATEGORY (CODE);
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS ADDRESS VARCHAR(300);
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS LATITUDE DECIMAL(10,7);
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS LONGITUDE DECIMAL(10,7);
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS POSTER_URL VARCHAR(500);
ALTER TABLE T_EVENT DROP CONSTRAINT IF EXISTS CK_T_EVENT_STATUS;
ALTER TABLE T_EVENT ADD CONSTRAINT CK_T_EVENT_STATUS
  CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'COMPLETED', 'ENDED', 'CANCELLED'));
ALTER TABLE T_TICKET_TYPE ADD COLUMN IF NOT EXISTS SALE_START_AT TIMESTAMP;
ALTER TABLE T_TICKET_TYPE ADD COLUMN IF NOT EXISTS SALE_END_AT TIMESTAMP;
ALTER TABLE T_PROMO ADD COLUMN IF NOT EXISTS DESCRIPTION VARCHAR(500);
ALTER TABLE T_PROMO ADD COLUMN IF NOT EXISTS MAX_DISCOUNT_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE T_PROMO ADD COLUMN IF NOT EXISTS MIN_PURCHASE DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE T_PROMO ADD COLUMN IF NOT EXISTS COVERAGE_CATEGORY_CODE VARCHAR(20) REFERENCES T_EVENT_CATEGORY (CODE);

CREATE INDEX IF NOT EXISTS IX_T_EVENT_PUBLIC ON T_EVENT (STATUS, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_EVENT_CITY ON T_EVENT (CITY_CODE, STATUS, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_EVENT_CAT ON T_EVENT (EVENT_CATEGORY_CODE, STATUS, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_NEWS_PUB ON T_NEWS (STATUS, PUBLISHED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_T_NEWS_CAT ON T_NEWS (NEWS_CATEGORY_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_T_NV_DEDUP ON T_NEWS_VIEW (NEWS_CODE, VIEWER_HASH, VIEWED_AT);
CREATE INDEX IF NOT EXISTS IX_T_AD_LIVE ON T_AD_CAMPAIGN (STATUS, START_AT, END_AT);
CREATE INDEX IF NOT EXISTS IX_T_AE_DEDUP ON T_AD_EVENT (CAMPAIGN_CODE, KIND, IP_HASH, CREATED_AT);
CREATE INDEX IF NOT EXISTS IX_T_TT_EVENT ON T_TICKET_TYPE (EVENT_CODE);

-- EVENT module columns (mirror of scripts/migrate9_event.sql).
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS SLUG VARCHAR(200);
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS TERMS TEXT;
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS CANCEL_REASON VARCHAR(500);
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE T_EVENT ADD COLUMN IF NOT EXISTS PUBLISHED_AT TIMESTAMP;
CREATE UNIQUE INDEX IF NOT EXISTS UQ_T_EVENT_SLUG ON T_EVENT (SLUG);
ALTER TABLE T_TICKET_TYPE ADD COLUMN IF NOT EXISTS DESCRIPTION VARCHAR(500);
ALTER TABLE T_TICKET_TYPE ADD COLUMN IF NOT EXISTS MAX_PER_PERSON INT;
ALTER TABLE T_TICKET_TYPE ADD COLUMN IF NOT EXISTS IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE T_TICKET_TYPE ADD COLUMN IF NOT EXISTS SORT_ORDER INT NOT NULL DEFAULT 99;
ALTER TABLE T_TICKET ADD COLUMN IF NOT EXISTS EMAIL VARCHAR(255);
ALTER TABLE T_TICKET ADD COLUMN IF NOT EXISTS PHONE VARCHAR(30);
CREATE INDEX IF NOT EXISTS IX_T_EVENT_MINE ON T_EVENT (ORGANIZER_CODE, IS_DELETED, STATUS, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_TT_EVENT_ACTIVE ON T_TICKET_TYPE (EVENT_CODE, IS_ACTIVE, SORT_ORDER);

-- TICKETING tables + columns (mirror of scripts/migrate12_ticketing.sql).
CREATE TABLE IF NOT EXISTS T_ORDER_ITEM (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ORDER_CODE VARCHAR(20) NOT NULL REFERENCES T_ORDER (CODE) ON DELETE CASCADE,
  TICKET_TYPE_CODE VARCHAR(20) NOT NULL REFERENCES T_TICKET_TYPE (CODE),
  TYPE_NAME VARCHAR(100) NOT NULL,
  UNIT_PRICE DECIMAL(18,2) NOT NULL DEFAULT 0,
  QTY INT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_STOCK_RESERVATION (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ORDER_CODE VARCHAR(20) NOT NULL REFERENCES T_ORDER (CODE) ON DELETE CASCADE,
  TICKET_TYPE_CODE VARCHAR(20) NOT NULL REFERENCES T_TICKET_TYPE (CODE),
  QTY INT NOT NULL,
  EXPIRES_AT TIMESTAMP NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (ORDER_CODE, TICKET_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS T_EVENT_OFFICER (
  EVENT_CODE VARCHAR(20) NOT NULL REFERENCES T_EVENT (CODE) ON DELETE CASCADE,
  OFFICER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE) ON DELETE CASCADE,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (EVENT_CODE, OFFICER_CODE)
);

CREATE TABLE IF NOT EXISTS T_SCAN_LOG (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  EVENT_CODE VARCHAR(20) NOT NULL REFERENCES T_EVENT (CODE),
  TICKET_CODE VARCHAR(20),
  OFFICER_CODE VARCHAR(20) NOT NULL REFERENCES CPUSER (CODE),
  RESULT VARCHAR(20) NOT NULL CHECK (RESULT IN ('VALID', 'USED', 'INVALID', 'WRONG_EVENT', 'UNPAID', 'REFUNDED', 'EXPIRED', 'OUTSIDE_SCHEDULE')),
  DETAIL VARCHAR(500),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE T_ORDER ADD COLUMN IF NOT EXISTS RESERVED_UNTIL TIMESTAMP;
ALTER TABLE T_ORDER DROP CONSTRAINT IF EXISTS CK_T_ORDER_STATUS;
ALTER TABLE T_ORDER ADD CONSTRAINT CK_T_ORDER_STATUS
  CHECK (STATUS IN ('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'EXPIRED'));
ALTER TABLE T_TICKET ADD COLUMN IF NOT EXISTS QR_TOKEN VARCHAR(512);
ALTER TABLE T_TICKET ADD COLUMN IF NOT EXISTS EMAIL VARCHAR(255);
ALTER TABLE T_TICKET ADD COLUMN IF NOT EXISTS PHONE VARCHAR(30);
ALTER TABLE T_REFUND ADD COLUMN IF NOT EXISTS TICKET_CODE VARCHAR(20) REFERENCES T_TICKET (CODE);
ALTER TABLE T_REFUND ADD COLUMN IF NOT EXISTS REJECT_NOTE VARCHAR(500);
ALTER TABLE T_REFUND ADD COLUMN IF NOT EXISTS PAYOUT_STATUS VARCHAR(20) NOT NULL DEFAULT 'NONE';
ALTER TABLE T_REFUND DROP CONSTRAINT IF EXISTS CK_T_RF_PAYOUT;
ALTER TABLE T_REFUND ADD CONSTRAINT CK_T_RF_PAYOUT
  CHECK (PAYOUT_STATUS IN ('NONE', 'PENDING_FINANCE', 'PAID'));
CREATE UNIQUE INDEX IF NOT EXISTS UQ_T_RF_ORDER_PENDING ON T_REFUND (ORDER_CODE) WHERE STATUS = 'PENDING';

CREATE INDEX IF NOT EXISTS IX_T_ORDER_BUYER ON T_ORDER (BUYER_CODE, STATUS, ORDER_DATE DESC);
CREATE INDEX IF NOT EXISTS IX_T_SR_EXPIRY ON T_STOCK_RESERVATION (TICKET_TYPE_CODE, EXPIRES_AT);
CREATE INDEX IF NOT EXISTS IX_T_SL_EVENT ON T_SCAN_LOG (EVENT_CODE, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_T_SL_OFFICER ON T_SCAN_LOG (OFFICER_CODE, CREATED_AT DESC);
