-- Skema PostgreSQL (fresh install). Relasi via CODE, tabel huruf besar prefix CP.
-- Jalankan sekali: psql -h localhost -U <user> -d <db> -f scripts/schema.postgres.sql
-- Env: DB_CONNECTION=postgres (+ DB_HOST/DB_PORT/DB_DATABASE/DB_USERNAME/DB_PASSWORD)

CREATE TABLE IF NOT EXISTS CPROLE (
  ID SERIAL PRIMARY KEY,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);
INSERT INTO CPROLE (CODE, NAME)
SELECT 'ADMIN', 'Administrator'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'ADMIN');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'USER', 'Pengguna'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'USER');

CREATE TABLE IF NOT EXISTS CPUSER (
  ID SERIAL PRIMARY KEY,
  CODE TEXT NOT NULL UNIQUE,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE_CODE TEXT NOT NULL DEFAULT 'USER' REFERENCES CPROLE (CODE),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS CPREFRESHTOKEN (
  ID SERIAL PRIMARY KEY,
  USER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE) ON DELETE CASCADE,
  TOKEN VARCHAR(512) NOT NULL UNIQUE,
  EXPIRES_AT TIMESTAMP NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS CPPERMISSION (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(40) NOT NULL UNIQUE,
  NAME VARCHAR(100) NOT NULL,
  PERMGROUP VARCHAR(40) NOT NULL,
  DESCRIPTION VARCHAR(255),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO CPPERMISSION (CODE, NAME, PERMGROUP, DESCRIPTION) VALUES
  ('MENU_USERS', 'Akses menu User Account', 'SYSTEM', 'Seluruh fungsi pengelolaan pengguna'),
  ('MENU_ROLES', 'Akses menu Role & Permission', 'SYSTEM', 'Seluruh fungsi pengelolaan role'),
  ('MENU_SESSIONS', 'Akses menu Sesi', 'SYSTEM', 'Seluruh fungsi pengelolaan sesi'),
  ('MENU_AUDIT', 'Akses menu Audit Log', 'SYSTEM', 'Seluruh fungsi audit log'),
  ('MENU_SECURITY', 'Akses menu Security Center', 'SYSTEM', 'Seluruh fungsi security center'),
  ('MENU_SYSLOG', 'Akses menu System Log', 'SYSTEM', 'Seluruh fungsi system log'),
  ('MENU_NOTIFICATIONS', 'Akses menu Notifikasi', 'SYSTEM', 'Seluruh fungsi notifikasi')
ON CONFLICT (CODE) DO UPDATE SET NAME=excluded.NAME, PERMGROUP=excluded.PERMGROUP, DESCRIPTION=excluded.DESCRIPTION;
-- MENU_DASHBOARD sengaja tidak ada: modul account dihapus, USER nol menu.

CREATE TABLE IF NOT EXISTS CPROLEPERMISSION (
  ROLE_CODE TEXT NOT NULL REFERENCES CPROLE (CODE) ON DELETE CASCADE,
  PERMISSION_CODE VARCHAR(40) NOT NULL REFERENCES CPPERMISSION (CODE) ON DELETE CASCADE,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (ROLE_CODE, PERMISSION_CODE)
);

INSERT INTO CPROLEPERMISSION (ROLE_CODE, PERMISSION_CODE)
SELECT 'ADMIN', CODE FROM CPPERMISSION
ON CONFLICT DO NOTHING;

-- USER tidak diberi menu apa pun (nol mapping); akses diberikan manual oleh admin.

-- CPMENU: registry menu. MCONTROL = nama folder modul (UPPERCASE),
-- wajib sama persis dengan folder frontend menus/<MCONTROL>/... .
CREATE TABLE IF NOT EXISTS CPMENU (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(40) NOT NULL UNIQUE,
  MCONTROL VARCHAR(40) NOT NULL,
  LABEL VARCHAR(100) NOT NULL,
  SORT_ORDER INT NOT NULL DEFAULT 99,
  PARENT_CODE VARCHAR(40) NULL REFERENCES CPMENU (CODE),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (MCONTROL, CODE)
);

INSERT INTO CPMENU (CODE, MCONTROL, LABEL, SORT_ORDER) VALUES
  ('MENU_USERS',         'SYSTEM', 'User Account',       1),
  ('MENU_ROLES',         'SYSTEM', 'Role & Permission',  2),
  ('MENU_SESSIONS',      'SYSTEM', 'Sesi & Auth',        3),
  ('MENU_AUDIT',         'SYSTEM', 'Audit Log',          4),
  ('MENU_SECURITY',      'SYSTEM', 'Security Center',    5),
  ('MENU_SYSLOG',        'SYSTEM', 'System Log',         6),
  ('MENU_NOTIFICATIONS', 'SYSTEM', 'Notifikasi',         7)
ON CONFLICT (CODE) DO NOTHING;

-- CPMATRIX: view matriks role x modul x menu (satu-satunya bacaan matriks).
-- Tulis tetap lewat CPROLEPERMISSION (tidak ada sinkron ganda).
CREATE OR REPLACE VIEW CPMATRIX AS
SELECT r.CODE AS ROLE_CODE, r.NAME AS ROLE_NAME,
       m.MCONTROL AS MODULE, m.CODE AS MENU_CODE, m.LABEL AS MENU_LABEL,
       m.SORT_ORDER, m.PARENT_CODE,
       CASE WHEN pm.ROLE_CODE IS NULL THEN 0 ELSE 1 END AS HAS_ACCESS
FROM CPROLE r
CROSS JOIN CPMENU m
LEFT JOIN CPROLEPERMISSION pm
  ON pm.ROLE_CODE = r.CODE AND pm.PERMISSION_CODE = m.CODE;

CREATE TABLE IF NOT EXISTS CPAUDITLOG (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  ACTOR_CODE VARCHAR(20),
  ACTION VARCHAR(60) NOT NULL,
  ENTITY VARCHAR(40) NOT NULL,
  ENTITY_CODE VARCHAR(60),
  DETAIL VARCHAR(1000),
  IP_ADDRESS VARCHAR(60),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTION ON CPAUDITLOG (ACTION, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTOR ON CPAUDITLOG (ACTOR_CODE, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPSYSLOG (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  LEVEL VARCHAR(10) NOT NULL,
  SOURCE VARCHAR(100) NOT NULL,
  MESSAGE VARCHAR(1000) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS IX_CPSYS_LEVEL ON CPSYSLOG (LEVEL, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPNOTIFTEMPLATE (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  NAME VARCHAR(100) NOT NULL,
  CHANNEL VARCHAR(10) NOT NULL,
  SUBJECT VARCHAR(200),
  BODY VARCHAR(4000) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY) VALUES
  ('NTPL-WELCOME', 'Selamat datang', 'EMAIL', 'Selamat datang di Go Core, {{nama}}!',
   'Halo {{nama}},

Akun Anda ({{kode}}) berhasil dibuat dengan role {{role}}.
Silakan login untuk mulai menggunakan aplikasi.

Salam,
Tim Go Core'),
  ('NTPL-RESET', 'Reset password', 'EMAIL', 'Permintaan reset password akun {{kode}}',
   'Halo {{nama}},

Kami menerima permintaan reset password untuk akun {{kode}}.
Abaikan pesan ini bila Anda tidak memintanya.

Salam,
Tim Go Core'),
  ('NTPL-ALERT', 'Peringatan keamanan', 'INAPP', 'Peringatan keamanan',
   'Aktivitas penting terdeteksi pada akun {{kode}}: {{detail}}')
ON CONFLICT (CODE) DO NOTHING;

CREATE TABLE IF NOT EXISTS CPNOTIFLOG (
  ID SERIAL PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL UNIQUE,
  TEMPLATE_CODE VARCHAR(20),
  CHANNEL VARCHAR(10) NOT NULL,
  RECIPIENT VARCHAR(255) NOT NULL,
  SUBJECT VARCHAR(200),
  BODY VARCHAR(4000) NOT NULL,
  STATUS VARCHAR(10) NOT NULL,
  ERROR VARCHAR(500),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);
