-- Skema SQLite (fresh install). Relasi via CODE, tabel huruf besar prefix CP.
-- Jalankan sekali (butuh sqlite3 CLI):
--   sqlite3 ./data/go-core.db < scripts/schema.sqlite.sql
-- Env: DB_CONNECTION=sqlite + DB_DATABASE=./data/go-core.db
-- Catatan: aktifkan foreign_keys bila akses manual:
--   PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS CPROLE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CPROLE (CODE, NAME)
SELECT 'ADMIN', 'Administrator'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'ADMIN');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'USER', 'Pengguna'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'USER');
-- Ticket-app roles (English only, zero menu grants by design).
INSERT INTO CPROLE (CODE, NAME)
SELECT 'AUDIENCE', 'Audience'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'AUDIENCE');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'ORGANIZER', 'Event Organizer'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'ORGANIZER');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'SELLER', 'Seller'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'SELLER');
INSERT INTO CPROLE (CODE, NAME)
SELECT 'OFFICER', 'Check-in Officer'
WHERE NOT EXISTS (SELECT 1 FROM CPROLE WHERE CODE = 'OFFICER');

CREATE TABLE IF NOT EXISTS CPUSER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  USERNAME TEXT NOT NULL UNIQUE,
  EMAIL TEXT NOT NULL UNIQUE,
  PASSWORD TEXT NOT NULL,
  ROLE_CODE TEXT NOT NULL DEFAULT 'USER' REFERENCES CPROLE (CODE),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CPREFRESHTOKEN (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE) ON DELETE CASCADE,
  TOKEN TEXT NOT NULL UNIQUE,
  EXPIRES_AT DATETIME NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- (CPPERMISSION sebagai tabel grant dibuat setelah CPMENU di bawah,
-- karena FK-nya menunjuk ke sana. Tidak ada tabel definisi terpisah:
-- definisi menu tinggal di CPMENU.)

-- CPMODULE: master modul. Satu baris = satu section sidebar + satu folder
-- di frontend/src/app/<MODULE>/. CPMENU.MODULE ber-FK ke sini (modul
-- dibuat dulu, baru menunya).
CREATE TABLE IF NOT EXISTS CPMODULE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  LABEL TEXT NOT NULL,
  SORT_ORDER INTEGER NOT NULL DEFAULT 99,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'SYSTEM', 'System', 1
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'SYSTEM');

-- CPMENU: registry menu. MODULE = kode modul (FK ke CPMODULE.CODE),
-- menentukan section sidebar level-1 (MODULE tampil sebagai section header).
-- MCONTROL = nama folder frontend (snake_case, mis. user_account): halaman
-- menu tinggal di frontend/src/app/<mcontrol>/index.jsx — datar, tanpa
-- folder modul perantara. NULL = menu PARENT (header buka-tutup di sidebar,
-- tanpa halaman/folder). Judul tampil = LABEL.
-- MENU_KIND: 'PARENT' = header buka-tutup (MCONTROL wajib NULL, tidak boleh
-- punya PARENT_CODE), 'CHILD' = item biasa (MCONTROL wajib unik, boleh punya
-- PARENT_CODE yang menunjuk menu PARENT se-modul, tanpa siklus).
CREATE TABLE IF NOT EXISTS CPMENU (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  MODULE TEXT NOT NULL REFERENCES CPMODULE (CODE),
  LABEL TEXT NOT NULL,
  MCONTROL TEXT UNIQUE,
  MENU_KIND TEXT NOT NULL DEFAULT 'CHILD' CHECK (MENU_KIND IN ('PARENT', 'CHILD')),
  SORT_ORDER INTEGER NOT NULL DEFAULT 99,
  PARENT_CODE TEXT REFERENCES CPMENU (CODE),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (MODULE, CODE),
  CHECK ((MENU_KIND = 'PARENT' AND MCONTROL IS NULL) OR (MENU_KIND = 'CHILD' AND MCONTROL IS NOT NULL))
);

-- Seed menu bawaan (urut sesuai sidebar).
-- MCONTROL snake_case = nama folder frontend/src/app/<mcontrol>/.
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_USERS', 'SYSTEM', 'User Account', 'users', 'CHILD', 1, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_USERS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_MODUL', 'SYSTEM', 'Modul & Menu', 'modul_menu', 'CHILD', 2, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_MODUL');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_ROLES', 'SYSTEM', 'Role & Permission', 'role_permission', 'CHILD', 3, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_ROLES');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_SESSIONS', 'SYSTEM', 'Sesi & Auth', 'sesi_auth', 'CHILD', 4, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SESSIONS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_AUDIT', 'SYSTEM', 'Audit Log', 'audit_log', 'CHILD', 5, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_AUDIT');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_SECURITY', 'SYSTEM', 'Security Center', 'security_center', 'CHILD', 6, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SECURITY');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_SYSLOG', 'SYSTEM', 'System Log', 'system_log', 'CHILD', 7, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SYSLOG');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_NOTIFICATIONS', 'SYSTEM', 'Notifikasi', 'notifikasi', 'CHILD', 8, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_NOTIFICATIONS');
-- Bersihkan sisa menu REPORT yang sudah dihapus (database lama).
DELETE FROM CPMENU WHERE CODE = 'MENU_ARUS_KAS';
DELETE FROM CPMENU WHERE CODE = 'MENU_LAPORAN';
DELETE FROM CPMENU WHERE CODE = 'MENU_KEUANGAN';
DELETE FROM CPMODULE WHERE CODE = 'REPORT';

-- CPPERMISSION: satu-satunya tabel relasi grant (ROLE_CODE -> MENU_CODE).
-- Definisi menu tinggal di CPMENU; tidak ada tabel definisi terpisah.
CREATE TABLE IF NOT EXISTS CPPERMISSION (
  ROLE_CODE TEXT NOT NULL REFERENCES CPROLE (CODE) ON DELETE CASCADE,
  MENU_CODE TEXT NOT NULL REFERENCES CPMENU (CODE) ON DELETE CASCADE,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ROLE_CODE, MENU_CODE)
);
-- ADMIN mendapat semua menu CHILD.
-- Menu PARENT tidak pernah di-grant: header buka-tutup tanpa halaman sendiri,
-- aksesnya menyusul otomatis dari menu CHILD di bawahnya.
-- USER nol mapping (manual via UI).
INSERT INTO CPPERMISSION (ROLE_CODE, MENU_CODE)
SELECT 'ADMIN', CODE FROM CPMENU
WHERE MENU_KIND = 'CHILD'
AND NOT EXISTS (
  SELECT 1 FROM CPPERMISSION x WHERE x.ROLE_CODE = 'ADMIN' AND x.MENU_CODE = CPMENU.CODE
);
-- Bersihkan grant PARENT sisa database lama (matriks kini hanya mencentang CHILD).
DELETE FROM CPPERMISSION
WHERE MENU_CODE IN (SELECT CODE FROM CPMENU WHERE MENU_KIND = 'PARENT');
-- Bersihkan sisa grant REPORT yang sudah dihapus (database lama).
DELETE FROM CPPERMISSION WHERE MENU_CODE IN ('MENU_LAPORAN', 'MENU_ARUS_KAS', 'MENU_KEUANGAN');

-- Matriks role x modul x menu dibaca via JOIN (CPROLE x CPMENU LEFT JOIN
-- CPPERMISSION); tulis grant tetap ke CPPERMISSION (tidak ada sinkron ganda).
-- Catatan: dulu master modul bernama CPMATRIX, sekarang CPMODULE (lihat di
-- atas). Tidak ada view yang perlu di-drop.

CREATE TABLE IF NOT EXISTS CPAUDITLOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ACTOR_CODE TEXT,
  ACTION TEXT NOT NULL,
  ENTITY TEXT NOT NULL,
  ENTITY_CODE TEXT,
  DETAIL TEXT,
  IP_ADDRESS TEXT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTION ON CPAUDITLOG (ACTION, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_CPAUDIT_ACTOR ON CPAUDITLOG (ACTOR_CODE, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPSYSLOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  LEVEL TEXT NOT NULL,
  SOURCE TEXT NOT NULL,
  MESSAGE TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_CPSYS_LEVEL ON CPSYSLOG (LEVEL, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS CPNOTIFTEMPLATE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CHANNEL TEXT NOT NULL,
  SUBJECT TEXT,
  BODY TEXT NOT NULL,
  IS_ACTIVE INTEGER NOT NULL DEFAULT 1,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
SELECT 'NTPL-WELCOME', 'Selamat datang', 'EMAIL', 'Selamat datang di Go Core, {{nama}}!',
'Halo {{nama}},

Akun Anda ({{kode}}) berhasil dibuat dengan role {{role}}.
Silakan login untuk mulai menggunakan aplikasi.

Salam,
Tim Go Core'
WHERE NOT EXISTS (SELECT 1 FROM CPNOTIFTEMPLATE WHERE CODE = 'NTPL-WELCOME');
INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
SELECT 'NTPL-RESET', 'Reset password', 'EMAIL', 'Permintaan reset password akun {{kode}}',
'Halo {{nama}},

Kami menerima permintaan reset password untuk akun {{kode}}.
Abaikan pesan ini bila Anda tidak memintanya.

Salam,
Tim Go Core'
WHERE NOT EXISTS (SELECT 1 FROM CPNOTIFTEMPLATE WHERE CODE = 'NTPL-RESET');
INSERT INTO CPNOTIFTEMPLATE (CODE, NAME, CHANNEL, SUBJECT, BODY)
SELECT 'NTPL-ALERT', 'Peringatan keamanan', 'INAPP', 'Peringatan keamanan',
'Aktivitas penting terdeteksi pada akun {{kode}}: {{detail}}'
WHERE NOT EXISTS (SELECT 1 FROM CPNOTIFTEMPLATE WHERE CODE = 'NTPL-ALERT');

CREATE TABLE IF NOT EXISTS CPNOTIFLOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  TEMPLATE_CODE TEXT,
  CHANNEL TEXT NOT NULL,
  RECIPIENT TEXT NOT NULL,
  SUBJECT TEXT,
  BODY TEXT NOT NULL,
  STATUS TEXT NOT NULL,
  ERROR TEXT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed starter accounts (password = username + "123", bcrypt).
-- admin/admin123 (ADMIN) + audience/audience123 (AUDIENCE) +
-- organizer/organizer123 (ORGANIZER) + seller/seller123 (SELLER) +
-- officer/officer123 (OFFICER), plus legacy user/user (USER).
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-ADMIN', 'admin', 'admin@ticket.app',
  '$2a$10$pPedrlyKaNDNl.uZMHK.F.jSkchAcyDcz2kgU1qOQKmLXO/KECB3.', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'admin');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-AUDIENCE', 'audience', 'audience@ticket.app',
  '$2a$10$IZUzHE4snobTnbmKwb.lQ.APsOKdWvYpfermkIwtcMxiPMUUruTnW', 'AUDIENCE'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'audience');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-ORGANIZER', 'organizer', 'organizer@ticket.app',
  '$2a$10$HFQR9/SSJPcvsDX4HXMXKuvnYz9DV/JTelLL4bc/Decxehdj1d3b6', 'ORGANIZER'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'organizer');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-SELLER', 'seller', 'seller@ticket.app',
  '$2a$10$sZLQKWkONHQ4muRlWVZeqeO8gYIpvBepQuEPy6DHDxA1WpoWMDpre', 'SELLER'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'seller');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-OFFICER', 'officer', 'officer@ticket.app',
  '$2a$10$nHVgbB3.h39bb4k4yJbBmuzN6Ddmsqhi9t0LXuOOHAtMXTPyWLFde', 'OFFICER'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'officer');
INSERT INTO CPUSER (CODE, USERNAME, EMAIL, PASSWORD, ROLE_CODE)
SELECT 'USR-USER0001', 'user', 'user@example.com',
  '$2a$10$MpKcDZmTSotcNefe53ODl.3frNUr0E/fuU/cpAKPglu85tG0Niyr6', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM CPUSER WHERE USERNAME = 'user');

-- Dashboard tables (prefix T_, mirror of scripts/migrate5_dashboard.sql).
-- Placed AFTER the ADMIN grant above so dashboard menus get ZERO grants.
CREATE TABLE IF NOT EXISTS T_CITY (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_EVENT (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ORGANIZER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  CITY_CODE TEXT REFERENCES T_CITY (CODE),
  TITLE TEXT NOT NULL,
  DESCRIPTION TEXT,
  VENUE TEXT,
  START_AT DATETIME NOT NULL,
  END_AT DATETIME,
  STATUS TEXT NOT NULL DEFAULT 'PUBLISHED' CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'COMPLETED', 'CANCELLED')),
  PLATFORM_FEE_PERCENT REAL NOT NULL DEFAULT 10.00,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_TICKET_TYPE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  EVENT_CODE TEXT NOT NULL REFERENCES T_EVENT (CODE) ON DELETE CASCADE,
  NAME TEXT NOT NULL,
  PRICE REAL NOT NULL DEFAULT 0,
  QUOTA INTEGER NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_PROMO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  EVENT_CODE TEXT REFERENCES T_EVENT (CODE) ON DELETE CASCADE,
  PROMO_CODE TEXT NOT NULL UNIQUE,
  DISCOUNT_PERCENT REAL NOT NULL DEFAULT 0,
  DISCOUNT_AMOUNT REAL NOT NULL DEFAULT 0,
  MAX_USES INTEGER,
  USED_COUNT INTEGER NOT NULL DEFAULT 0,
  VALID_FROM DATETIME NOT NULL,
  VALID_TO DATETIME NOT NULL,
  STATUS TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'EXPIRED', 'DISABLED')),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_ORDER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  EVENT_CODE TEXT NOT NULL REFERENCES T_EVENT (CODE),
  BUYER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  TICKET_TYPE_CODE TEXT NOT NULL REFERENCES T_TICKET_TYPE (CODE),
  QTY INTEGER NOT NULL,
  GROSS_AMOUNT REAL NOT NULL DEFAULT 0,
  DISCOUNT_AMOUNT REAL NOT NULL DEFAULT 0,
  PLATFORM_FEE REAL NOT NULL DEFAULT 0,
  NET_AMOUNT REAL NOT NULL DEFAULT 0,
  PROMO_CODE TEXT,
  STATUS TEXT NOT NULL DEFAULT 'PAID' CHECK (STATUS IN ('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'EXPIRED')),
  ORDER_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_TICKET (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ORDER_CODE TEXT NOT NULL REFERENCES T_ORDER (CODE) ON DELETE CASCADE,
  QR_CODE TEXT NOT NULL UNIQUE,
  HOLDER_NAME TEXT,
  STATUS TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'USED', 'REFUNDED')),
  CHECKED_IN_AT DATETIME,
  CHECKED_IN_BY TEXT REFERENCES CPUSER (CODE),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_REFUND (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ORDER_CODE TEXT NOT NULL REFERENCES T_ORDER (CODE),
  AMOUNT REAL NOT NULL,
  REASON TEXT,
  STATUS TEXT NOT NULL DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
  REQUESTED_BY TEXT NOT NULL REFERENCES CPUSER (CODE),
  DECIDED_BY TEXT REFERENCES CPUSER (CODE),
  DECIDED_AT DATETIME,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_AD_DAILY (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EVENT_CODE TEXT NOT NULL REFERENCES T_EVENT (CODE) ON DELETE CASCADE,
  STAT_DATE DATE NOT NULL,
  IMPRESSIONS INTEGER NOT NULL DEFAULT 0,
  CLICKS INTEGER NOT NULL DEFAULT 0,
  COST REAL NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (EVENT_CODE, STAT_DATE)
);

CREATE TABLE IF NOT EXISTS T_PAYOUT (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  OWNER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  AMOUNT REAL NOT NULL,
  STATUS TEXT NOT NULL DEFAULT 'READY' CHECK (STATUS IN ('READY', 'REQUESTED', 'PAID')),
  REQUESTED_AT DATETIME,
  PAID_AT DATETIME,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_PRODUCT (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  SELLER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  CATEGORY TEXT NOT NULL,
  NAME TEXT NOT NULL,
  PRICE REAL NOT NULL DEFAULT 0,
  STOCK INTEGER NOT NULL DEFAULT 0,
  LOW_STOCK_THRESHOLD INTEGER NOT NULL DEFAULT 5,
  RATING REAL NOT NULL DEFAULT 0,
  REVIEW_COUNT INTEGER NOT NULL DEFAULT 0,
  STATUS TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'REJECTED')),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_MERCH_ORDER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  PRODUCT_CODE TEXT NOT NULL REFERENCES T_PRODUCT (CODE),
  BUYER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  SELLER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  QTY INTEGER NOT NULL,
  TOTAL_AMOUNT REAL NOT NULL DEFAULT 0,
  STATUS TEXT NOT NULL DEFAULT 'NEW' CHECK (STATUS IN ('NEW', 'PROCESSING', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'RETURNED')),
  ORDER_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SHIP_DEADLINE DATETIME,
  SHIPPED_AT DATETIME,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_COMPLAINT (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ORDER_CODE TEXT NOT NULL REFERENCES T_MERCH_ORDER (CODE) ON DELETE CASCADE,
  BUYER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  MESSAGE TEXT NOT NULL,
  STATUS TEXT NOT NULL DEFAULT 'OPEN' CHECK (STATUS IN ('OPEN', 'RESOLVED')),
  RESOLVED_AT DATETIME,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_REVIEW (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ORDER_CODE TEXT NOT NULL REFERENCES T_MERCH_ORDER (CODE) ON DELETE CASCADE,
  PRODUCT_CODE TEXT NOT NULL REFERENCES T_PRODUCT (CODE),
  BUYER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  RATING INTEGER NOT NULL CHECK (RATING BETWEEN 1 AND 5),
  COMMENT TEXT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_ORGANIZER_BALANCE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ORGANIZER_CODE TEXT NOT NULL UNIQUE REFERENCES CPUSER (CODE),
  ESCROW_AMOUNT REAL NOT NULL DEFAULT 0,
  AVAILABLE_AMOUNT REAL NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_SELLER_BALANCE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  SELLER_CODE TEXT NOT NULL UNIQUE REFERENCES CPUSER (CODE),
  ESCROW_AMOUNT REAL NOT NULL DEFAULT 0,
  AVAILABLE_AMOUNT REAL NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_T_EVENT_ORG_START ON T_EVENT (ORGANIZER_CODE, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_ORDER_EVENT_DATE ON T_ORDER (EVENT_CODE, ORDER_DATE);
CREATE INDEX IF NOT EXISTS IX_T_ORDER_STATUS ON T_ORDER (STATUS, ORDER_DATE);
CREATE INDEX IF NOT EXISTS IX_T_TICKET_ORDER ON T_TICKET (ORDER_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_T_REFUND_STATUS ON T_REFUND (STATUS, CREATED_AT);
CREATE INDEX IF NOT EXISTS IX_T_MO_SELLER_DATE ON T_MERCH_ORDER (SELLER_CODE, ORDER_DATE);
CREATE INDEX IF NOT EXISTS IX_T_MO_STATUS ON T_MERCH_ORDER (SELLER_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_T_PROD_SELLER ON T_PRODUCT (SELLER_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_T_CMPL_STATUS ON T_COMPLAINT (STATUS, CREATED_AT);
CREATE INDEX IF NOT EXISTS IX_T_AD_EVENT_DATE ON T_AD_DAILY (EVENT_CODE, STAT_DATE);

-- DISCOVERY module + menus (mirror of scripts/migrate7_discovery_menus.sql).
-- Placed AFTER the ADMIN grant above so these menus get ZERO grants.
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'DISCOVERY', 'Discovery', 3
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'DISCOVERY');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_HOME', 'DISCOVERY', 'Home', 'home', 'CHILD', 1, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_HOME');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_NEWS', 'DISCOVERY', 'News', 'news', 'CHILD', 2, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_NEWS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_EVENTS', 'DISCOVERY', 'Events', 'events', 'CHILD', 3, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_EVENTS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_PROMOTIONS', 'DISCOVERY', 'Promotions', 'promotions', 'CHILD', 5, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_PROMOTIONS');

-- EVENT module + menus (mirror of scripts/migrate10_event_menus.sql).
-- Placed AFTER the ADMIN grant above so these menus get ZERO grants.
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'EVENT', 'Event', 4
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'EVENT');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_MY_EVENTS', 'EVENT', 'My Events', 'my_events', 'CHILD', 1, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_MY_EVENTS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_TICKET_TYPES', 'EVENT', 'Ticket Types', 'ticket_types', 'CHILD', 3, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_TICKET_TYPES');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_ATTENDEES', 'EVENT', 'Attendees', 'attendees', 'CHILD', 4, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_ATTENDEES');

-- TICKETING module + menus (mirror of scripts/migrate13_ticketing_menus.sql).
-- Placed AFTER the ADMIN grant above so these menus get ZERO grants.
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'TICKETING', 'Ticketing', 5
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'TICKETING');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_CHECKOUT', 'TICKETING', 'Checkout', 'checkout', 'CHILD', 1, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_CHECKOUT');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_MY_TICKETS', 'TICKETING', 'My Tickets', 'my_tickets', 'CHILD', 2, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_MY_TICKETS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_REFUNDS', 'TICKETING', 'Refunds', 'refunds', 'CHILD', 3, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_REFUNDS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_SCAN_TICKET', 'TICKETING', 'Scan Ticket', 'scan_ticket', 'CHILD', 4, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SCAN_TICKET');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_SCAN_HISTORY', 'TICKETING', 'Scan History', 'scan_history', 'CHILD', 5, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SCAN_HISTORY');

-- DASHBOARD module + menus (ZERO grants to any role, by design).
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'DASHBOARD', 'Dashboard', 2
WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'DASHBOARD');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_ORGANIZER', 'DASHBOARD', 'Organizer Dashboard', 'organizer_dashboard', 'CHILD', 1, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_ORGANIZER');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_SELLER', 'DASHBOARD', 'Seller Dashboard', 'seller_dashboard', 'CHILD', 2, NULL
WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_SELLER');

-- Discovery tables (prefix T_, mirror of scripts/migrate6_discovery.sql).
CREATE TABLE IF NOT EXISTS T_EVENT_CATEGORY (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  SORT_ORDER INTEGER NOT NULL DEFAULT 99,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_NEWS_CATEGORY (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_NEWS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  TITLE TEXT NOT NULL,
  SLUG TEXT NOT NULL UNIQUE,
  SUMMARY TEXT,
  BODY TEXT NOT NULL,
  IMAGE_URL TEXT,
  NEWS_CATEGORY_CODE TEXT NOT NULL REFERENCES T_NEWS_CATEGORY (CODE),
  EVENT_CATEGORY_CODE TEXT REFERENCES T_EVENT_CATEGORY (CODE),
  EVENT_CODE TEXT REFERENCES T_EVENT (CODE),
  STATUS TEXT NOT NULL DEFAULT 'DRAFT' CHECK (STATUS IN ('DRAFT', 'PUBLISHED')),
  PUBLISHED_AT DATETIME,
  VIEW_COUNT INTEGER NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_NEWS_VIEW (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NEWS_CODE TEXT NOT NULL REFERENCES T_NEWS (CODE) ON DELETE CASCADE,
  VIEWER_HASH TEXT NOT NULL,
  VIEWED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_AD_CAMPAIGN (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  TITLE TEXT NOT NULL,
  IMAGE_URL TEXT,
  TARGET_URL TEXT,
  POSITION TEXT NOT NULL DEFAULT 'HOME_BANNER' CHECK (POSITION IN ('HOME_BANNER', 'EVENT_LIST', 'SIDEBAR')),
  START_AT DATETIME NOT NULL,
  END_AT DATETIME NOT NULL,
  STATUS TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'PAUSED', 'ENDED')),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_AD_EVENT (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CAMPAIGN_CODE TEXT NOT NULL REFERENCES T_AD_CAMPAIGN (CODE) ON DELETE CASCADE,
  KIND TEXT NOT NULL CHECK (KIND IN ('IMPRESSION', 'CLICK')),
  IP_HASH TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Discovery columns on existing T_ tables (SQLite ADD COLUMN is limited;
-- FK clauses omitted here, base tables already constrain via app logic).
-- NOTE: re-running is safe (each ALTER guarded by syntax that fails
-- silently only when the column exists - run once per fresh install).
ALTER TABLE T_EVENT ADD COLUMN EVENT_CATEGORY_CODE TEXT;
ALTER TABLE T_EVENT ADD COLUMN ADDRESS TEXT;
ALTER TABLE T_EVENT ADD COLUMN LATITUDE REAL;
ALTER TABLE T_EVENT ADD COLUMN LONGITUDE REAL;
ALTER TABLE T_EVENT ADD COLUMN POSTER_URL TEXT;
ALTER TABLE T_TICKET_TYPE ADD COLUMN SALE_START_AT DATETIME;
ALTER TABLE T_TICKET_TYPE ADD COLUMN SALE_END_AT DATETIME;
ALTER TABLE T_PROMO ADD COLUMN DESCRIPTION TEXT;
ALTER TABLE T_PROMO ADD COLUMN MAX_DISCOUNT_AMOUNT REAL NOT NULL DEFAULT 0;
ALTER TABLE T_PROMO ADD COLUMN MIN_PURCHASE REAL NOT NULL DEFAULT 0;
ALTER TABLE T_PROMO ADD COLUMN COVERAGE_CATEGORY_CODE TEXT;

CREATE INDEX IF NOT EXISTS IX_T_EVENT_PUBLIC ON T_EVENT (STATUS, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_EVENT_CITY ON T_EVENT (CITY_CODE, STATUS, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_EVENT_CAT ON T_EVENT (EVENT_CATEGORY_CODE, STATUS, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_NEWS_PUB ON T_NEWS (STATUS, PUBLISHED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_T_NEWS_CAT ON T_NEWS (NEWS_CATEGORY_CODE, STATUS);
CREATE INDEX IF NOT EXISTS IX_T_NV_DEDUP ON T_NEWS_VIEW (NEWS_CODE, VIEWER_HASH, VIEWED_AT);
CREATE INDEX IF NOT EXISTS IX_T_AD_LIVE ON T_AD_CAMPAIGN (STATUS, START_AT, END_AT);
CREATE INDEX IF NOT EXISTS IX_T_AE_DEDUP ON T_AD_EVENT (CAMPAIGN_CODE, KIND, IP_HASH, CREATED_AT);
CREATE INDEX IF NOT EXISTS IX_T_TT_EVENT ON T_TICKET_TYPE (EVENT_CODE);

-- EVENT module columns (mirror of scripts/migrate9_event.sql).
-- NOTE: fresh-install only (SQLite ALTER has no IF NOT EXISTS guard).
ALTER TABLE T_EVENT ADD COLUMN SLUG TEXT;
ALTER TABLE T_EVENT ADD COLUMN TERMS TEXT;
ALTER TABLE T_EVENT ADD COLUMN CANCEL_REASON TEXT;
ALTER TABLE T_EVENT ADD COLUMN IS_DELETED INTEGER NOT NULL DEFAULT 0;
ALTER TABLE T_EVENT ADD COLUMN PUBLISHED_AT DATETIME;
CREATE UNIQUE INDEX IF NOT EXISTS UQ_T_EVENT_SLUG ON T_EVENT (SLUG);
ALTER TABLE T_TICKET_TYPE ADD COLUMN DESCRIPTION TEXT;
ALTER TABLE T_TICKET_TYPE ADD COLUMN MAX_PER_PERSON INTEGER;
ALTER TABLE T_TICKET_TYPE ADD COLUMN IS_ACTIVE INTEGER NOT NULL DEFAULT 1;
ALTER TABLE T_TICKET_TYPE ADD COLUMN SORT_ORDER INTEGER NOT NULL DEFAULT 99;
ALTER TABLE T_TICKET ADD COLUMN EMAIL TEXT;
ALTER TABLE T_TICKET ADD COLUMN PHONE TEXT;
CREATE INDEX IF NOT EXISTS IX_T_EVENT_MINE ON T_EVENT (ORGANIZER_CODE, IS_DELETED, STATUS, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_TT_EVENT_ACTIVE ON T_TICKET_TYPE (EVENT_CODE, IS_ACTIVE, SORT_ORDER);

-- TICKETING tables + columns (mirror of scripts/migrate12_ticketing.sql).
-- NOTE: fresh-install only (SQLite ALTER has no IF NOT EXISTS guard).
CREATE TABLE IF NOT EXISTS T_ORDER_ITEM (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ORDER_CODE TEXT NOT NULL REFERENCES T_ORDER (CODE) ON DELETE CASCADE,
  TICKET_TYPE_CODE TEXT NOT NULL REFERENCES T_TICKET_TYPE (CODE),
  TYPE_NAME TEXT NOT NULL,
  UNIT_PRICE REAL NOT NULL DEFAULT 0,
  QTY INTEGER NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_STOCK_RESERVATION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  ORDER_CODE TEXT NOT NULL REFERENCES T_ORDER (CODE) ON DELETE CASCADE,
  TICKET_TYPE_CODE TEXT NOT NULL REFERENCES T_TICKET_TYPE (CODE),
  QTY INTEGER NOT NULL,
  EXPIRES_AT DATETIME NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (ORDER_CODE, TICKET_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS T_EVENT_OFFICER (
  EVENT_CODE TEXT NOT NULL REFERENCES T_EVENT (CODE) ON DELETE CASCADE,
  OFFICER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE) ON DELETE CASCADE,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (EVENT_CODE, OFFICER_CODE)
);

CREATE TABLE IF NOT EXISTS T_SCAN_LOG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  TICKET_CODE TEXT,
  EVENT_CODE TEXT NOT NULL REFERENCES T_EVENT (CODE),
  OFFICER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  RESULT TEXT NOT NULL CHECK (RESULT IN ('VALID', 'USED', 'INVALID', 'WRONG_EVENT', 'UNPAID', 'REFUNDED', 'EXPIRED', 'OUTSIDE_SCHEDULE')),
  DETAIL TEXT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE T_ORDER ADD COLUMN RESERVED_UNTIL DATETIME;
ALTER TABLE T_TICKET ADD COLUMN QR_TOKEN TEXT;
ALTER TABLE T_REFUND ADD COLUMN TICKET_CODE TEXT REFERENCES T_TICKET (CODE);
ALTER TABLE T_REFUND ADD COLUMN REJECT_NOTE TEXT;
ALTER TABLE T_REFUND ADD COLUMN PAYOUT_STATUS TEXT NOT NULL DEFAULT 'NONE';
CREATE UNIQUE INDEX IF NOT EXISTS UQ_T_RF_ORDER_PENDING ON T_REFUND (ORDER_CODE) WHERE STATUS = 'PENDING';

CREATE INDEX IF NOT EXISTS IX_T_ORDER_BUYER ON T_ORDER (BUYER_CODE, STATUS, ORDER_DATE DESC);
CREATE INDEX IF NOT EXISTS IX_T_SR_EXPIRY ON T_STOCK_RESERVATION (TICKET_TYPE_CODE, EXPIRES_AT);
CREATE INDEX IF NOT EXISTS IX_T_SL_EVENT ON T_SCAN_LOG (EVENT_CODE, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_T_SL_OFFICER ON T_SCAN_LOG (OFFICER_CODE, CREATED_AT DESC);

-- MARKETING module (mirror of scripts/migrate14_marketing.sql, fresh install + idempotent).
-- SQLite has no ADD COLUMN IF NOT EXISTS guard per version: fresh-install path
-- creates tables with final shape; ALTERs below are best-effort for upgrades.
CREATE TABLE IF NOT EXISTS T_PROMO_SCOPE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  PROMO_CODE TEXT NOT NULL REFERENCES T_PROMO (CODE) ON DELETE CASCADE,
  SCOPE_TYPE TEXT NOT NULL CHECK (SCOPE_TYPE IN ('CATEGORY', 'EVENT')),
  CATEGORY_CODE TEXT REFERENCES T_EVENT_CATEGORY (CODE),
  EVENT_CODE TEXT REFERENCES T_EVENT (CODE),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_T_PSC_PROMO ON T_PROMO_SCOPE (PROMO_CODE);
CREATE TABLE IF NOT EXISTS T_PROMO_USAGE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  PROMO_CODE TEXT NOT NULL REFERENCES T_PROMO (CODE) ON DELETE CASCADE,
  ORDER_CODE TEXT NOT NULL REFERENCES T_ORDER (CODE) ON DELETE CASCADE,
  USER_CODE TEXT NOT NULL REFERENCES CPUSER (CODE),
  DISCOUNT_AMOUNT REAL NOT NULL DEFAULT 0,
  USED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_T_PU_PROMO ON T_PROMO_USAGE (PROMO_CODE);
CREATE INDEX IF NOT EXISTS IX_T_PU_USER ON T_PROMO_USAGE (USER_CODE, PROMO_CODE);
CREATE INDEX IF NOT EXISTS IX_T_PU_ORDER ON T_PROMO_USAGE (ORDER_CODE);
CREATE TABLE IF NOT EXISTS T_AD_POSITION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE TEXT NOT NULL UNIQUE,
  NAME TEXT NOT NULL,
  PRICE_PER_DAY REAL NOT NULL DEFAULT 0,
  SORT_ORDER INTEGER NOT NULL DEFAULT 99,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO T_AD_POSITION (CODE, NAME, PRICE_PER_DAY, SORT_ORDER)
SELECT 'HOME_BANNER', 'Banner Home', 150000, 1 WHERE NOT EXISTS (SELECT 1 FROM T_AD_POSITION WHERE CODE = 'HOME_BANNER');
INSERT INTO T_AD_POSITION (CODE, NAME, PRICE_PER_DAY, SORT_ORDER)
SELECT 'EVENT_LIST', 'Event List', 80000, 2 WHERE NOT EXISTS (SELECT 1 FROM T_AD_POSITION WHERE CODE = 'EVENT_LIST');
INSERT INTO T_AD_POSITION (CODE, NAME, PRICE_PER_DAY, SORT_ORDER)
SELECT 'SIDEBAR', 'Sidebar', 100000, 3 WHERE NOT EXISTS (SELECT 1 FROM T_AD_POSITION WHERE CODE = 'SIDEBAR');
CREATE TABLE IF NOT EXISTS T_AD_STAT_DAILY (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CAMPAIGN_CODE TEXT NOT NULL REFERENCES T_AD_CAMPAIGN (CODE) ON DELETE CASCADE,
  STAT_DATE DATE NOT NULL,
  IMPRESSIONS INTEGER NOT NULL DEFAULT 0,
  CLICKS INTEGER NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (CAMPAIGN_CODE, STAT_DATE)
);
CREATE INDEX IF NOT EXISTS IX_T_ASD_CAMP ON T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE);
ALTER TABLE T_PROMO ADD COLUMN ORGANIZER_CODE TEXT REFERENCES CPUSER (CODE);
ALTER TABLE T_PROMO ADD COLUMN SCOPE_TYPE TEXT NOT NULL DEFAULT 'ALL';
ALTER TABLE T_PROMO ADD COLUMN MAX_PER_USER INTEGER;
ALTER TABLE T_AD_CAMPAIGN ADD COLUMN ORGANIZER_CODE TEXT REFERENCES CPUSER (CODE);
ALTER TABLE T_AD_CAMPAIGN ADD COLUMN COST REAL NOT NULL DEFAULT 0;
ALTER TABLE T_AD_CAMPAIGN ADD COLUMN PAYMENT_STATUS TEXT NOT NULL DEFAULT 'UNPAID';
ALTER TABLE T_AD_CAMPAIGN ADD COLUMN APPROVAL_STATUS TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE T_AD_CAMPAIGN ADD COLUMN REJECT_NOTE TEXT;
ALTER TABLE T_NEWS ADD COLUMN AUTHOR_CODE TEXT REFERENCES CPUSER (CODE);
ALTER TABLE T_NEWS ADD COLUMN SCHEDULED_AT DATETIME;
ALTER TABLE T_NEWS ADD COLUMN IS_DELETED INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS IX_T_PROMO_ORG ON T_PROMO (ORGANIZER_CODE, STATUS, VALID_TO);
CREATE INDEX IF NOT EXISTS IX_T_ADC_ORG ON T_AD_CAMPAIGN (ORGANIZER_CODE, STATUS, START_AT);
CREATE INDEX IF NOT EXISTS IX_T_NEWS_AUTHOR ON T_NEWS (AUTHOR_CODE, STATUS, PUBLISHED_AT DESC);
CREATE INDEX IF NOT EXISTS IX_T_NEWS_SCHED ON T_NEWS (STATUS, SCHEDULED_AT);
INSERT INTO CPMODULE (CODE, LABEL, SORT_ORDER)
SELECT 'MARKETING', 'Marketing', 6 WHERE NOT EXISTS (SELECT 1 FROM CPMODULE WHERE CODE = 'MARKETING');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_PROMO_CODES', 'MARKETING', 'Promo Codes', 'promo_codes', 'CHILD', 1, NULL WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_PROMO_CODES');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_AD_CAMPAIGNS', 'MARKETING', 'Ad Campaigns', 'ad_campaigns', 'CHILD', 2, NULL WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_AD_CAMPAIGNS');
INSERT INTO CPMENU (CODE, MODULE, LABEL, MCONTROL, MENU_KIND, SORT_ORDER, PARENT_CODE)
SELECT 'MENU_NEWS_MANAGEMENT', 'MARKETING', 'News Management', 'news_management', 'CHILD', 3, NULL WHERE NOT EXISTS (SELECT 1 FROM CPMENU WHERE CODE = 'MENU_NEWS_MANAGEMENT');
DELETE FROM CPPERMISSION WHERE MENU_CODE IN ('MENU_PROMO_CODES', 'MENU_AD_CAMPAIGNS', 'MENU_NEWS_MANAGEMENT');
