-- Demo seed for DISCOVERY tables (categories, cities, events, news, promos, ads).
-- ONLY touches T_* tables. Uses accounts USR-ORGANIZER (owner) + USR-AUDIENCE
-- (buyer). CP_* never modified. Requires: migrate4 + migrate5 + migrate6.
-- Idempotent (IF NOT EXISTS per CODE). Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/seed-discovery.sql
-- Or: task seed-discovery
SET XACT_ABORT ON;
BEGIN TRAN;

-- Event categories --------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT_CATEGORY WHERE CODE = 'KPOP')
  INSERT INTO dbo.T_EVENT_CATEGORY (CODE, NAME, SORT_ORDER) VALUES ('KPOP', 'K-pop', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT_CATEGORY WHERE CODE = 'ANIME')
  INSERT INTO dbo.T_EVENT_CATEGORY (CODE, NAME, SORT_ORDER) VALUES ('ANIME', 'Wibu/Anime', 2);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT_CATEGORY WHERE CODE = 'KONSER')
  INSERT INTO dbo.T_EVENT_CATEGORY (CODE, NAME, SORT_ORDER) VALUES ('KONSER', 'Konser', 3);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT_CATEGORY WHERE CODE = 'FESTIVAL')
  INSERT INTO dbo.T_EVENT_CATEGORY (CODE, NAME, SORT_ORDER) VALUES ('FESTIVAL', 'Festival', 4);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT_CATEGORY WHERE CODE = 'SPORT')
  INSERT INTO dbo.T_EVENT_CATEGORY (CODE, NAME, SORT_ORDER) VALUES ('SPORT', 'Olahraga', 5);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT_CATEGORY WHERE CODE = 'WORKSHOP')
  INSERT INTO dbo.T_EVENT_CATEGORY (CODE, NAME, SORT_ORDER) VALUES ('WORKSHOP', 'Workshop', 6);

-- News categories -----------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS_CATEGORY WHERE CODE = 'INFO')
  INSERT INTO dbo.T_NEWS_CATEGORY (CODE, NAME) VALUES ('INFO', 'Info');
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS_CATEGORY WHERE CODE = 'TIPS')
  INSERT INTO dbo.T_NEWS_CATEGORY (CODE, NAME) VALUES ('TIPS', 'Tips');
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS_CATEGORY WHERE CODE = 'LIPUTAN')
  INSERT INTO dbo.T_NEWS_CATEGORY (CODE, NAME) VALUES ('LIPUTAN', 'Liputan Event');
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS_CATEGORY WHERE CODE = 'PROMO')
  INSERT INTO dbo.T_NEWS_CATEGORY (CODE, NAME) VALUES ('PROMO', 'Info Promo');

-- Cities (3 exist from dashboard seed; add 7 more) ----------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-YK')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-YK', 'Yogyakarta');
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-SMG')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-SMG', 'Semarang');
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-MDN')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-MDN', 'Medan');
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-MKS')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-MKS', 'Makassar');
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-DPS')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-DPS', 'Denpasar');
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-MLG')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-MLG', 'Malang');
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-PLM')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-PLM', 'Palembang');

-- Events (12 published + ended + draft + cancelled) -----------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D01')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, ADDRESS, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT, POSTER_URL)
  VALUES ('EVT-D01', 'USR-ORGANIZER', 'CTY-JKT', 'KPOP', 'Seoul Wave Jakarta', 'Festival K-pop terbesar tahun ini dengan 5 grup papan atas.', 'JIExpo Kemayoran', 'Jl. Benyamin Sueb, Kemayoran', DATEADD(day, 20, GETDATE()), DATEADD(day, 21, GETDATE()), 'PUBLISHED', 10.00, 'https://picsum.photos/seed/tikto-d01/800/450');
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D02')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, ADDRESS, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D02', 'USR-ORGANIZER', 'CTY-BDG', 'ANIME', 'Wibu Fest Bandung', 'Festival anime, cosplay competition, dan doujin market.', 'Sabuga ITB', 'Jl. Tamansari No. 73, Bandung', DATEADD(day, 15, GETDATE()), DATEADD(day, 16, GETDATE()), 'PUBLISHED', 10.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D03')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, ADDRESS, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT, POSTER_URL)
  VALUES ('EVT-D03', 'USR-ORGANIZER', 'CTY-SBY', 'KONSER', 'Rock Nusa Surabaya', 'Konser rock lintas generasi, 10 band dalam satu panggung.', 'Grand City Convex', 'Jl. Walikota Mustajab, Surabaya', DATEADD(day, 40, GETDATE()), DATEADD(day, 40, GETDATE()), 'PUBLISHED', 10.00, 'https://picsum.photos/seed/tikto-d03/800/450');
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D04')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D04', 'USR-ORGANIZER', 'CTY-YK', 'FESTIVAL', 'Kuliner Nusantara', 'Festival kuliner 100 tenant dari seluruh Indonesia.', 'Jogja Expo Center', DATEADD(day, 10, GETDATE()), DATEADD(day, 12, GETDATE()), 'PUBLISHED', 8.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D05')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D05', 'USR-ORGANIZER', 'CTY-SMG', 'SPORT', 'Marathon Pagi Semarang', 'Lomba lari 5K dan 10K menyusuri kota lama.', 'Kota Lama Semarang', DATEADD(day, 25, GETDATE()), DATEADD(day, 25, GETDATE()), 'PUBLISHED', 8.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D06')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D06', 'USR-ORGANIZER', 'CTY-DPS', 'WORKSHOP', 'Kelas Kopi Denpasar', 'Workshop seduh manual dan latte art untuk pemula.', 'Uma Kopi Studio', DATEADD(day, 12, GETDATE()), DATEADD(day, 12, GETDATE()), 'PUBLISHED', 12.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D07')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D07', 'USR-ORGANIZER', 'CTY-MDN', 'KPOP', 'Encore Stage Medan', 'Tur encore boy group papan atas, satu malam saja.', 'Regale Convention', DATEADD(day, 50, GETDATE()), DATEADD(day, 50, GETDATE()), 'PUBLISHED', 10.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D08')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT, POSTER_URL)
  VALUES ('EVT-D08', 'USR-ORGANIZER', 'CTY-MLG', 'KONSER', 'Jazz Senja Malang', 'Konser jazz akustik di taman kota saat matahari terbenam.', 'Taman Krida Budaya', DATEADD(day, 8, GETDATE()), DATEADD(day, 8, GETDATE()), 'PUBLISHED', 10.00, 'https://picsum.photos/seed/tikto-d08/800/450');
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D09')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D09', 'USR-ORGANIZER', 'CTY-PLM', 'FESTIVAL', 'Lampion Palembang', 'Festival lampion tepi sungai Musi.', 'Benteng Kuto Besak', DATEADD(day, 35, GETDATE()), DATEADD(day, 37, GETDATE()), 'PUBLISHED', 8.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D10')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D10', 'USR-ORGANIZER', 'CTY-MKS', 'ANIME', 'Comic Day Makassar', 'Bursa komik dan games terbesar di Indonesia timur.', 'Phinisi Hall', DATEADD(day, 18, GETDATE()), DATEADD(day, 19, GETDATE()), 'PUBLISHED', 10.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D11')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D11', 'USR-ORGANIZER', 'CTY-JKT', 'KONSER', 'Hampir Habis Show', 'Showcase intim, kapasitas sangat terbatas.', 'Studio Kecil', DATEADD(day, 22, GETDATE()), DATEADD(day, 22, GETDATE()), 'PUBLISHED', 10.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D12')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D12', 'USR-ORGANIZER', 'CTY-BDG', 'WORKSHOP', 'Sold Out Class', 'Kelas masak yang selalu penuh dalam hitungan jam.', 'Dapur Kita', DATEADD(day, 28, GETDATE()), DATEADD(day, 28, GETDATE()), 'PUBLISHED', 12.00);
-- ended / draft / cancelled (must stay invisible in discovery)
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D13')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D13', 'USR-ORGANIZER', 'CTY-JKT', 'FESTIVAL', 'Festival Lalu', 'Sudah selesai bulan kemarin.', 'Lapangan Lama', DATEADD(day, -20, GETDATE()), DATEADD(day, -19, GETDATE()), 'COMPLETED', 8.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D14')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D14', 'USR-ORGANIZER', 'CTY-SBY', 'KONSER', 'Rahasia Belum Rilis', 'Masih draft, belum dipublikasi.', 'TBA', DATEADD(day, 55, GETDATE()), DATEADD(day, 55, GETDATE()), 'DRAFT', 10.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-D15')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-D15', 'USR-ORGANIZER', 'CTY-YK', 'SPORT', 'Fun Run Batal', 'Dibatalkan karena cuaca.', 'Alun-alun', DATEADD(day, 14, GETDATE()), DATEADD(day, 14, GETDATE()), 'CANCELLED', 8.00);
-- Backfill demo events with categories + posters
UPDATE dbo.T_EVENT SET EVENT_CATEGORY_CODE = 'KONSER', POSTER_URL = 'https://picsum.photos/seed/tikto-demo1/800/450'
WHERE CODE = 'EVT-DEMO1' AND EVENT_CATEGORY_CODE IS NULL;
UPDATE dbo.T_EVENT SET EVENT_CATEGORY_CODE = 'WORKSHOP'
WHERE CODE = 'EVT-DEMO2' AND EVENT_CATEGORY_CODE IS NULL;
UPDATE dbo.T_EVENT SET EVENT_CATEGORY_CODE = 'FESTIVAL'
WHERE CODE = 'EVT-DEMO3' AND EVENT_CATEGORY_CODE IS NULL;

-- Ticket types (2 per event) ----------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D01A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D01A', 'EVT-D01', 'Festival A', 350000, 500);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D01B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D01B', 'EVT-D01', 'VIP', 1200000, 50);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D02A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D02A', 'EVT-D02', 'Regular', 100000, 400);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D02B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D02B', 'EVT-D02', 'Cosplay Pass', 250000, 100);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D03A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D03A', 'EVT-D03', 'Regular', 200000, 1000);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D03B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D03B', 'EVT-D03', 'VIP', 750000, 100);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D04A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D04A', 'EVT-D04', 'HTM', 50000, 2000);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D04B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D04B', 'EVT-D04', 'Premium', 150000, 200);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D05A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D05A', 'EVT-D05', 'Kategori 5K', 125000, 800);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D05B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D05B', 'EVT-D05', 'Kategori 10K', 175000, 500);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D06A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D06A', 'EVT-D06', 'Umum', 300000, 40);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D06B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA, SALE_START_AT) VALUES ('TT-D06B', 'EVT-D06', 'Barista', 600000, 20, DATEADD(day, 5, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D07A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D07A', 'EVT-D07', 'Regular', 400000, 600);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D07B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D07B', 'EVT-D07', 'VIP', 1500000, 60);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D08A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D08A', 'EVT-D08', 'Regular', 180000, 300);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D08B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA, SALE_END_AT) VALUES ('TT-D08B', 'EVT-D08', 'VVIP', 500000, 50, DATEADD(day, -1, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D09A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D09A', 'EVT-D09', 'Regular', 75000, 1500);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D09B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D09B', 'EVT-D09', 'Keluarga', 250000, 200);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D10A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D10A', 'EVT-D10', 'Day Pass', 90000, 500);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D10B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D10B', 'EVT-D10', 'Full Pass', 200000, 150);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D11A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D11A', 'EVT-D11', 'Regular', 150000, 100);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D11B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D11B', 'EVT-D11', 'Sofa', 300000, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D12A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D12A', 'EVT-D12', 'Regular', 200000, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-D12B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA) VALUES ('TT-D12B', 'EVT-D12', 'VIP Dapur', 450000, 10);

-- Orders shaping sold counts: almost-full (92/100), sold-out (40/40), popular ----
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DSC01')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DSC01', 'EVT-D11', 'USR-AUDIENCE', 'TT-D11A', 95, 14250000, 0, 1425000, 12825000, 'PAID', DATEADD(day, -6, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DSC02')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DSC02', 'EVT-D12', 'USR-AUDIENCE', 'TT-D12A', 30, 6000000, 0, 720000, 5280000, 'PAID', DATEADD(day, -7, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DSC03')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DSC03', 'EVT-D12', 'USR-AUDIENCE', 'TT-D12B', 10, 4500000, 0, 540000, 3960000, 'PAID', DATEADD(day, -7, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DSC04')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DSC04', 'EVT-D01', 'USR-AUDIENCE', 'TT-D01A', 5, 1750000, 0, 175000, 1575000, 'PAID', DATEADD(day, -4, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DSC05')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DSC05', 'EVT-D03', 'USR-AUDIENCE', 'TT-D03A', 8, 1600000, 0, 160000, 1440000, 'PAID', DATEADD(day, -3, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DSC06')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DSC06', 'EVT-D08', 'USR-AUDIENCE', 'TT-D08A', 12, 2160000, 0, 216000, 1944000, 'PAID', DATEADD(day, -2, GETDATE()));

-- News (6 published + 1 draft; body has harmless markup + one XSS probe) ------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NW-D01')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, EVENT_CATEGORY_CODE, EVENT_CODE, STATUS, PUBLISHED_AT, VIEW_COUNT)
  VALUES ('NW-D01', 'Festival Musik Terbesar Siap Digelar di Jakarta', 'festival-musik-terbesar-jakarta', 'Seoul Wave Jakarta menghadirkan 5 grup papan atas akhir bulan ini.', '<p>Persiapan <b>Seoul Wave Jakarta</b> sudah 90 persen. Panitia menyiapkan dua panggung dan area kuliner.</p><script>alert(1)</script>', 'LIPUTAN', 'KPOP', 'EVT-D01', 'PUBLISHED', DATEADD(day, -2, GETDATE()), 150);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NW-D02')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, PUBLISHED_AT, VIEW_COUNT)
  VALUES ('NW-D02', 'Tips Berburu Tiket Konser Anti Kehabisan', 'tips-berburu-tiket-konser', 'Siapkan akun, koneksi, dan jam alarm sebelum war tiket dimulai.', '<p>Datang 15 menit lebih awal di halaman event dan simpan metode pembayaran.</p>', 'TIPS', 'PUBLISHED', DATEADD(day, -5, GETDATE()), 320);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NW-D03')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, EVENT_CATEGORY_CODE, STATUS, PUBLISHED_AT, VIEW_COUNT)
  VALUES ('NW-D03', 'Komunitas Cosplay Bandung Pecahkan Rekor', 'komunitas-cosplay-bandung-rekor', 'Ratusan cosplayer memadati Sabuga akhir pekan lalu.', '<p>Peserta datang dari 12 kota. Tahun depan menargetkan 2000 peserta.</p>', 'LIPUTAN', 'ANIME', 'PUBLISHED', DATEADD(day, -8, GETDATE()), 95);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NW-D04')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, PUBLISHED_AT, VIEW_COUNT)
  VALUES ('NW-D04', 'Promo Merdeka: Diskon 10 Persen Semua Event', 'promo-merdeka-diskon', 'Gunakan kode MERDEKA10 untuk potongan semua event bulan ini.', '<p>Syarat dan ketentuan berlaku. Maksimum potongan Rp50 ribu.</p>', 'PROMO', 'PUBLISHED', DATEADD(day, -1, GETDATE()), 410);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NW-D05')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, PUBLISHED_AT, VIEW_COUNT)
  VALUES ('NW-D05', 'Jadwal Event Bulan Depan: Catat Tanggalnya', 'jadwal-event-bulan-depan', 'Rangkuman event pilihan yang sayang dilewatkan.', '<p>Dari konser jazz sampai marathon pagi, semua ada bulan depan.</p>', 'INFO', 'PUBLISHED', DATEADD(day, -3, GETDATE()), 60);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NW-D06')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, EVENT_CATEGORY_CODE, EVENT_CODE, STATUS, PUBLISHED_AT, VIEW_COUNT)
  VALUES ('NW-D06', 'Belanja Merchandise Original di Venue', 'merchandise-original-venue', 'Bawa pulang kaos dan poster resmi dari event favoritmu.', '<p>Gerai merchandise buka 2 jam sebelum acara dimulai.</p>', 'INFO', 'FESTIVAL', 'EVT-D04', 'PUBLISHED', DATEADD(day, -6, GETDATE()), 45);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NW-D07')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, PUBLISHED_AT)
  VALUES ('NW-D07', 'Draf Rahasia Redaksi', 'draf-rahasia', 'Belum terbit, tidak boleh bocor.', '<p>Rahasia.</p>', 'INFO', 'DRAFT', NULL);

-- Promos (active, upcoming, expired, exhausted) -------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-DISC10')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, MAX_DISCOUNT_AMOUNT, MIN_PURCHASE, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS)
  VALUES ('PRM-DISC10', 'DISC10', 'Diskon 10% semua event, maks Rp50 ribu, min belanja Rp100 ribu.', 10.00, 50000, 100000, 1000, 12, DATEADD(day, -10, GETDATE()), DATEADD(day, 20, GETDATE()), 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-KPOP20')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, COVERAGE_CATEGORY_CODE, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS)
  VALUES ('PRM-KPOP20', 'KPOP20', 'Diskon 20% khusus event K-pop.', 20.00, 'KPOP', 200, 5, DATEADD(day, -5, GETDATE()), DATEADD(day, 25, GETDATE()), 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-D01EVT')
  INSERT INTO dbo.T_PROMO (CODE, EVENT_CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS)
  VALUES ('PRM-D01EVT', 'EVT-D01', 'SEOUL50', 'Potongan Rp50 ribu khusus Seoul Wave Jakarta.', 0, 50000, 100, 3, DATEADD(day, -7, GETDATE()), DATEADD(day, 15, GETDATE()), 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-FUTURE')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS)
  VALUES ('PRM-FUTURE', 'NATAL25', 'Diskon Natal 25%, berlaku mulai bulan depan.', 25.00, 500, 0, DATEADD(day, 10, GETDATE()), DATEADD(day, 40, GETDATE()), 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-OLD')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS)
  VALUES ('PRM-OLD', 'LAMA15', 'Sudah lewat masanya.', 15.00, 100, 90, DATEADD(day, -40, GETDATE()), DATEADD(day, -5, GETDATE()), 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-OUT')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS)
  VALUES ('PRM-OUT', 'HABIS5', 'Kuotanya sudah habis.', 5.00, 10, 10, DATEADD(day, -10, GETDATE()), DATEADD(day, 20, GETDATE()), 'ACTIVE');

-- Ad campaigns (2 live + 1 ended) --------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_CAMPAIGN WHERE CODE = 'ADC-D01')
  INSERT INTO dbo.T_AD_CAMPAIGN (CODE, TITLE, TARGET_URL, POSITION, START_AT, END_AT, STATUS)
  VALUES ('ADC-D01', 'Sponsor Bank TiktoPay', 'https://example.com/tiktopay', 'HOME_BANNER', DATEADD(day, -5, GETDATE()), DATEADD(day, 30, GETDATE()), 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_CAMPAIGN WHERE CODE = 'ADC-D02')
  INSERT INTO dbo.T_AD_CAMPAIGN (CODE, TITLE, TARGET_URL, POSITION, START_AT, END_AT, STATUS)
  VALUES ('ADC-D02', 'Minuman Segar Dingin', 'https://example.com/minuman', 'EVENT_LIST', DATEADD(day, -2, GETDATE()), DATEADD(day, 15, GETDATE()), 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_CAMPAIGN WHERE CODE = 'ADC-D03')
  INSERT INTO dbo.T_AD_CAMPAIGN (CODE, TITLE, TARGET_URL, POSITION, START_AT, END_AT, STATUS)
  VALUES ('ADC-D03', 'Promo Berakhir Kemarin', 'https://example.com/lama', 'HOME_BANNER', DATEADD(day, -30, GETDATE()), DATEADD(day, -1, GETDATE()), 'ACTIVE');

COMMIT TRAN;
