-- Demo seed for TICKETING module (checkout -> pay -> scan -> refund flows).
-- ONLY touches T_* tables. Buyer USR-AUDIENCE, officer USR-OFFICER.
-- QR_TOKEN values are backfilled afterwards (signed tokens cannot be made
-- in SQL - see note at the bottom). CP_* never modified.
-- Requires: migrate4/5/6/9 (accounts, T_* tables, columns) + migrate12.
-- Idempotent (IF NOT EXISTS per CODE). Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/seed-ticketing.sql
-- Or: task seed-ticketing
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
BEGIN TRAN;

-- Event happening TODAY (scan demo target) ------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-T01')
  INSERT INTO dbo.T_EVENT (CODE, SLUG, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, ADDRESS, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT, PUBLISHED_AT)
  VALUES ('EVT-T01', 'panggung-hari-ini-evt-t01', 'USR-ORGANIZER', 'CTY-JKT', 'KONSER', 'Panggung Hari Ini', 'Konser yang berlangsung hari ini, cocok untuk demo scan.', 'Hall Live', 'Jl. Demo No. 7',
    DATEADD(hour, -2, GETDATE()), DATEADD(hour, 8, GETDATE()), 'PUBLISHED', 10.00, DATEADD(day, -7, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-T01A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, DESCRIPTION, PRICE, QUOTA, IS_ACTIVE, SORT_ORDER) VALUES ('TT-T01A', 'EVT-T01', 'Regular', 'Akses festival', 100000, 200, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-T01B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, DESCRIPTION, PRICE, QUOTA, IS_ACTIVE, SORT_ORDER) VALUES ('TT-T01B', 'EVT-T01', 'VIP', 'Depan panggung', 300000, 50, 1, 2);

-- Orders in every status (buyer audience) -------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-T01')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE, RESERVED_UNTIL)
  VALUES ('ORD-T01', 'EVT-T01', 'USR-AUDIENCE', 'TT-T01A', 2, 200000, 0, 20000, 220000, 'PENDING', DATEADD(minute, -1, GETDATE()), DATEADD(minute, 14, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER_ITEM WHERE CODE = 'OI-T01A')
  INSERT INTO dbo.T_ORDER_ITEM (CODE, ORDER_CODE, TICKET_TYPE_CODE, TYPE_NAME, UNIT_PRICE, QTY)
  VALUES ('OI-T01A', 'ORD-T01', 'TT-T01A', 'Regular', 100000, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.T_STOCK_RESERVATION WHERE CODE = 'RSV-T01A')
  INSERT INTO dbo.T_STOCK_RESERVATION (CODE, ORDER_CODE, TICKET_TYPE_CODE, QTY, EXPIRES_AT)
  VALUES ('RSV-T01A', 'ORD-T01', 'TT-T01A', 2, DATEADD(minute, 14, GETDATE()));

IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-T02')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, PROMO_CODE, STATUS, ORDER_DATE)
  VALUES ('ORD-T02', 'EVT-T01', 'USR-AUDIENCE', 'TT-T01A', 2, 200000, 20000, 18000, 198000, 'HEMAT20', 'PAID', DATEADD(day, -2, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER_ITEM WHERE CODE = 'OI-T02A')
  INSERT INTO dbo.T_ORDER_ITEM (CODE, ORDER_CODE, TICKET_TYPE_CODE, TYPE_NAME, UNIT_PRICE, QTY)
  VALUES ('OI-T02A', 'ORD-T02', 'TT-T01A', 'Regular', 100000, 2);

IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-T03')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-T03', 'EVT-T01', 'USR-AUDIENCE', 'TT-T01B', 1, 300000, 0, 30000, 330000, 'PAID', DATEADD(day, -3, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-T04')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-T04', 'EVT-D08', 'USR-AUDIENCE', 'TT-D08A', 1, 180000, 0, 18000, 198000, 'PAID', DATEADD(day, -4, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-T05')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-T05', 'EVT-T01', 'USR-AUDIENCE', 'TT-T01A', 1, 100000, 0, 10000, 110000, 'EXPIRED', DATEADD(day, -5, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-T06')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-T06', 'EVT-T01', 'USR-AUDIENCE', 'TT-T01B', 1, 300000, 0, 30000, 330000, 'CANCELLED', DATEADD(day, -5, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-T07')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-T07', 'EVT-D01', 'USR-AUDIENCE', 'TT-D01A', 1, 350000, 0, 35000, 385000, 'PAID', DATEADD(day, -6, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-T08')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-T08', 'EVT-D02', 'USR-AUDIENCE', 'TT-D02A', 1, 100000, 0, 10000, 110000, 'REFUNDED', DATEADD(day, -9, GETDATE()));

-- Tickets (QR_TOKEN backfilled by Go helper afterwards) -----------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-T01')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, EMAIL, STATUS) VALUES ('TIX-T01', 'ORD-T02', 'QR-T01', 'Ayu Lestari', 'ayu@mail.com', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-T02')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-T02', 'ORD-T02', 'QR-T02', 'Budi Santoso', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-T03')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, EMAIL, PHONE, STATUS) VALUES ('TIX-T03', 'ORD-T03', 'QR-T03', 'Citra Ayu', 'citra@mail.com', '081203', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-T04')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-T04', 'ORD-T04', 'QR-T04', 'Dedi Kurnia', 'USED', DATEADD(day, -1, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-T07')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-T07', 'ORD-T07', 'QR-T07', 'Gita Sari', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-T08')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-T08', 'ORD-T08', 'QR-T08', 'Hadi Wijaya', 'REFUNDED');

-- Refunds: 1 PENDING (approve/reject test) + 1 APPROVED history ------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_REFUND WHERE CODE = 'RFD-T01')
  INSERT INTO dbo.T_REFUND (CODE, ORDER_CODE, AMOUNT, REASON, STATUS, REQUESTED_BY, PAYOUT_STATUS)
  VALUES ('RFD-T01', 'ORD-T07', 385000, 'Jadwal bentrok', 'PENDING', 'USR-AUDIENCE', 'PENDING_FINANCE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_REFUND WHERE CODE = 'RFD-T02')
  INSERT INTO dbo.T_REFUND (CODE, ORDER_CODE, AMOUNT, REASON, STATUS, REQUESTED_BY, DECIDED_BY, DECIDED_AT, PAYOUT_STATUS)
  VALUES ('RFD-T02', 'ORD-T08', 110000, 'Double order', 'APPROVED', 'USR-AUDIENCE', 'USR-ORGANIZER', DATEADD(day, -2, GETDATE()), 'PENDING_FINANCE');

-- Officer assignment + scan log samples ------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT_OFFICER WHERE EVENT_CODE = 'EVT-T01' AND OFFICER_CODE = 'USR-OFFICER')
  INSERT INTO dbo.T_EVENT_OFFICER (EVENT_CODE, OFFICER_CODE) VALUES ('EVT-T01', 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_SCAN_LOG WHERE CODE = 'SCN-T01')
  INSERT INTO dbo.T_SCAN_LOG (CODE, EVENT_CODE, TICKET_CODE, OFFICER_CODE, RESULT, DETAIL) VALUES ('SCN-T01', 'EVT-T01', 'TIX-T01', 'USR-OFFICER', 'VALID', 'Ayu Lestari');
IF NOT EXISTS (SELECT 1 FROM dbo.T_SCAN_LOG WHERE CODE = 'SCN-T02')
  INSERT INTO dbo.T_SCAN_LOG (CODE, EVENT_CODE, TICKET_CODE, OFFICER_CODE, RESULT, DETAIL) VALUES ('SCN-T02', 'EVT-T01', 'TIX-T01', 'USR-OFFICER', 'USED', 'sudah masuk');
IF NOT EXISTS (SELECT 1 FROM dbo.T_SCAN_LOG WHERE CODE = 'SCN-T03')
  INSERT INTO dbo.T_SCAN_LOG (CODE, EVENT_CODE, TICKET_CODE, OFFICER_CODE, RESULT, DETAIL) VALUES ('SCN-T03', 'EVT-T01', NULL, 'USR-OFFICER', 'INVALID', 'tidak ditemukan');

COMMIT TRAN;

-- QR_TOKEN backfill: signed tokens cannot be made in SQL. After running this
-- file, generate tokens with the Go helper and UPDATE each TIX-T* row:
--   go run ./scripts/qrseed_helper.go (see repo scripts/)
-- (The helper reads JWT_SECRET/QR_SECRET from .env and prints UPDATEs.)
