-- Demo seed for dashboard T_ tables (organizer + seller dashboards).
-- ONLY touches T_* tables. CP_* accounts used (never modified):
--   organizer USR-ORGANIZER, seller USR-SELLER, buyer USR-AUDIENCE,
--   officer USR-OFFICER (checked_in_by).
-- Requires: migrate4 (accounts) + migrate5 (T_ tables).
-- Idempotent (IF NOT EXISTS per CODE). Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/seed-dashboard.sql
-- Or: task seed-dashboard
SET XACT_ABORT ON;
BEGIN TRAN;

-- Cities ----------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-JKT')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-JKT', 'Jakarta');
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-BDG')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-BDG', 'Bandung');
IF NOT EXISTS (SELECT 1 FROM dbo.T_CITY WHERE CODE = 'CTY-SBY')
  INSERT INTO dbo.T_CITY (CODE, NAME) VALUES ('CTY-SBY', 'Surabaya');

-- Events (2 published future + 1 draft for the unpublished alert) -------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-DEMO1')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, TITLE, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-DEMO1', 'USR-ORGANIZER', 'CTY-JKT', 'Jakarta Music Fest', 'GBK Senayan',
    DATEADD(day, 30, GETDATE()), DATEADD(day, 31, GETDATE()), 'PUBLISHED', 10.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-DEMO2')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, TITLE, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-DEMO2', 'USR-ORGANIZER', 'CTY-BDG', 'Bandung Tech Conference', 'Gedung Sate Hall',
    DATEADD(day, 45, GETDATE()), DATEADD(day, 46, GETDATE()), 'PUBLISHED', 12.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-DEMO3')
  INSERT INTO dbo.T_EVENT (CODE, ORGANIZER_CODE, CITY_CODE, TITLE, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-DEMO3', 'USR-ORGANIZER', 'CTY-SBY', 'Surabaya Food Carnival', 'Grand City',
    DATEADD(day, 60, GETDATE()), DATEADD(day, 62, GETDATE()), 'DRAFT', 10.00);

-- Ticket types -----------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-VIP1')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA)
  VALUES ('TT-VIP1', 'EVT-DEMO1', 'VIP', 500000, 100);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-REG1')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA)
  VALUES ('TT-REG1', 'EVT-DEMO1', 'Regular', 150000, 900);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-EARLY2')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA)
  VALUES ('TT-EARLY2', 'EVT-DEMO2', 'Early Bird', 250000, 200);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-NORM2')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA)
  VALUES ('TT-NORM2', 'EVT-DEMO2', 'Normal', 400000, 300);

-- Promos (HEMAT20 + EARLY10 active, SOON5 expires in 2 days for the alert) ------
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-HEMAT20')
  INSERT INTO dbo.T_PROMO (CODE, EVENT_CODE, PROMO_CODE, DISCOUNT_PERCENT, MAX_USES, VALID_FROM, VALID_TO, STATUS)
  VALUES ('PRM-HEMAT20', 'EVT-DEMO1', 'HEMAT20', 20.00, 500, DATEADD(day, -30, GETDATE()), DATEADD(day, 30, GETDATE()), 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-EARLY10')
  INSERT INTO dbo.T_PROMO (CODE, EVENT_CODE, PROMO_CODE, DISCOUNT_PERCENT, MAX_USES, VALID_FROM, VALID_TO, STATUS)
  VALUES ('PRM-EARLY10', NULL, 'EARLY10', 10.00, 1000, DATEADD(day, -30, GETDATE()), DATEADD(day, 60, GETDATE()), 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-SOON5')
  INSERT INTO dbo.T_PROMO (CODE, EVENT_CODE, PROMO_CODE, DISCOUNT_PERCENT, MAX_USES, VALID_FROM, VALID_TO, STATUS)
  VALUES ('PRM-SOON5', 'EVT-DEMO2', 'SOON5', 5.00, 100, DATEADD(day, -10, GETDATE()), DATEADD(day, 2, GETDATE()), 'ACTIVE');

-- Orders (PAID across the last 30 days + 1 CANCELLED + 1 REFUNDED) --------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO01')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, PROMO_CODE, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO01', 'EVT-DEMO1', 'USR-AUDIENCE', 'TT-VIP1', 2, 1000000, 200000, 80000, 720000, 'HEMAT20', 'PAID', DATEADD(day, -2, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO02')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO02', 'EVT-DEMO1', 'USR-AUDIENCE', 'TT-REG1', 4, 600000, 0, 60000, 540000, 'PAID', DATEADD(day, -5, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO03')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, PROMO_CODE, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO03', 'EVT-DEMO1', 'USR-AUDIENCE', 'TT-REG1', 1, 150000, 30000, 12000, 108000, 'HEMAT20', 'PAID', DATEADD(day, -9, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO04')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, PROMO_CODE, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO04', 'EVT-DEMO2', 'USR-AUDIENCE', 'TT-EARLY2', 2, 500000, 50000, 54000, 396000, 'EARLY10', 'PAID', DATEADD(day, -12, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO05')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO05', 'EVT-DEMO2', 'USR-AUDIENCE', 'TT-NORM2', 1, 400000, 0, 48000, 352000, 'PAID', DATEADD(day, -15, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO06')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO06', 'EVT-DEMO1', 'USR-AUDIENCE', 'TT-REG1', 3, 450000, 0, 45000, 405000, 'PAID', DATEADD(day, -20, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO07')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO07', 'EVT-DEMO1', 'USR-AUDIENCE', 'TT-VIP1', 1, 500000, 0, 50000, 450000, 'PAID', DATEADD(day, -25, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO08')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO08', 'EVT-DEMO2', 'USR-AUDIENCE', 'TT-EARLY2', 1, 250000, 0, 30000, 220000, 'PAID', DATEADD(day, -28, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO09')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO09', 'EVT-DEMO1', 'USR-AUDIENCE', 'TT-REG1', 2, 300000, 0, 30000, 270000, 'CANCELLED', DATEADD(day, -3, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-DEMO10')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-DEMO10', 'EVT-DEMO1', 'USR-AUDIENCE', 'TT-REG1', 1, 150000, 0, 15000, 135000, 'REFUNDED', DATEADD(day, -1, GETDATE()));

-- Tickets (mix of USED + ACTIVE + 1 REFUNDED) ------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D01')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY)
  VALUES ('TIX-D01', 'ORD-DEMO01', 'QR-DEMO01', 'Ayu', 'USED', DATEADD(day, -1, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D02')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D02', 'ORD-DEMO01', 'QR-DEMO02', 'Budi', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D03')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY)
  VALUES ('TIX-D03', 'ORD-DEMO02', 'QR-DEMO03', 'Citra', 'USED', DATEADD(day, -2, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D04')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY)
  VALUES ('TIX-D04', 'ORD-DEMO02', 'QR-DEMO04', 'Dedi', 'USED', DATEADD(day, -2, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D05')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D05', 'ORD-DEMO02', 'QR-DEMO05', 'Eka', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D06')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D06', 'ORD-DEMO02', 'QR-DEMO06', 'Fajar', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D07')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D07', 'ORD-DEMO03', 'QR-DEMO07', 'Gita', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D08')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D08', 'ORD-DEMO04', 'QR-DEMO08', 'Hadi', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D09')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D09', 'ORD-DEMO04', 'QR-DEMO09', 'Indah', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D10')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY)
  VALUES ('TIX-D10', 'ORD-DEMO05', 'QR-DEMO10', 'Joko', 'USED', DATEADD(day, -3, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D11')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D11', 'ORD-DEMO06', 'QR-DEMO11', 'Kirana', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D12')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D12', 'ORD-DEMO06', 'QR-DEMO12', 'Lukman', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D13')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D13', 'ORD-DEMO06', 'QR-DEMO13', 'Maya', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D14')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY)
  VALUES ('TIX-D14', 'ORD-DEMO07', 'QR-DEMO14', 'Nadia', 'USED', DATEADD(day, -4, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D15')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D15', 'ORD-DEMO08', 'QR-DEMO15', 'Oscar', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-D16')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS)
  VALUES ('TIX-D16', 'ORD-DEMO10', 'QR-DEMO16', 'Putri', 'REFUNDED');

-- Refunds (1 PENDING for approve/reject test + 1 APPROVED history) --------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_REFUND WHERE CODE = 'RFD-DEMO1')
  INSERT INTO dbo.T_REFUND (CODE, ORDER_CODE, AMOUNT, REASON, STATUS, REQUESTED_BY)
  VALUES ('RFD-DEMO1', 'ORD-DEMO03', 108000, 'Acara bentrok jadwal', 'PENDING', 'USR-AUDIENCE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_REFUND WHERE CODE = 'RFD-DEMO2')
  INSERT INTO dbo.T_REFUND (CODE, ORDER_CODE, AMOUNT, REASON, STATUS, REQUESTED_BY, DECIDED_BY, DECIDED_AT)
  VALUES ('RFD-DEMO2', 'ORD-DEMO10', 135000, 'Tiket ganda', 'APPROVED', 'USR-AUDIENCE', 'USR-ORGANIZER', DATEADD(day, -1, GETDATE()));

-- Ad stats (7 days for EVT-DEMO1) -------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_DAILY WHERE EVENT_CODE = 'EVT-DEMO1' AND STAT_DATE = CAST(DATEADD(day, -6, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_DAILY (EVENT_CODE, STAT_DATE, IMPRESSIONS, CLICKS, COST)
  VALUES ('EVT-DEMO1', CAST(DATEADD(day, -6, GETDATE()) AS DATE), 12000, 320, 150000);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_DAILY WHERE EVENT_CODE = 'EVT-DEMO1' AND STAT_DATE = CAST(DATEADD(day, -5, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_DAILY (EVENT_CODE, STAT_DATE, IMPRESSIONS, CLICKS, COST)
  VALUES ('EVT-DEMO1', CAST(DATEADD(day, -5, GETDATE()) AS DATE), 15000, 410, 180000);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_DAILY WHERE EVENT_CODE = 'EVT-DEMO1' AND STAT_DATE = CAST(DATEADD(day, -4, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_DAILY (EVENT_CODE, STAT_DATE, IMPRESSIONS, CLICKS, COST)
  VALUES ('EVT-DEMO1', CAST(DATEADD(day, -4, GETDATE()) AS DATE), 18000, 520, 210000);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_DAILY WHERE EVENT_CODE = 'EVT-DEMO1' AND STAT_DATE = CAST(DATEADD(day, -3, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_DAILY (EVENT_CODE, STAT_DATE, IMPRESSIONS, CLICKS, COST)
  VALUES ('EVT-DEMO1', CAST(DATEADD(day, -3, GETDATE()) AS DATE), 22000, 640, 250000);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_DAILY WHERE EVENT_CODE = 'EVT-DEMO1' AND STAT_DATE = CAST(DATEADD(day, -2, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_DAILY (EVENT_CODE, STAT_DATE, IMPRESSIONS, CLICKS, COST)
  VALUES ('EVT-DEMO1', CAST(DATEADD(day, -2, GETDATE()) AS DATE), 25000, 700, 280000);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_DAILY WHERE EVENT_CODE = 'EVT-DEMO1' AND STAT_DATE = CAST(DATEADD(day, -1, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_DAILY (EVENT_CODE, STAT_DATE, IMPRESSIONS, CLICKS, COST)
  VALUES ('EVT-DEMO1', CAST(DATEADD(day, -1, GETDATE()) AS DATE), 19000, 480, 200000);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_DAILY WHERE EVENT_CODE = 'EVT-DEMO1' AND STAT_DATE = CAST(GETDATE() AS DATE))
  INSERT INTO dbo.T_AD_DAILY (EVENT_CODE, STAT_DATE, IMPRESSIONS, CLICKS, COST)
  VALUES ('EVT-DEMO1', CAST(GETDATE() AS DATE), 9000, 210, 90000);

-- Payout + balances ----------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_PAYOUT WHERE CODE = 'PYO-DEMO1')
  INSERT INTO dbo.T_PAYOUT (CODE, OWNER_CODE, AMOUNT, STATUS)
  VALUES ('PYO-DEMO1', 'USR-ORGANIZER', 1500000, 'READY');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PAYOUT WHERE CODE = 'PYO-DEMO2')
  INSERT INTO dbo.T_PAYOUT (CODE, OWNER_CODE, AMOUNT, STATUS)
  VALUES ('PYO-DEMO2', 'USR-SELLER', 500000, 'READY');
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORGANIZER_BALANCE WHERE ORGANIZER_CODE = 'USR-ORGANIZER')
  INSERT INTO dbo.T_ORGANIZER_BALANCE (CODE, ORGANIZER_CODE, ESCROW_AMOUNT, AVAILABLE_AMOUNT)
  VALUES ('OBL-DEMO1', 'USR-ORGANIZER', 2500000, 1000000);
IF NOT EXISTS (SELECT 1 FROM dbo.T_SELLER_BALANCE WHERE SELLER_CODE = 'USR-SELLER')
  INSERT INTO dbo.T_SELLER_BALANCE (CODE, SELLER_CODE, ESCROW_AMOUNT, AVAILABLE_AMOUNT)
  VALUES ('SBL-DEMO1', 'USR-SELLER', 750000, 500000);

-- Products (2 low-stock + 1 rejected for alerts) -------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_PRODUCT WHERE CODE = 'PRD-KAOS')
  INSERT INTO dbo.T_PRODUCT (CODE, SELLER_CODE, CATEGORY, NAME, PRICE, STOCK, LOW_STOCK_THRESHOLD, RATING, REVIEW_COUNT, STATUS)
  VALUES ('PRD-KAOS', 'USR-SELLER', 'Apparel', 'Kaos Tikto', 120000, 3, 5, 5.00, 2, 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PRODUCT WHERE CODE = 'PRD-TUMBLER')
  INSERT INTO dbo.T_PRODUCT (CODE, SELLER_CODE, CATEGORY, NAME, PRICE, STOCK, LOW_STOCK_THRESHOLD, RATING, REVIEW_COUNT, STATUS)
  VALUES ('PRD-TUMBLER', 'USR-SELLER', 'Accessories', 'Tumbler Event', 85000, 50, 5, 4.50, 2, 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PRODUCT WHERE CODE = 'PRD-POSTER')
  INSERT INTO dbo.T_PRODUCT (CODE, SELLER_CODE, CATEGORY, NAME, PRICE, STOCK, LOW_STOCK_THRESHOLD, RATING, REVIEW_COUNT, STATUS)
  VALUES ('PRD-POSTER', 'USR-SELLER', 'Accessories', 'Poster Konser', 35000, 2, 5, 5.00, 1, 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PRODUCT WHERE CODE = 'PRD-HOODIE')
  INSERT INTO dbo.T_PRODUCT (CODE, SELLER_CODE, CATEGORY, NAME, PRICE, STOCK, LOW_STOCK_THRESHOLD, STATUS)
  VALUES ('PRD-HOODIE', 'USR-SELLER', 'Apparel', 'Hoodie Bajakan', 250000, 10, 5, 'REJECTED');

-- Merch orders (all statuses; MORD-D01 ships tomorrow for the alert) ------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_MERCH_ORDER WHERE CODE = 'MORD-D01')
  INSERT INTO dbo.T_MERCH_ORDER (CODE, PRODUCT_CODE, BUYER_CODE, SELLER_CODE, QTY, TOTAL_AMOUNT, STATUS, ORDER_DATE, SHIP_DEADLINE)
  VALUES ('MORD-D01', 'PRD-KAOS', 'USR-AUDIENCE', 'USR-SELLER', 2, 240000, 'NEW', DATEADD(day, -1, GETDATE()), DATEADD(day, 1, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_MERCH_ORDER WHERE CODE = 'MORD-D02')
  INSERT INTO dbo.T_MERCH_ORDER (CODE, PRODUCT_CODE, BUYER_CODE, SELLER_CODE, QTY, TOTAL_AMOUNT, STATUS, ORDER_DATE, SHIP_DEADLINE)
  VALUES ('MORD-D02', 'PRD-TUMBLER', 'USR-AUDIENCE', 'USR-SELLER', 1, 85000, 'PROCESSING', DATEADD(day, -2, GETDATE()), DATEADD(day, 5, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_MERCH_ORDER WHERE CODE = 'MORD-D03')
  INSERT INTO dbo.T_MERCH_ORDER (CODE, PRODUCT_CODE, BUYER_CODE, SELLER_CODE, QTY, TOTAL_AMOUNT, STATUS, ORDER_DATE, SHIP_DEADLINE, SHIPPED_AT)
  VALUES ('MORD-D03', 'PRD-POSTER', 'USR-AUDIENCE', 'USR-SELLER', 5, 175000, 'SHIPPED', DATEADD(day, -3, GETDATE()), DATEADD(day, 2, GETDATE()), DATEADD(day, -1, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_MERCH_ORDER WHERE CODE = 'MORD-D04')
  INSERT INTO dbo.T_MERCH_ORDER (CODE, PRODUCT_CODE, BUYER_CODE, SELLER_CODE, QTY, TOTAL_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('MORD-D04', 'PRD-KAOS', 'USR-AUDIENCE', 'USR-SELLER', 1, 120000, 'COMPLETED', DATEADD(day, -4, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_MERCH_ORDER WHERE CODE = 'MORD-D05')
  INSERT INTO dbo.T_MERCH_ORDER (CODE, PRODUCT_CODE, BUYER_CODE, SELLER_CODE, QTY, TOTAL_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('MORD-D05', 'PRD-TUMBLER', 'USR-AUDIENCE', 'USR-SELLER', 2, 170000, 'COMPLETED', DATEADD(day, -8, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_MERCH_ORDER WHERE CODE = 'MORD-D06')
  INSERT INTO dbo.T_MERCH_ORDER (CODE, PRODUCT_CODE, BUYER_CODE, SELLER_CODE, QTY, TOTAL_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('MORD-D06', 'PRD-POSTER', 'USR-AUDIENCE', 'USR-SELLER', 1, 35000, 'COMPLETED', DATEADD(day, -12, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_MERCH_ORDER WHERE CODE = 'MORD-D07')
  INSERT INTO dbo.T_MERCH_ORDER (CODE, PRODUCT_CODE, BUYER_CODE, SELLER_CODE, QTY, TOTAL_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('MORD-D07', 'PRD-KAOS', 'USR-AUDIENCE', 'USR-SELLER', 1, 120000, 'COMPLETED', DATEADD(day, -20, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_MERCH_ORDER WHERE CODE = 'MORD-D08')
  INSERT INTO dbo.T_MERCH_ORDER (CODE, PRODUCT_CODE, BUYER_CODE, SELLER_CODE, QTY, TOTAL_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('MORD-D08', 'PRD-TUMBLER', 'USR-AUDIENCE', 'USR-SELLER', 1, 85000, 'CANCELLED', DATEADD(day, -2, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_MERCH_ORDER WHERE CODE = 'MORD-D09')
  INSERT INTO dbo.T_MERCH_ORDER (CODE, PRODUCT_CODE, BUYER_CODE, SELLER_CODE, QTY, TOTAL_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('MORD-D09', 'PRD-POSTER', 'USR-AUDIENCE', 'USR-SELLER', 2, 70000, 'RETURNED', DATEADD(day, -15, GETDATE()));

-- Complaint (1 OPEN) + reviews ----------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_COMPLAINT WHERE CODE = 'CMP-D01')
  INSERT INTO dbo.T_COMPLAINT (CODE, ORDER_CODE, BUYER_CODE, MESSAGE, STATUS)
  VALUES ('CMP-D01', 'MORD-D04', 'USR-AUDIENCE', 'Sablon kaos luntur setelah dicuci', 'OPEN');
IF NOT EXISTS (SELECT 1 FROM dbo.T_REVIEW WHERE CODE = 'REV-D01')
  INSERT INTO dbo.T_REVIEW (CODE, ORDER_CODE, PRODUCT_CODE, BUYER_CODE, RATING, COMMENT)
  VALUES ('REV-D01', 'MORD-D05', 'PRD-TUMBLER', 'USR-AUDIENCE', 5, 'Bagus, pengiriman cepat');
IF NOT EXISTS (SELECT 1 FROM dbo.T_REVIEW WHERE CODE = 'REV-D02')
  INSERT INTO dbo.T_REVIEW (CODE, ORDER_CODE, PRODUCT_CODE, BUYER_CODE, RATING, COMMENT)
  VALUES ('REV-D02', 'MORD-D06', 'PRD-POSTER', 'USR-AUDIENCE', 4, 'Lumayan, warna sedikit pudar');
IF NOT EXISTS (SELECT 1 FROM dbo.T_REVIEW WHERE CODE = 'REV-D03')
  INSERT INTO dbo.T_REVIEW (CODE, ORDER_CODE, PRODUCT_CODE, BUYER_CODE, RATING, COMMENT)
  VALUES ('REV-D03', 'MORD-D07', 'PRD-KAOS', 'USR-AUDIENCE', 5, 'Kaos adem, recommended');

COMMIT TRAN;
