-- Demo seed for MARKETING module (promo + ad + news).
-- ONLY touches T_* tables (never CP_*). Owner = USR-ORGANIZER, buyer = USR-AUDIENCE.
-- Requires: migrate4 (accounts) + migrate5/6/9/12/14 (T_* tables + columns).
-- Idempotent (IF NOT EXISTS per CODE). Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/seed-marketing.sql
-- Or: task seed-marketing
SET XACT_ABORT ON;
BEGIN TRAN;

-- 6 promos: aktif / akan_datang / kedaluwarsa / kuota_habis / nonaktif / used --
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-MKT01')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, MAX_DISCOUNT_AMOUNT, MIN_PURCHASE, MAX_USES, USED_COUNT, MAX_PER_USER, VALID_FROM, VALID_TO, STATUS, SCOPE_TYPE, ORGANIZER_CODE)
  VALUES ('PRM-MKT01', 'MKT-AKTIF10', 'Diskon 10% aktif, maks Rp30 rb, min 50 rb', 10.00, 30000, 50000, 100, 5, 2, DATEADD(day, -5, GETDATE()), DATEADD(day, 20, GETDATE()), 'ACTIVE', 'ALL', 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-MKT02')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_AMOUNT, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS, SCOPE_TYPE, ORGANIZER_CODE)
  VALUES ('PRM-MKT02', 'MKT-DATANG50', 'Potongan 50rb akan datang (kategori KONSER)', 50000, 50, 0, DATEADD(day, 10, GETDATE()), DATEADD(day, 40, GETDATE()), 'ACTIVE', 'CATEGORY', 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-MKT03')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS, SCOPE_TYPE, ORGANIZER_CODE)
  VALUES ('PRM-MKT03', 'MKT-KADAL15', 'Sudah lewat', 15.00, 100, 20, DATEADD(day, -40, GETDATE()), DATEADD(day, -5, GETDATE()), 'ACTIVE', 'ALL', 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-MKT04')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS, SCOPE_TYPE, ORGANIZER_CODE)
  VALUES ('PRM-MKT04', 'MKT-HABIS5', 'Kuota habis', 5.00, 10, 10, DATEADD(day, -10, GETDATE()), DATEADD(day, 20, GETDATE()), 'ACTIVE', 'ALL', 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-MKT05')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, MAX_USES, USED_COUNT, VALID_FROM, VALID_TO, STATUS, SCOPE_TYPE, ORGANIZER_CODE)
  VALUES ('PRM-MKT05', 'MKT-OFF20', 'Dinonaktifkan admin', 20.00, 50, 2, DATEADD(day, -5, GETDATE()), DATEADD(day, 20, GETDATE()), 'DISABLED', 'ALL', 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO WHERE CODE = 'PRM-MKT06')
  INSERT INTO dbo.T_PROMO (CODE, PROMO_CODE, DESCRIPTION, DISCOUNT_PERCENT, MAX_DISCOUNT_AMOUNT, MIN_PURCHASE, MAX_USES, USED_COUNT, MAX_PER_USER, VALID_FROM, VALID_TO, STATUS, SCOPE_TYPE, ORGANIZER_CODE)
  VALUES ('PRM-MKT06', 'MKT-USED10', 'Ada riwayat pakai', 10.00, 50000, 100000, 100, 3, 1, DATEADD(day, -10, GETDATE()), DATEADD(day, 20, GETDATE()), 'ACTIVE', 'EVENT', 'USR-ORGANIZER');

-- Scopes for MKT-DATANG50 (category) + MKT-USED10 (event) --
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO_SCOPE WHERE PROMO_CODE = 'PRM-MKT02')
  INSERT INTO dbo.T_PROMO_SCOPE (CODE, PROMO_CODE, SCOPE_TYPE, CATEGORY_CODE) VALUES ('PSC-MKT02', 'PRM-MKT02', 'CATEGORY', 'KONSER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO_SCOPE WHERE PROMO_CODE = 'PRM-MKT06')
  INSERT INTO dbo.T_PROMO_SCOPE (CODE, PROMO_CODE, SCOPE_TYPE, EVENT_CODE)
  SELECT 'PSC-MKT06', 'PRM-MKT06', 'EVENT', CODE FROM dbo.T_EVENT WHERE ORGANIZER_CODE = 'USR-ORGANIZER' AND IS_DELETED = 0 ORDER BY CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;

-- Usage history for MKT-USED10 (3 orders) --
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO_USAGE WHERE CODE = 'PU-MKT01')
  INSERT INTO dbo.T_PROMO_USAGE (CODE, PROMO_CODE, ORDER_CODE, USER_CODE, DISCOUNT_AMOUNT, USED_AT)
  SELECT 'PU-MKT01', 'PRM-MKT06', CODE, 'USR-AUDIENCE', 25000, DATEADD(day, -2, GETDATE()) FROM dbo.T_ORDER WHERE STATUS = 'PAID' ORDER BY ORDER_DATE DESC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
IF NOT EXISTS (SELECT 1 FROM dbo.T_PROMO_USAGE WHERE CODE = 'PU-MKT02')
  INSERT INTO dbo.T_PROMO_USAGE (CODE, PROMO_CODE, ORDER_CODE, USER_CODE, DISCOUNT_AMOUNT, USED_AT)
  SELECT 'PU-MKT02', 'PRM-MKT06', CODE, 'USR-AUDIENCE', 30000, DATEADD(day, -1, GETDATE()) FROM dbo.T_ORDER WHERE STATUS = 'PAID' ORDER BY ORDER_DATE DESC OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY;

-- 5 ad campaigns: draft / pending_payment / pending_approval / live / rejected(+ended/paused) --
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_CAMPAIGN WHERE CODE = 'ADC-MKT01')
  INSERT INTO dbo.T_AD_CAMPAIGN (CODE, TITLE, IMAGE_URL, TARGET_URL, POSITION, START_AT, END_AT, STATUS, PAYMENT_STATUS, APPROVAL_STATUS, COST, ORGANIZER_CODE)
  VALUES ('ADC-MKT01', 'Iklan Draft Banner', 'https://picsum.photos/seed/mkt-ad1/800/450', 'https://example.com/draft', 'HOME_BANNER', DATEADD(day, 5, GETDATE()), DATEADD(day, 12, GETDATE()), 'DRAFT', 'UNPAID', 'PENDING', 1050000, 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_CAMPAIGN WHERE CODE = 'ADC-MKT02')
  INSERT INTO dbo.T_AD_CAMPAIGN (CODE, TITLE, IMAGE_URL, TARGET_URL, POSITION, START_AT, END_AT, STATUS, PAYMENT_STATUS, APPROVAL_STATUS, COST, ORGANIZER_CODE)
  VALUES ('ADC-MKT02', 'Menunggu Pembayaran', 'https://picsum.photos/seed/mkt-ad2/800/450', 'https://example.com/pay', 'HOME_BANNER', DATEADD(day, 2, GETDATE()), DATEADD(day, 9, GETDATE()), 'PENDING_PAYMENT', 'UNPAID', 'PENDING', 1200000, 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_CAMPAIGN WHERE CODE = 'ADC-MKT03')
  INSERT INTO dbo.T_AD_CAMPAIGN (CODE, TITLE, IMAGE_URL, TARGET_URL, POSITION, START_AT, END_AT, STATUS, PAYMENT_STATUS, APPROVAL_STATUS, COST, ORGANIZER_CODE)
  VALUES ('ADC-MKT03', 'Menunggu Persetujuan', 'https://picsum.photos/seed/mkt-ad3/800/450', 'https://example.com/approve', 'EVENT_LIST', DATEADD(day, 1, GETDATE()), DATEADD(day, 8, GETDATE()), 'PENDING_APPROVAL', 'PAID', 'PENDING', 640000, 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_CAMPAIGN WHERE CODE = 'ADC-MKT04')
  INSERT INTO dbo.T_AD_CAMPAIGN (CODE, TITLE, IMAGE_URL, TARGET_URL, POSITION, START_AT, END_AT, STATUS, PAYMENT_STATUS, APPROVAL_STATUS, COST, ORGANIZER_CODE)
  VALUES ('ADC-MKT04', 'Tayang Sekarang', 'https://picsum.photos/seed/mkt-ad4/800/450', 'https://example.com/live', 'HOME_BANNER', DATEADD(day, -2, GETDATE()), DATEADD(day, 10, GETDATE()), 'LIVE', 'PAID', 'APPROVED', 1800000, 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_CAMPAIGN WHERE CODE = 'ADC-MKT05')
  INSERT INTO dbo.T_AD_CAMPAIGN (CODE, TITLE, IMAGE_URL, TARGET_URL, POSITION, START_AT, END_AT, STATUS, PAYMENT_STATUS, APPROVAL_STATUS, REJECT_NOTE, COST, ORGANIZER_CODE)
  VALUES ('ADC-MKT05', 'Ditolak Admin', 'https://picsum.photos/seed/mkt-ad5/800/450', 'https://example.com/reject', 'SIDEBAR', DATEADD(day, -5, GETDATE()), DATEADD(day, 5, GETDATE()), 'REJECTED', 'PAID', 'REJECTED', 'Materi tidak sesuai kebijakan', 1000000, 'USR-ORGANIZER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_CAMPAIGN WHERE CODE = 'ADC-MKT06')
  INSERT INTO dbo.T_AD_CAMPAIGN (CODE, TITLE, IMAGE_URL, TARGET_URL, POSITION, START_AT, END_AT, STATUS, PAYMENT_STATUS, APPROVAL_STATUS, COST, ORGANIZER_CODE)
  VALUES ('ADC-MKT06', 'Sudah Selesai', 'https://picsum.photos/seed/mkt-ad6/800/450', 'https://example.com/ended', 'HOME_BANNER', DATEADD(day, -10, GETDATE()), DATEADD(day, -1, GETDATE()), 'ENDED', 'PAID', 'APPROVED', 1350000, 'USR-ORGANIZER');

-- Ad daily stats for LIVE campaign (7 days) + one other for chart variety --
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_STAT_DAILY WHERE CAMPAIGN_CODE = 'ADC-MKT04' AND STAT_DATE = CAST(DATEADD(day, -6, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE, IMPRESSIONS, CLICKS) VALUES ('ADC-MKT04', CAST(DATEADD(day, -6, GETDATE()) AS DATE), 1200, 45);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_STAT_DAILY WHERE CAMPAIGN_CODE = 'ADC-MKT04' AND STAT_DATE = CAST(DATEADD(day, -5, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE, IMPRESSIONS, CLICKS) VALUES ('ADC-MKT04', CAST(DATEADD(day, -5, GETDATE()) AS DATE), 1800, 62);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_STAT_DAILY WHERE CAMPAIGN_CODE = 'ADC-MKT04' AND STAT_DATE = CAST(DATEADD(day, -4, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE, IMPRESSIONS, CLICKS) VALUES ('ADC-MKT04', CAST(DATEADD(day, -4, GETDATE()) AS DATE), 2100, 88);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_STAT_DAILY WHERE CAMPAIGN_CODE = 'ADC-MKT04' AND STAT_DATE = CAST(DATEADD(day, -3, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE, IMPRESSIONS, CLICKS) VALUES ('ADC-MKT04', CAST(DATEADD(day, -3, GETDATE()) AS DATE), 2500, 110);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_STAT_DAILY WHERE CAMPAIGN_CODE = 'ADC-MKT04' AND STAT_DATE = CAST(DATEADD(day, -2, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE, IMPRESSIONS, CLICKS) VALUES ('ADC-MKT04', CAST(DATEADD(day, -2, GETDATE()) AS DATE), 3000, 95);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_STAT_DAILY WHERE CAMPAIGN_CODE = 'ADC-MKT04' AND STAT_DATE = CAST(DATEADD(day, -1, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE, IMPRESSIONS, CLICKS) VALUES ('ADC-MKT04', CAST(DATEADD(day, -1, GETDATE()) AS DATE), 2800, 120);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_STAT_DAILY WHERE CAMPAIGN_CODE = 'ADC-MKT04' AND STAT_DATE = CAST(GETDATE() AS DATE))
  INSERT INTO dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE, IMPRESSIONS, CLICKS) VALUES ('ADC-MKT04', CAST(GETDATE() AS DATE), 1500, 60);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_STAT_DAILY WHERE CAMPAIGN_CODE = 'ADC-MKT03' AND STAT_DATE = CAST(DATEADD(day, -2, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE, IMPRESSIONS, CLICKS) VALUES ('ADC-MKT03', CAST(DATEADD(day, -2, GETDATE()) AS DATE), 800, 20);
IF NOT EXISTS (SELECT 1 FROM dbo.T_AD_STAT_DAILY WHERE CAMPAIGN_CODE = 'ADC-MKT03' AND STAT_DATE = CAST(DATEADD(day, -1, GETDATE()) AS DATE))
  INSERT INTO dbo.T_AD_STAT_DAILY (CAMPAIGN_CODE, STAT_DATE, IMPRESSIONS, CLICKS) VALUES ('ADC-MKT03', CAST(DATEADD(day, -1, GETDATE()) AS DATE), 900, 30);

-- 8 news: 4 published, 1 draft, 1 scheduled (future), 2 archived (one published→archived) --
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NWS-MKT01')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, IMAGE_URL, NEWS_CATEGORY_CODE, STATUS, AUTHOR_CODE, PUBLISHED_AT, VIEW_COUNT, IS_DELETED)
  VALUES ('NWS-MKT01', 'Tips Sukses Jualan Tiket Online', 'tips-sukses-jualan-tiket-online', 'Strategi promosi event agar laris.', '<p>Gunakan promo terbatas dan banner yang menarik.</p>', 'https://picsum.photos/seed/nws-mkt01/800/450', 'TIPS', 'PUBLISHED', 'USR-ORGANIZER', DATEADD(day, -5, GETDATE()), 120, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NWS-MKT02')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, AUTHOR_CODE, PUBLISHED_AT, VIEW_COUNT, IS_DELETED)
  VALUES ('NWS-MKT02', 'Jadwal Event Bulan Depan', 'jadwal-event-bulan-depan-mkt', 'Rangkuman event pilihan.', '<p>Jangan lewatkan konser dan festival bulan depan.</p>', 'INFO', 'PUBLISHED', 'USR-ORGANIZER', DATEADD(day, -3, GETDATE()), 85, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NWS-MKT03')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, EVENT_CATEGORY_CODE, STATUS, AUTHOR_CODE, PUBLISHED_AT, VIEW_COUNT, IS_DELETED)
  VALUES ('NWS-MKT03', 'Promo Merdeka Tiket Hemat', 'promo-merdeka-tiket-hemat', 'Diskon spesial kemerdekaan.', '<p>Gunakan kode MERDEKA20 untuk potongan.</p>', 'PROMO', 'KONSER', 'PUBLISHED', 'USR-ORGANIZER', DATEADD(day, -1, GETDATE()), 210, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NWS-MKT04')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, AUTHOR_CODE, PUBLISHED_AT, VIEW_COUNT, IS_DELETED)
  VALUES ('NWS-MKT04', 'Liputan Festival Kuliner Nusantara', 'liputan-festival-kuliner-nusantara', 'Ribuan pengunjung memadati lokasi.', '<p>Festival berlangsung 3 hari dengan 100 tenant.</p>', 'LIPUTAN', 'PUBLISHED', 'USR-ORGANIZER', DATEADD(day, -2, GETDATE()), 65, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NWS-MKT05')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, AUTHOR_CODE, IS_DELETED)
  VALUES ('NWS-MKT05', 'Draf Berita Rahasia', 'draf-berita-rahasia', 'Belum terbit.', '<p>Rahasia.</p>', 'INFO', 'DRAFT', 'USR-ORGANIZER', 0);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NWS-MKT06')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, AUTHOR_CODE, SCHEDULED_AT, IS_DELETED)
  VALUES ('NWS-MKT06', 'Berita Terjadwal Besok', 'berita-terjadwal-besok', 'Akan terbit otomatis besok.', '<p>Ini berita terjadwal.</p>', 'INFO', 'DRAFT', 'USR-ORGANIZER', DATEADD(day, 1, GETDATE()), 0);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NWS-MKT07')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, AUTHOR_CODE, PUBLISHED_AT, VIEW_COUNT, IS_DELETED)
  VALUES ('NWS-MKT07', 'Arsip Berita Lama', 'arsip-berita-lama', 'Sudah diarsipkan.', '<p>Konten lama yang diarsip.</p>', 'INFO', 'ARCHIVED', 'USR-ORGANIZER', DATEADD(day, -20, GETDATE()), 15, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.T_NEWS WHERE CODE = 'NWS-MKT08')
  INSERT INTO dbo.T_NEWS (CODE, TITLE, SLUG, SUMMARY, BODY, NEWS_CATEGORY_CODE, STATUS, AUTHOR_CODE, PUBLISHED_AT, VIEW_COUNT, IS_DELETED)
  VALUES ('NWS-MKT08', 'Berita Diarsip Setelah Terbit', 'berita-diarsip-setelah-terbit', 'Ditarik dari publik.', '<p>Sebelumnya tayang, kini diarsip.</p>', 'TIPS', 'ARCHIVED', 'USR-ORGANIZER', DATEADD(day, -10, GETDATE()), 40, 0);

COMMIT TRAN;
