-- Demo seed for EVENT module (My Events workflow).
-- ONLY touches T_* tables. Owner USR-ORGANIZER, buyer USR-AUDIENCE,
-- checker USR-OFFICER. Slugs follow the migrate9 backfill format
-- (slugified title + '-' + code). CP_* never modified.
-- Requires: migrate4 (accounts) + migrate5/6 (T_* tables) + migrate9 (columns).
-- Idempotent (IF NOT EXISTS per CODE). Run:
--   sqlcmd -S <host>,<port> -U <user> -P <pass> -d <DB_NAME> -C -b -i scripts/seed-event.sql
-- Or: task seed-event
SET XACT_ABORT ON;
BEGIN TRAN;

-- 6 events: draft / published / almost-full / ended / cancelled / published ----
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-E01')
  INSERT INTO dbo.T_EVENT (CODE, SLUG, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, ADDRESS, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT)
  VALUES ('EVT-E01', 'konser-demo-draft-evt-e01', 'USR-ORGANIZER', 'CTY-JKT', 'KONSER', 'Konser Demo Draft', 'Masih disiapkan panitia.', 'Studio A', 'Jl. Demo No. 1', DATEADD(day, 30, GETDATE()), DATEADD(day, 30, GETDATE()), 'DRAFT', 10.00);
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-E02')
  INSERT INTO dbo.T_EVENT (CODE, SLUG, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, ADDRESS, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT, PUBLISHED_AT, POSTER_URL)
  VALUES ('EVT-E02', 'festival-demo-published-evt-e02', 'USR-ORGANIZER', 'CTY-BDG', 'FESTIVAL', 'Festival Demo Published', 'Sudah tayang dan siap jual.', 'Lapangan B', 'Jl. Demo No. 2', DATEADD(day, 40, GETDATE()), DATEADD(day, 42, GETDATE()), 'PUBLISHED', 10.00, DATEADD(day, -2, GETDATE()), 'https://picsum.photos/seed/tikto-e02/800/450');
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-E03')
  INSERT INTO dbo.T_EVENT (CODE, SLUG, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT, PUBLISHED_AT)
  VALUES ('EVT-E03', 'workshop-hampir-habis-evt-e03', 'USR-ORGANIZER', 'CTY-SBY', 'WORKSHOP', 'Workshop Hampir Habis', 'Tersisa sedikit kursi.', 'Ruang C', DATEADD(day, 20, GETDATE()), DATEADD(day, 20, GETDATE()), 'PUBLISHED', 12.00, DATEADD(day, -5, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-E04')
  INSERT INTO dbo.T_EVENT (CODE, SLUG, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT, PUBLISHED_AT)
  VALUES ('EVT-E04', 'konser-selesai-evt-e04', 'USR-ORGANIZER', 'CTY-YK', 'KONSER', 'Konser Selesai', 'Sudah berlalu.', 'Hall D', DATEADD(day, -10, GETDATE()), DATEADD(day, -9, GETDATE()), 'COMPLETED', 10.00, DATEADD(day, -30, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-E05')
  INSERT INTO dbo.T_EVENT (CODE, SLUG, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT, CANCEL_REASON, PUBLISHED_AT)
  VALUES ('EVT-E05', 'lomba-batal-evt-e05', 'USR-ORGANIZER', 'CTY-SMG', 'SPORT', 'Lomba Batal', 'Dibatalkan panitia.', 'Stadion E', DATEADD(day, 15, GETDATE()), DATEADD(day, 15, GETDATE()), 'CANCELLED', 8.00, 'Izin keramaian tidak turun', DATEADD(day, -3, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_EVENT WHERE CODE = 'EVT-E06')
  INSERT INTO dbo.T_EVENT (CODE, SLUG, ORGANIZER_CODE, CITY_CODE, EVENT_CATEGORY_CODE, TITLE, DESCRIPTION, VENUE, ADDRESS, START_AT, END_AT, STATUS, PLATFORM_FEE_PERCENT, PUBLISHED_AT, POSTER_URL)
  VALUES ('EVT-E06', 'anime-fest-peserta-evt-e06', 'USR-ORGANIZER', 'CTY-JKT', 'ANIME', 'Anime Fest Peserta', 'Penuh peserta dan keseruan.', 'Hall F', 'Jl. Demo No. 6', DATEADD(day, 25, GETDATE()), DATEADD(day, 26, GETDATE()), 'PUBLISHED', 10.00, DATEADD(day, -10, GETDATE()), 'https://picsum.photos/seed/tikto-e06/800/450');

-- Ticket types (2-3 per event, one inactive on EVT-E02) ------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-E01A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, DESCRIPTION, PRICE, QUOTA, IS_ACTIVE, SORT_ORDER) VALUES ('TT-E01A', 'EVT-E01', 'Regular', 'Akses festival', 100000, 200, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-E02A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, DESCRIPTION, PRICE, QUOTA, IS_ACTIVE, SORT_ORDER) VALUES ('TT-E02A', 'EVT-E02', 'Regular', 'Akses 3 hari', 150000, 500, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-E02B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, DESCRIPTION, PRICE, QUOTA, MAX_PER_PERSON, IS_ACTIVE, SORT_ORDER) VALUES ('TT-E02B', 'EVT-E02', 'VIP', 'Depan panggung + merch', 500000, 100, 4, 0, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-E03A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA, IS_ACTIVE, SORT_ORDER) VALUES ('TT-E03A', 'EVT-E03', 'Peserta', 250000, 50, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-E04A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA, IS_ACTIVE, SORT_ORDER) VALUES ('TT-E04A', 'EVT-E04', 'Regular', 120000, 300, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-E05A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, PRICE, QUOTA, IS_ACTIVE, SORT_ORDER) VALUES ('TT-E05A', 'EVT-E05', 'Pelari', 80000, 400, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-E06A')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, DESCRIPTION, PRICE, QUOTA, MAX_PER_PERSON, IS_ACTIVE, SORT_ORDER) VALUES ('TT-E06A', 'EVT-E06', 'Day Pass', 'Satu hari penuh', 90000, 300, 5, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-E06B')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, DESCRIPTION, PRICE, QUOTA, IS_ACTIVE, SORT_ORDER) VALUES ('TT-E06B', 'EVT-E06', 'Full Pass', 'Dua hari + poster', 160000, 150, 1, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET_TYPE WHERE CODE = 'TT-E06C')
  INSERT INTO dbo.T_TICKET_TYPE (CODE, EVENT_CODE, NAME, DESCRIPTION, PRICE, QUOTA, IS_ACTIVE, SORT_ORDER) VALUES ('TT-E06C', 'EVT-E06', 'Gratis Anak', 'Di bawah 5 tahun', 0, 100, 1, 3);

-- Orders: almost-full EVT-E03 (46/50) ---------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-ESC01')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-ESC01', 'EVT-E03', 'USR-AUDIENCE', 'TT-E03A', 46, 11500000, 0, 1380000, 10120000, 'PAID', DATEADD(day, -4, GETDATE()));

-- Orders EVT-E06: 10 orders = 30 tickets (8 PAID, 1 PENDING, 1 CANCELLED) ------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA01')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA01', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06A', 3, 270000, 0, 27000, 243000, 'PAID', DATEADD(day, -9, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA02')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA02', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06B', 2, 320000, 0, 32000, 288000, 'PAID', DATEADD(day, -8, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA03')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA03', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06A', 4, 360000, 0, 36000, 324000, 'PAID', DATEADD(day, -7, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA04')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA04', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06C', 1, 0, 0, 0, 0, 'PAID', DATEADD(day, -6, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA05')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA05', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06B', 5, 800000, 0, 80000, 720000, 'PAID', DATEADD(day, -5, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA06')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA06', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06A', 2, 180000, 0, 18000, 162000, 'PAID', DATEADD(day, -4, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA07')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA07', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06A', 3, 270000, 0, 27000, 243000, 'PAID', DATEADD(day, -3, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA08')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA08', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06B', 4, 640000, 0, 64000, 576000, 'PAID', DATEADD(day, -2, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA09')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA09', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06A', 3, 270000, 0, 27000, 243000, 'PENDING', DATEADD(day, -1, GETDATE()));
IF NOT EXISTS (SELECT 1 FROM dbo.T_ORDER WHERE CODE = 'ORD-EA10')
  INSERT INTO dbo.T_ORDER (CODE, EVENT_CODE, BUYER_CODE, TICKET_TYPE_CODE, QTY, GROSS_AMOUNT, DISCOUNT_AMOUNT, PLATFORM_FEE, NET_AMOUNT, STATUS, ORDER_DATE)
  VALUES ('ORD-EA10', 'EVT-E06', 'USR-AUDIENCE', 'TT-E06B', 3, 480000, 0, 48000, 432000, 'CANCELLED', DATEADD(day, -1, GETDATE()));

-- 30 tickets (12 USED + 18 ACTIVE) --------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E001')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, EMAIL, PHONE, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E001', 'ORD-EA01', 'QR-E001', 'Ayu Lestari', 'ayu@mail.com', '081201', 'USED', DATEADD(day, -2, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E002')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, EMAIL, STATUS) VALUES ('TIX-E002', 'ORD-EA01', 'QR-E002', 'Budi Santoso', 'budi@mail.com', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E003')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E003', 'ORD-EA01', 'QR-E003', 'Citra Ayu', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E004')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, EMAIL, PHONE, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E004', 'ORD-EA02', 'QR-E004', 'Dedi Kurnia', 'dedi@mail.com', '081204', 'USED', DATEADD(day, -2, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E005')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E005', 'ORD-EA02', 'QR-E005', 'Eka Putri', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E006')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E006', 'ORD-EA03', 'QR-E006', 'Fajar Ramadhan', 'USED', DATEADD(day, -1, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E007')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E007', 'ORD-EA03', 'QR-E007', 'Gita Sari', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E008')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E008', 'ORD-EA03', 'QR-E008', 'Hadi Wijaya', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E009')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E009', 'ORD-EA03', 'QR-E009', 'Indah Permata', 'USED', DATEADD(day, -1, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E010')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, EMAIL, STATUS) VALUES ('TIX-E010', 'ORD-EA04', 'QR-E010', 'Joko Susilo', 'joko@mail.com', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E011')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E011', 'ORD-EA05', 'QR-E011', 'Kirana Dewi', 'USED', DATEADD(day, -1, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E012')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E012', 'ORD-EA05', 'QR-E012', 'Lukman Hakim', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E013')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E013', 'ORD-EA05', 'QR-E013', 'Maya Anggraini', 'USED', DATEADD(day, -1, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E014')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E014', 'ORD-EA05', 'QR-E014', 'Nadia Rahma', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E015')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E015', 'ORD-EA05', 'QR-E015', 'Oscar Mahesa', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E016')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, EMAIL, PHONE, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E016', 'ORD-EA06', 'QR-E016', 'Putri Ayu', 'putri@mail.com', '081216', 'USED', DATEADD(hour, -5, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E017')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E017', 'ORD-EA06', 'QR-E017', 'Qoriatul', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E018')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E018', 'ORD-EA07', 'QR-E018', 'Rina Marlina', 'USED', DATEADD(hour, -4, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E019')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E019', 'ORD-EA07', 'QR-E019', 'Sinta Dewi', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E020')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E020', 'ORD-EA07', 'QR-E020', 'Tono Prasetyo', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E021')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E021', 'ORD-EA08', 'QR-E021', 'Udin Saefudin', 'USED', DATEADD(hour, -3, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E022')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E022', 'ORD-EA08', 'QR-E022', 'Vina Melinda', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E023')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E023', 'ORD-EA08', 'QR-E023', 'Wawan Setiawan', 'USED', DATEADD(hour, -3, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E024')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E024', 'ORD-EA08', 'QR-E024', 'Yoga Saputra', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E025')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, EMAIL, STATUS) VALUES ('TIX-E025', 'ORD-EA09', 'QR-E025', 'Zahra Aulia', 'zahra@mail.com', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E026')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E026', 'ORD-EA09', 'QR-E026', 'Andi Nugraha', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E027')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E027', 'ORD-EA09', 'QR-E027', 'Bima Sakti', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E028')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS, CHECKED_IN_AT, CHECKED_IN_BY) VALUES ('TIX-E028', 'ORD-EA10', 'QR-E028', 'Candra Kirana', 'USED', DATEADD(hour, -2, GETDATE()), 'USR-OFFICER');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E029')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E029', 'ORD-EA10', 'QR-E029', 'Dian Puspita', 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM dbo.T_TICKET WHERE CODE = 'TIX-E030')
  INSERT INTO dbo.T_TICKET (CODE, ORDER_CODE, QR_CODE, HOLDER_NAME, STATUS) VALUES ('TIX-E030', 'ORD-EA10', 'QR-E030', 'Eko Wahyono', 'ACTIVE');

COMMIT TRAN;
